### ISSUE TITLE
(a) consume flow does not work with GraphQL assets on Mumbai (b) asset returns as None

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1007]
[Update Oct 14 trentmc]: at first we had both issues (a) and (b). It wasn't clear if they were the same. But, they were different. I could have split the issues, but we have branches & PRs with "1007" so I'm keeping it all here.

- (a) was reported in detail right below, in this description. It was solved on Oct 13 [see this comment](https://github.com/oceanprotocol/ocean.py/issues/1007#issuecomment-1277611428)
- (b) was reported in detail in [this comment](https://github.com/oceanprotocol/ocean.py/issues/1007#issuecomment-1276286245). Solution is now WIP, via [this PR](https://github.com/oceanprotocol/ocean.py/pull/1009)
- We'll close this issue when both (a) and (b) are solved.

----
**Describe the bug - issue (a)**
Consume flow does not work with an asset of GraphQL type, on Mumbai. 
Running the following command
`order_tx_id = ocean.assets.pay_for_access_service(asset, bob_wallet)`
throws this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 808, in pay_for_access_service
    raise AssetNotConsumable(consumable_result)
ocean_lib.agreements.consumable.AssetNotConsumable: 2
```

**To Reproduce**
1. Perform Set envvars from Quickstart: Remotely Publish Data NFT & Datatoken (https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/simple-remote.md#set-envvars)
```
export REMOTE_TEST_PRIVATE_KEY1=<your REMOTE_TEST_PRIVATE_KEY1>
export REMOTE_TEST_PRIVATE_KEY2=<your REMOTE_TEST_PRIVATE_KEY2>
```
2. Perform Setup in Python from Quickstart: Remotely Publish Data NFT & Datatoken (https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/simple-remote.md#setup-in-python)

```
# Create Ocean instance
import os
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config("https://rpc-mumbai.maticvigil.com")
config["BLOCK_CONFIRMATIONS"] = 1 #faster
ocean = Ocean(config)

# Create Alice's wallet
import os
from ocean_lib.web3_internal.wallet import Wallet

alice_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY1')
alice_wallet = Wallet(ocean.web3, alice_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert alice_wallet.web3.eth.get_balance(alice_wallet.address) > 0, "Alice needs MATIC"

# Create Bob's wallet.
bob_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY2')
bob_wallet = Wallet(ocean.web3, bob_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert bob_wallet.web3.eth.get_balance(bob_wallet.address) > 0, "Bob needs MATIC"

```

3. Alice creates a GraphQL asset
```
name="Data NFTs in Ocean - 2"
url= "https://v4.subgraph.goerli.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph"
query="""query{nfts(orderBy: createdTimestamp, orderDirection:desc){id symbol createdTimestamp}}"""
asset = ocean.assets.create_graphql_asset(name, url, query, alice_wallet)
```

4. Alice mints datatokens
```
datatoken_address = asset.datatokens[0]["address"]
datatoken = ocean.get_datatoken(datatoken_address)
to_address = bob_wallet.address
amt_tokens = ocean.to_wei(10)
datatoken.mint(to_address, amt_tokens, alice_wallet)
```

5. Bob sends a datatoken to the service, for access
`order_tx_id = ocean.assets.pay_for_access_service(asset, bob_wallet)`

**Expected behavior**
Datatoken transfer performed succesfully and transaction id returned.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux Ubuntu 22.04.1 running on VMWare Workstation 16 Player
 - Python version: 3.8.14
 - ocean-lib version: 1.5.0
 - ocean-contracts version: 1.1.7

**Comment by trentmc** [comment]
I think I found a similar issue: it also fails on simple publish, in Polygon.

How to reproduce: 
1. go to [predict-eth.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md)
2. do step 6.1 
3. start going through step 6.2 as follows:

```python
url = "https://drive.google.com/uc?export=download&id=1uZakKrzkSYosD_wf-EFJusFhzlOGQRRy"
name = "ETH predictions"
asset = ocean.assets.create_url_asset(name, url, alice_wallet) #will take 30+ seconds
```

The last step will fail. While all the txs will go through, `asset` will come back as None.

**Comment by trentmc** [comment]
This is urgent because predict-eth needs to work. It's a live competition, and competitors need to submit for Monday, using the flow.

FYI it worked earlier. (Mon this week? Late last week?)

**Comment by alexcos20** [comment]
fix here: https://github.com/oceanprotocol/aquarius/pull/919  
It will be deployed shortly on all networks

**Comment by trentmc** [comment]
I just tested for this issue.

- I went through the "how to reproduce" in the description. It still fails: `asset` comes back as `None`
- I also went through my reporting of a (same?) issue in [the comment above](https://github.com/oceanprotocol/ocean.py/issues/1007#issuecomment-1276286245). It fails the same way: `asset` comes back as `None`
