### ISSUE TITLE
Add compute-to-data example README: make it work

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#101]
Goal of this issue: write down some super-basic flow for compute-to-data example, as a new file in ocean.py READMEs repo. Just "make it work". Rough & messy is ok!

Then, Trent will follow up with "make it good" in #279

-----

RESULT: @alexcos20 just shared to me (@trentmc) the following steps. This is enough of a starting point for me to work with. Therefore I will close this issue.

**STEPS:**
1. clone https://github.com/oceanprotocol/ocean.js-cli  , follow Readme how to install & run
2. run "npm run cli h"  to get a list of all commands
3. publish your python algo:  npm run cli publishAlgo metadata/pythonAlgo.json     , you will get a did (ex: did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158)
4. publish your dataset :     npm run cli publish metadata/simpleDataset.json  - (ex: did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb)
5. allow your algo for C2D for that dataset:       npm run cli allowAlgo did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158
6. start a compute job:       npm run cli startCompute did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158   (you will get a jobId   3a985f1f88af4fe08e26b4d0d857be57)
7. get compute job status:      npm run cli getCompute 3a985f1f88af4fe08e26b4d0d857be57
8. watch the logs & algo output above

**Comment by trentmc** [comment]
Doing this will also help for #8 "Epic: datatokens demo showing data science flow"

**Comment by kremalicious** [comment]
no, please not more READMEs. There should be a proper compute-to-date example, see https://github.com/oceanprotocol/ocean.py/issues/113

**Comment by trentmc** [comment]
> please not more README
I'm fine with not forcing this to be a README. it could be in docs.oceanprotocol.com. Though if it's there it will be harder to maintain and keep accurate than in here. And if in here, how do you do it if it isn't a README?

> see #113
I don't see the connection with #113. That is for developers wanting to *improve* ocean.py itself. Whereas this issue is for people wanting to simply *use* ocean.py.

**Comment by kremalicious** [comment]
added 2 use cases to #113, but agree it should focus on the develop ocean.py instructions.

Think the main issue is that mixup of docs & examples. As a developer I expect example code to run, so having that in markdown is not that useful. Also makes it hard to auto-verify it on code changes and then we end up quickly with wrong code examples as the codebase progresses.

So my suggestion would be that every example file can be run, with instructions on how to do so in one readme in examples folder. So all the various documents in the READMEs folder should be extracted into the example folder.

As for only compute-to-data, we kinda have this here https://github.com/oceanprotocol/ocean.py/blob/master/READMEs/compute-flow.md

But in the end it should be a runnable example referenced from the main examples readme. Then we do not need a dedicated compute flow doc with code examples in it

**Comment by trentmc** [comment]
> but agree it should focus on the develop ocean.py instructions.

:)

> As for only compute-to-data, we kinda have this here 
https://github.com/oceanprotocol/ocean.py/blob/master/READMEs/compute-flow.md

Yep. But it's obsolete. The original name of this ticket was about reviving exactly that code:)

> Think the main issue is that mixup of docs & examples ... [more]

This is the crux of the issue, I think. 
* One extreme is simply a .md with a mix of text and code. Pro: ease of understanding, which is the main point of a README. Con: can't easily copy-and-paste all code. Con: hard to keep code up-to-date / maintained.
* Opposite extreme: separate .py code files and markdown files. Pro: can easily copy-and-paste all code, easier to keep code up-to-date / maintained. Con: not easy to follow because text and code is in two separate places, which hurts understanding / onboarding, the whole point of READMEs.

Is there a good technical way to solve this? E.g. is there markdown which can refer to specific sections of code that gets auto-updated?

**Comment by Akif-G** [comment]
@trentmc 
> Is there a good technical way to solve this? E.g. is there markdown which can refer to specific sections of code that gets auto-updated?

We can use Jupyter Notebooks. Github Supports markdown and its executable.

**Comment by trentmc** [comment]
> We can use Jupyter Notebooks. Github Supports markdown and its executable.

I don't understand how Jupyter would refer to specific sections of code that get auto-updated. 

I just googled around. This is more what I was hoping would exist - it seems that it does:) 

https://github.com/BurdetteLamar/markdown_helper#whats-a-markdown-helper

"File inclusion: to include text from other files, as code-block or markdown."

**Comment by trentmc** [comment]
More comments.

I like Jupyter. But I'm on the fence whether we should use it here.
For this, I see it as a tradeoff of: extra friction to go to Jupyter (vs Github readme), versus how much better experience the user has once in Jupyter (vs readme). (edited) 

Here's a couple datapoints to compare
- scikit learn: https://scikit-learn.org/stable/modules/linear_model.html#lars-lasso
- tensorflow: https://www.tensorflow.org/tutorials/quickstart/beginner (edited) 

Another datapoint: we are hoping to move from README-heavy docs to proper readthefile type docs. [Here's the issue](https://github.com/oceanprotocol/multi-repo-issue/issues/80). Scikit-learn and tensorflow follow that shape as well a bit.

**Comment by trentmc** [comment]
I now have enough to do the next issue. We can close this one.
