### ISSUE TITLE
Ocean Brownie -- phase 2 issue

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#1019]
This issue collects plans for Brownie integration -- phase 2.

- [x] remove direct usages of web3.py, especially with get_transaction_receipt, change with wait_for_transaction_status instead
- [x] when deploying contracts from barge directly, using contract_base.deploy, do it via Brownie
- [ ] proposal: instead of returning the txid from the contract transaction, return the TransactionReceipt object directly, in order to facilitate access to events, attributes etc. -> this was not done in phase 1 because it requires large-scale changes in typing, where we always expect the tx_id as str, not as a TransactionReceipt (structural changes)
- [x] refactor event handling to properly use transaction events
- [ ] run a code usage analysis and remove outdated/unused code
- [x] better structure for brownie contract handling, remove the custom wallet configs and rely on the network-config instead (happens now de facto, but we need to remove the old code) -> when doing this, move NETWORK_IDS to a file called networkutil or similar.
- [x] document network-config.sample copying
- [x] remove "0x" concatenation in exchange ids
- [ ] reinstate enforce types where needed (possibly we should keep it more lax to map to brownie?)
- [ ] look into removal of currency functions
- [x] refactor wallet: possibly use accounts
- [x] remove duplications related to gas price calculations
- [ ] document account clearing and network connection
- more...

**Comment by calina-c** [comment]
Discussion: Right now, we are working through the config dict towards brownie itself. We can not remove the config dict due to certain extra params needed (non-RPC related, e.g. aquarius url, provider url etc). But connecting to a certain network is done via the config dict, not brownie per se: the Ocean object is created based on the config dict and connects to the network ad-hoc. However, I think it would be more clear to do it the other way around: do a brownie network.connect(), then all ocean objects instantiated in that network can rely on the definitions in network-config, not the other way around.

It depends on how we want to do this, starting from the RPC or the chain? Starting from brownie to Ocean or Ocean to brownie? Possibly I'm not clear enough, but let's discuss this before going further.

**Comment by trentmc** [comment]
> It depends on how we want to do this, starting from the RPC or the chain? Starting from brownie to Ocean or Ocean to brownie? Possibly I'm not clear enough, but let's discuss this before going further.

Think of it this way: people using ocean.py may have other py code that uses brownie, side-by-side with ocean. It should all play well together.

So overall, it should be "starting from brownie to Ocean".

(Philosophically: Ocean tools need to be maximally useful, subject to "getting out of the way". The above suggestion is in line with that.)

**Comment by calina-c** [comment]
I am writing this in support of our pending discussion for ocean.py planning:

- TODO: review in 2b - randomize amount to send in ether -> follow-up

### 2c - Use accounts instead of custom wallets
* removes contract deployment, Ocean shouldn’t handle any deployment, just work with existing contracts (discussed with Alex)
* sign provider payloads using public keys
* only LocalAccounts should be used, since anything provider-related needs the private key to sign payloads. -> brownie has some sort of caching where it transforms LocalAccounts into Accounts and they become unusable. I added the accounts.clear() method into the readmes where necessary, but I wonder if we need to elaborate somewhere in the docs
* discussion related to typing: we DO need LocalAccounts for anything provider-related, but should we require LocalAccounts throughout ocean.py, or should we allow everything brownie offers (i.e. Account objects, hardware wallets etc.)? I personally find it confusing to allow Account in some places and only LocalAccount in others, so I would type everything to LocalAccount

### 2d - Properly use brownie configs
* for conformity to Brownie, Example Configs are now based on network name. The brownie network configuration file will be used under the hood to identify the RPC, chain id, etc.
* there are 2 possibilities here:
1. the user handles network connection, i.e. calls network.connect(“development”) or network.connect(“mumbai”) before anything
2. the config contains a “NETWORK_NAME”, making the contracts autoconfigurable: Ocean, OceanAssets and all contract models automatically connect to the network they are configured with
I chose the second option here, since it allows more flexibility when dealing with multiple networks. It also hides some aspects of Brownie from the user, as they just configure contracts and not connections. However, we can still opt for the 1st choice if agreed so.

After confirming the proper business logic, we should add some docs.

### Still pending
* removal of currency-related code, but I think that’s not a high priority right now
* reinstating enforce types and typing: Brownie is more lax than the previous version of ocean.py, and handles some conversions under the hood. This means I had to temporarily remove some typing enforcements. Some of them should be rediscussed and reinstated
* sometimes it happens for me on the local ganache to get nonce errors, which go away with time.sleep()s. I don’t see this happening on the CI ganache or anywhere else, so I want us to track this. I’ve seen a lot of complaints and issues online.

**Comment by calina-c** [comment]
Moved everything that is still relevant/valid in #977 and closing this
