### ISSUE TITLE
Installing ocean.py in Mac with M1 processor fail due to issues with Cryptography

### ISSUE THREAD

**Issue by jfdelgad** [oceanprotocol/ocean.py#1034]
**Describe the bug**

**To Reproduce**
1. Installing the library on Mac with M1 processors fail due to an issue with Cryptography library

**Expected behavior**
The library installation should succeed in M1 based computers.

**Desktop (please complete the following information):**
 - OS: MacOS
 - python 3.8+

Installing Cryptography succeeds in Mac with M1 but the version used in ocean.py since to have problems.

**Comment by trentmc** [comment]
Related previous issue: https://github.com/oceanprotocol/ocean.py/issues/887

**Comment by trentmc** [comment]
Note: full credit to this fix goes to @jfdelgad . I just did it to keep its change clean from other work, e.g. in https://github.com/oceanprotocol/ocean.py/pull/1046/files
