### ISSUE TITLE
override default behavior of interpreting special characters in strings

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/ocean.py#1040]
A string that contains a backlash or other special characters (urls, regular expressions, etc.) can be misinterpreted and we might be introducing an error ourselves without knowing it

Luckily in Python we have raw strings, which assure us that all the characters of a string are taken as literals

So I would like to suggest that either function parameters or arguments always be wrapped as a regular string, for example:

'url' would be r'url'

This would result in always knowing exactly what are we passing. That is not going to be modified. Less errors. Increase compatibility between operating systems and a more homogeneous code

**Comment by trentmc** [comment]
Where is the specific issue? What is the specific recommended action? Thanks!

FYI we use dynamic type-checking almost everywhere. So e.g. functions know what types are passing (strings, and beyond), and what types are being returned.
