### ISSUE TITLE
Publishing an asset by ocean.assets.create() on Mumbai returns NoneType instead of Asset class 

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1057]
**Describe the bug**
Publishing an asset on Mumbai network, by using the ocean.assets.create() method, returns a NoneType class instead of Asset class. I tested it 5 times, in two different days, with the same result.

**To Reproduce**

**Set envvars**
In the console:

```
export REMOTE_TEST_PRIVATE_KEY1=<private_key1>
export REMOTE_TEST_PRIVATE_KEY2=<private_key2>
```

**Setup in Python**
```
import os
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config("https://matic-mumbai.chainstacklabs.com")
config["BLOCK_CONFIRMATIONS"] = 1
ocean = Ocean(config)

# Create Alice's wallet
import os
from ocean_lib.web3_internal.wallet import Wallet

alice_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY1')
alice_wallet = Wallet(ocean.web3, alice_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert alice_wallet.web3.eth.get_balance(alice_wallet.address) > 0, "Alice needs MATIC"
print("Alice wallet created. Wallet address:", alice_wallet.address)

# Create Bob's wallet. While some flows just use Alice wallet, it's simpler to do all here.
bob_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY2')
bob_wallet = Wallet(ocean.web3, bob_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert bob_wallet.web3.eth.get_balance(bob_wallet.address) > 0, "Bob needs MATIC"
print("Bob wallet created. Wallet address:", bob_wallet.address)
```

**Create the asset**
```
date_created = "2022-11-03T12:36:11Z"
metadata = {
        "created": date_created,
        "updated": date_created,
        "description": "Branin dataset",
        "name": "Branin dataset",
        "type": "dataset",
        "author": "Trent",
        "license": "CC0: PublicDomain",}
from ocean_lib.structures.file_objects import UrlFile
url_file = UrlFile(url="https://raw.githubusercontent.com/trentmc/branin/main/branin.arff")
from ocean_lib.web3_internal.constants import ZERO_ADDRESS
asset = ocean.assets.create(
        metadata,
        alice_wallet,
        [url_file],
        datatoken_templates=[1],
        datatoken_names=["Datatoken 1"],
        datatoken_symbols=["DT1"],
        datatoken_minters=[alice_wallet.address],
        datatoken_fee_managers=[alice_wallet.address],
        datatoken_publish_market_order_fee_addresses=[ZERO_ADDRESS],
        datatoken_publish_market_order_fee_tokens=[ocean.OCEAN_address],
        datatoken_publish_market_order_fee_amounts=[0],
        datatoken_bytess=[[b""]],
)
INFO:ocean:Successfully created NFT with address 0x699a07C3a52E17f238469b30f2429A73D1b7357A.
INFO:ocean:Successfully created datatoken with address 0xBDD467f901852B3113Ef5E69D7B3E7454d50AaDF.
INFO:ocean_lib.data_provider.data_encryptor:Asset urls encrypted successfully, encrypted urls str: 0x04ec6f8c04c8ef3906663e4f62724aebc2a7cc320341b057dfb84fe2d958bc0bdb8878ace77ac1195fbda932d91ee2595b7c726bc68c807b1da6c30891bba708a2714b23f1cbbd28b512b853c3fa3f20cc08887f2a70a43a46365eaf0bbdc0f7fd86eb200c76a5b548e60870696dfd7a217ebc0e57904817c48ee43a753ad2551a1669d3c114b91cc8c2c0e3d41cb6d8c9138eadb841627e818d8440a654a6626076346cbc132b168c8f3e188ea42df1fbf5af1ccdb562b1ebd7f4111b6c41c1451483b3e4d47fd1d6dc4268ce57b058454ed3e6aad48ba72344d0eeb8bb7ecfb82e5ddf4d3852a6d419ceb082ac3c3579bc20654963d8adcc78cbbbe82e543e34c9dbe50a3e78efa568a35fcbe4d9c1e08fc6484da5540200179775eff95f8f30d06b144b5842e64c509b8a02160b6b992f9d66716221d5257833bce956cf, encryptedEndpoint https://v4.provider.mumbai.oceanprotocol.com/api/services/encrypt
INFO:ocean_lib.data_provider.data_encryptor:Asset urls encrypted successfully, encrypted urls str: 0x04f6fbfa2d11c206682cebaaf557ab9293ee4775f0d04f7dc6ed5e7c0ea9e5a4c4063308eb009a02aceb73b3a739c3c166a4a524d1ae4f6948fb4722b7ce61b2a67b2f854ff486f763a50e4c887c9c510f37e0e8515ee55947f62ca50fe59ed59dbeb240ae7971b924723dc39a79fdd8c3b2987ea3b2c5b496b3ba9f739d1316caa150d97da2efc389de7cbcb08a0f36706d531c2307e79bd00ad76c1f35285b9a2352fa7066d023643941e128328a3c0e5bfb8b1af6feab4a1d8c2ab98dcf410cff1c36690a132f2e46031c2063d58f206f1f02cf3b5933e80151c21f99dce0cce333529004a4ea5a6f2ffeaeb8177aa8a227a1741c00099540d3c1457c1a2a93d285cb2197926e3d129f9dc80e23544a34671bdc245d1d1e16ef2216ce0fe98d861acb3dc5c38d9c2aa101caa66b42b174742b2e4d238f53611b226c4b5d0dc12f243e3cc9511a37e7e23c948c423c1049db6bbba8cd4ac0f712c28daa3567bf3373b82bcefcc8aee295ee3b3c94c35898538f38158e0521ab80dcbabf99661718a81cad6244a5c6b0b0c38a42a85f3f2beff6147b2dbab3f7be5ee4e3d6f6a34f0fab8423bdef388832afa989b8042ba70de5ea3424af8553946881d28cecf2a3fae03fea8f6f151e1ba81a698448491e13e85ad9c0d71e5e95225b100545e28780a172b8e2d6e92af0002e2351a0809aa444a7d8a9e283b6052d079951d31df85ae476ae8bf882b598bc851cb4b8907b621f8cf205bfada03930a49022a348cf4fbe862d89267d3c63a01e8eadf80c52d56cadb23e11d7d9c25365cc701f434e81c63460e0dc30292d371292a5f8b47a7c93f9ca9176cdfbe6811cad0281547c67904816ba31e785af2d0e8f52fa3c04f5f949997145ba05f683d508e40ee871041a6df73a2f5a927248947b33d0143a2bbc99ba3509376566f55ed09c3726e4f1b5bbb30de48e2c23b19e31ce830aea3a5750956f8eac803e9e5ca66a20ed7586c147ef8c5dacc2501dbcc50b0b7fc4ce6166d96a167d9ec8e7efbcd14a6cb21ed088d48230059942b95e883260d01cec5430921b93df1f0ed904905aedefe6d4cbda37f5ecbde51b17271412d6936aa7c05637c225da9dd3a1e93f59f22047eb2e92539cfe453bbcd51f25db358b94042f0b19c425b9cdf1fc8fa123f5ef0224066ad80ef2013bc9d3b3ea756f03f739e82f0be3151c78ee6407e8ec937a7a80d3fb5d815482e5bf188901a97f5b608fe7c59ca8b7c67d38e469aa0e662b519a4d19191a465a2c0864b2ab2c26ba7ebd489e9c22b191b53dfdacafecbc1dce2f84ea950654e2c2fb13c141336ed13fe7dd9b68fa728f8b7ce431c66f10c68cb4fe6f3af803dd1e7b75618f0bd007556883ba13135b734c0452e586bcb18b2bf41e252ce09902c147e811af192a5272024d53429626447db0b23fb948d0cb0862691e972335a3098791a1, encryptedEndpoint https://v4.provider.mumbai.oceanprotocol.com/api/services/encrypt
>>> asset.did
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'did'
>>> type(asset)
<class 'NoneType'>
```

**Expected behavior**
ocean.assets.create() returns an Asset class object.

**Desktop (please complete the following information):**
- Ubuntu Linux 20.04.1 on VMWare Workstation
- ocean-lib 1.6.1

**Comment by calina-c** [comment]
I managed to fix this by prolonging the waiting time for Aquarius. Should I implement this as a solution? It just seems like Aqua is slower to pickup the asset.

**Comment by MBadea17** [comment]
Yes.

**Comment by trentmc** [comment]
> I managed to fix this by prolonging the waiting time for Aquarius. Should I implement this as a solution? It just seems like Aqua is slower to pickup the asset.

There are two possible solutions for this issue:
1. Wait longer, like got suggest.
2. In create(), use the optional argument to bypass waiting for Aquarius. It's not the default, because users need to know they might not get the full ddo. I added this recently to bypass long wait times.

I defer you you @calinCali to which is the best solution for this issue.

**Comment by calina-c** [comment]
I think for the purposes of the readme, waiting longer is ok. Either way we get all the prints from the brownie transaction, so the user will not just sit idly by waiting, they will see intermediary progress.

**Comment by trentmc** [comment]
> I think for the purposes of the readme, waiting longer is ok. Either way we get all the prints from the brownie transaction, so the user will not just sit idly by waiting, they will see intermediary progress.

I didn't realize that this was in the readme.

In that case, since we have control over it, we don't need to wait, and waiting hurts ux (minutes if waiting)....

Then I definitely recommend option 2, where we don't wait.

**Comment by calina-c** [comment]
I'm worried doing both will compromise our clarity in the readmes. There are multiple options of how we can handle this.

- add a parameter for aquarius waiting to the config dictionary, in order to have a single entrypoint to this logic
- add a parameter to the create function that determine what is returned, e.g. aqua_waiting = (time in seconds, where 0 means we return the did instead)

However, all these actions must be documented. The ocean.assets.create helper is used throughout the readmes and code, and we'd have to add explanations everywhere. For me as a user, I would be confused about why I was expecting an Asset object that I want to use, but I get a did instead, and then, in order to use it, I have to pick it up from Aquarius again, myself. How can we phrase/document/construct this in a way that makes sense?

**Comment by trentmc** [comment]
Independent of this issue - and like we've discussed verbally - we need to refactor ocean_assets.py. It may be better (more OO)to push higher level create() functionality into data_nft_factory.py. Hopefully we can do that in the next couple weeks, as part of pre-release

Fyi there are other readmes that already use "wait_for_aqua=True". Why? Avoids timeout issues and avoids long user wait times / helps ux. 

Then, we can be tactical for this issue. I recommend as above: do both option 1 (because general fix) and option 2 (other readmes already do it, avoids long user wait times / helps ux).

**Comment by trentmc** [comment]
> we need to refactor ocean_assets.py. It may be better (more OO)to push higher level create() functionality into data_nft_factory.py. Hopefully we can do that in the next couple weeks, as part of pre-release

I added this to #910 "UX Tweaks for READMEs, round two", which I plan to work on in coming weeks. 

Given that it will be soon enough, it's ok if you just do option 1 for this issue.
