### ISSUE TITLE
ocean.pool.create() does not work within a .py file but works within the Python shell. (+ a weird thing that makes it work within .py files)

### ISSUE THREAD

**Issue by surajsjain** [oceanprotocol/ocean.py#106]
I tried `pool = ocean.pool.create(token_address, data_token_amount=100.0, OCEAN_amount=10.0, from_wallet=alice_wallet)` from the marketplace flow documentation within the python shell and it worked just fine. But when I put it in a **.py** file along with other code, it threw the following error:
```
Traceback (most recent call last):
  File "weird.py", line 76, in <module>
    pool = ocean.pool.create(
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/ocean/ocean_pool.py", line 69, in create
    pool_address = bfactory.newBPool(from_wallet)
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/models/bfactory.py", line 16, in newBPool
    tx_id = self.send_transaction(
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_base.py", line 196, in send_transaction
    return contract_function.transact(_transact).hex()
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/web3_internal/web3_overrides/contract.py", line 61, in transact
    return transact_with_contract_function(
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/web3_internal/web3_overrides/contract.py", line 110, in transact_with_contract_function
    txn_hash = web3.eth.sendRawTransaction(raw_tx)
  File "path_to_virtual_env/lib/python3.8/site-packages/web3/eth.py", line 272, in sendRawTransaction
    return self.web3.manager.request_blocking(
  File "path_to_virtual_env/lib/python3.8/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
```

So, just out of curiosity, I tried the following within the **.py** file:
```
while(True):
        try:
            pool = ocean.pool.create(token_address, data_token_amount=100.0, OCEAN_amount=10.0, from_wallet=alice_wallet)
            break
        except:
            continue
```
I just told it to keep on trying until it gets it and not throw an error. Surprisingly, **this worked!!**

Is this something normal? Am I missing something (like, am I doing something in a way it's not usually done)? I just copy-pasted everything that was in the marketplace flow documentation. So, if there's something that's missing before `ocean.pool.create()` can you please update it in the documentation?

**Comment by surajsjain** [comment]
Update: now, the while loop with the try-except isn't working either

**Comment by trentmc** [comment]
They're supposed to behave the same. Perhaps compare the values in ocean.config for each? Maybe some envvar didn't get set for the file based approach.

I'll aim to reproduce this tomorrow.

**Comment by surajsjain** [comment]
I copy-pasted the arguments passed to ocean.pool.create from the Python shell to the .py file, but it does not run in the .py file without the while loop and the try-except blocks. The environment variables were the same for both the .py file as well as the python shell. I also cross-verified the envvars with the marketplace flow in the docs. But the .py file still throws the same underpriced error and stops at ocean.pool.create() in the .py file if I don't use the try-except thing with the while loop. Even I was a bit surprised the first time when they were not behaving the same, but then just out of curiosity, I put up the while loop and it worked.

**Comment by trentmc** [comment]
Good afternoon! 

> The environment variables were the same for both the .py file as well as the python shell.

Thanks for the report. It might still be that some non-envvar config is an issue. But before that, here's another possibility:

It can take a while for the Eth tx to go through. And, it can take a while for Aquarius to updated info. 

This would be consistent with the issue that you saw, and the workaround you had.

As a specific thing to try: what if you did a pause(), for say 20 s, right before the call to ocean.pool.create()?

**Comment by surajsjain** [comment]
I used `time.sleep()` to pause the flow of execution for 30 seconds and it worked. I have created a [pull request](https://github.com/oceanprotocol/ocean.py/pull/107) for the documentation to have the same.
