### ISSUE TITLE
To discuss: Remove currency functions

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#1062]
Per @trentmc we need to assess the need for all the currency functions we have lying around in Ocean.py. After the brownie refactoring, eth transfers take in a string representing the amount, i.e. "1 ether", "0.4 ether" etc., where we tried to leverage the options brownie gave us, instead of reinventing the wheel.

This made us realize we could maybe remove some or all of the currency adjustments/handling in ocean.py. Let's discuss and implement this if needed.

**Comment by trentmc** [comment]
👍👍 to remove all of the extra code in ocean.py for currency handling
