### ISSUE TITLE
Have separate README to install Ocean, with better OS support

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1081]
**Is your feature request related to a problem? Please describe.**

In a [recent PR for eth-predict](https://github.com/oceanprotocol/predict-eth/pull/45), @juanpablovs pointed out the different needs of different OSes when installing Ocean. And that PR actually implemented the changes.

Yet ocean.py doesn't have those. They would help a lot for certain OSes. 

(What ocean.py currently has: part of "setup" section in its data-nfts readme. It also still has stuff on coincurve, which I believe post-brownie is out of date.)

**Describe the solution you'd like**

Basically, move "installation" content from eth-predict to a dedicated readme in ocean.py.

- [ ] Create a new README, e.g. `READMES/install.md`
- [ ] Copy "installation" content from eth-predict main2.md's "setup" to the new install.md README. ([Here's the version from JP's PR](https://github.com/oceanprotocol/predict-eth/blob/090f82cabb944d9d6c88c681de2f01c0d7a44a82/challenges/main2.md#1-setup).)
- [ ] In ocean.py data-nfts readme, subsection on "installation": make it point to the new install.md README. 
- [ ] In eth-predict repo, main2.md readme: remove all its content and also point to the new install.md README.

**Comment by mariacarmina** [comment]
I have a question regarding second step. The installation from eth-predict main2.md is a bit different from what ocean.py requires. In ocean.py, Windows is not mentioned in the supported OS from data-nfts README and there are different packages to install, different from ocean.py requirements. 
Q1: For ocean.py should we move content from data-nfts README setup part into `install.md`?
Q2: Should we update also `developers.md` to point to `install.md` at the installation part?

**Comment by trentmc** [comment]
> Windows is not mentioned in the supported OS from data-nfts README and there are different packages to install, different from ocean.py requirements.

Traditionally, ocean.py has not explicitly supported Windows. But someone (JP?) has shown stats that a high % of data scientists use Windows. So if we have a clean way to support Windows, we should. And now JP has found a way to do that - and implemented it in the predict-eth README installation instructions. He also has a good testing flow.

Given that we (a) want Windows support if feasible to do (b) JP has shown a feasible way to do it, then I advocate that we update the spec of ocean.py to explicitly support Windows. 

And therefore the main thing to do update ocean.py's READMEs to have setup to account for Windows. And that's the purpose of this issue. (While minimizing DRY violations.)

**Comment by mariacarmina** [comment]
The commands should work for all the OSs if python is installed, the only thing that differs is how you write the paths. The rest of dependencies that need to be installed, will be installed through `pip`.

**Comment by trentmc** [comment]
> The commands should work for all the OSs if python is installed, the only thing that differs is how you write the paths. The rest of dependencies that need to be installed, will be installed through `pip`.

To be precise, there are a couple other things to handle too. But JP's code (that you used) handles this, so all good.
