### ISSUE TITLE
Ocean.py:  Dynamic provider endpoints

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#110]
Blocked by https://github.com/oceanprotocol/provider/issues/36

Right now all endpoints are hardcoded (https://github.com/oceanprotocol/ocean.py/blob/master/ocean_lib/data_provider/data_service_provider.py#L372)

Ocean.py should read the provider root endpoint (/ ) and create the required URLs based on that information.
Also errors are going to be thrown if a service that is not exposed is being accessed.

**Comment by trentmc** [comment]
The branch "issue110" is still in the codebase. I believe it can be deleted? @mariacarmina
