### ISSUE TITLE
In C2D README, show how to submit an algorithm for use by C2D *including docker container*

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1108]
While the README shows how to submit a url to the algorithm, it says basically nothing about docker containers. Yet under the hood it uses a pre-prepared docker image for gpr.py. 

This means that if someone wants to use any other algorithm than gpr.py, they will need to prepare their own docker image, yet we don't provide any guidance on how to do so. This is a super-high point of friction and needs to be resolved. Fixing this is the aim of this issue.

Related: [predict-eth#40](https://github.com/oceanprotocol/predict-eth/issues/40) needs this issue done.

**Comment by calina-c** [comment]
@trentmc In my opinion, this should be in the main documentation, not ocean.py readmes. We are showcasing things you can do with ocean.py. The part where people create and publish a custom docker image seems remotely related. We can do it, but I'm not a huge fan of it.

**Comment by trentmc** [comment]
> @trentmc In my opinion, this should be in the main documentation, not ocean.py readmes. We are showcasing things you can do with ocean.py. 

Main documentation on C2D is way too thick and heavy for users to get going with. C2D readme is perfect. It'll likely be a pretty common case where the user needs to go beyond the default docker container. Good news: Jaime's PR (promises to) accomplish this goal cleanly.

**Comment by calina-c** [comment]
Here in https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md#appendix-tips--tricks it seems like this is covered. Can we close this issue? @AnaLoznianu @trentmc do you think I should add something more?

**Comment by trentmc** [comment]
Yep, I believe it's done. Closing. @jfdelgad please re-open if you believe otherwise.
