### ISSUE TITLE
Fifty "Event log does not contain..." warnings makes up 80% of output from tests, hurting debugging

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1127]
### The issue

In [this example CI run](https://github.com/oceanprotocol/ocean.py/actions/runs/3569449956/jobs/5999424849): there is one error, but I have to scroll past 50 warnings to get there. I find myself scrolling and scrolling and scrolling all the time, just to find the error.

This happens for all CI runs, and local unittest runs too. 

It's the same warning repeated "Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed". It's expanded on below.

### To fix

Do one of the following. (1) is preferred, (2) is next best, (3) only if we really need. 
1. fix the issue that's causing the warning itself, so that no warnings show up (best approach, if possible)
2. find a way to suppress this specific warning ("Event log does not contain..."), without suppressing other warnings (next best)
3. suppress all warnings by default in CI and locally, but make it possible to turn them on with a special switch (only if needed).

### Expended log

Here's a larger snippet of the warnings.

```text
ocean_lib/aquarius/test/test_aquarius.py::test_aqua_functions_for_single_ddo
  /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x1D5CEbD46Eb0a12013DbE1A66733AD39d410F061: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")

ocean_lib/assets/test/test_asset_downloader.py::test_ocean_assets_download_destination_file
  /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x3DFeAd655056B0E82F2c5EDAC47043c00E409c28: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")

ocean_lib/data_provider/test/test_data_service_provider.py::test_fileinfo
  /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xcf293068b28f99622FFE50C9C6f3e7046Ecda8d9: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")

<<repeated 50 times, for different modules>>
```

**Comment by calina-c** [comment]
@trentmc I investigated this. Here is what I found:
- it happens when we perform receipt.events["NFTCreated"]. I don't think it happens in other cases, just for this event
- the warning is sent via brownie itself, using the warnings module. I'm not sure how to disable/deactivate this part since it's 3rd party

will keep investigating
