### ISSUE TITLE
ocean.py build fails on python 3.11 (all), python 3.10 (Mac)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1158]
From @alexcos20 [in slack](https://oceanprotocol.slack.com/archives/CNDG1849Z/p1670323726860589)

Ocean.py build:
- fails with python 3.11  (but seems to be fine with 3.10 and 3.8)  on Linux and Windows
- fails with python 3.11,3.10  (but seems to be fine with 3.8)  on macOs

PR with the CIs that show failures: https://github.com/oceanprotocol/ocean.py/pull/1157

See https://en.wikipedia.org/wiki/History_of_Python -> Table of versions

Related issue: [ocean.py#1159](https://github.com/oceanprotocol/ocean.py/issues/1159) "Expand CI to more OSes & Py versions"

**Comment by AnaLoznianu** [comment]
This was one of my problems when testing the eth-predict readme. I was using python 3.10.8

**Comment by AnaLoznianu** [comment]
Split this issue in two: 
- here we will tackle the bug with 3.10 version on the macOS operating system
- adding support for 3.11 is a feature we will do in: https://github.com/oceanprotocol/ocean.py/issues/1197

**Comment by trentmc** [comment]
> Split this issue in two:
> 
> * here we will tackle the bug with 3.10 version on the macOS operating system
> * adding support for 3.11 is a feature we will do in: [Add ocean.py support for python 3.11 #1197](https://github.com/oceanprotocol/ocean.py/issues/1197)

FYI #1197 is duplicate with #1159. 1159 is also more thorough. So I closed the newer issue.
