### ISSUE TITLE
ocean.py: datatoken.verify_order_tx: should allow access if the sender is either the consumer or the payer of an order

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#116]
Provider is using this function to check the access rights

Order event definition:  https://github.com/oceanprotocol/contracts/blob/master/contracts/templates/DataTokenTemplate.sol#L33

**Comment by trentmc** [comment]
The branch "issue116" is still in the codebase. I believe it can be deleted? 

I'll re-open this issue until the branch is deleted (or otherwise appropriate action)

@mariacarmina
