### ISSUE TITLE
ocean_assets.py::download_file() error, because allowedSwapper is nonzero

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1161]
### Summary

Steps to solve this issue, while keeping ocean.py code clean & maintainable:

- [x] First, deprecate OceanAssets::download_file(). It does too many things at once. [PR](https://github.com/oceanprotocol/ocean.py/pull/1215), [Commit](https://github.com/oceanprotocol/ocean.py/commit/b43b7b704f70d3eb7a4901d6e1774e4491689469)
- [ ] Then, for template 2 datatoken, simplify interface to "dispense and order" (and for "buy and order"). [PR 1](https://github.com/oceanprotocol/ocean.py/pull/1214), PR 2 TBD.
- [ ] Finally, for template 1 datatoken, create an method for "dispense and order" (and for "buy and order") with the same interface as template 2. Under the hood, it does the steps separately. Then, maybe revise READMEs to show this. 

### Background & motivation

Traceback shared by Alex:
```text
Hi, new here and getting just started using Ocean Protocol. Taking a stab at the Storage Network Data Challenge. I have set up the entire environment and sucessfully connected to a Polygon Mainnet Wallet containing sufficient MATIC. print(accounts.at(challenge_wallet.address).balance()) in python console shows me the correct MATIC amount so I tend to think everything is fine to start downloading stuff from the Ocean Market. However, when I try to do that for the data sets in the Challenge I get an error.  Any pointers what could be the issue?  Command I tried is: filecoin_price = ocean.assets.download_file("did:op:d2f9630759d2fad32d1765a5e9a380b77e674a9561d107a062bd47a66b70f4bc",challenge_wallet)
Resolve did...
Dispense access token...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ronald/ocean/challenges/StorageNetworkDataChallenge/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/ronald/ocean/challenges/StorageNetworkDataChallenge/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean_assets.py", line 709, in download_file
    raise ValueError("Not allowed. allowedSwapper={allowedSwapper}")
ValueError: Not allowed. allowedSwapper={allowedSwapper}
```

@alexcos20 's Q: does ocean.py 2.0.0a4 knows how to handle different templates ? 

Here's the code inside [ocean_assets.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/ocean/ocean_assets.py)::download_file():
```python
            # catch key failure modes
            st = dispenser.status(datatoken.address)
            active, allowedSwapper = st[0], st[6]
            if not active:
                raise ValueError("No active dispenser for datatoken")
            if allowedSwapper not in [ZERO_ADDRESS, wallet.address]:
                raise ValueError("Not allowed. allowedSwapper={allowedSwapper}")
```

Trent notes: 
- yesterday, @calina-c just merged into main a large change to ocean_assets.py. Commit: https://github.com/oceanprotocol/ocean.py/commit/8f6a530cd62f9118a72c3dca578840b8f07164fb. However that change likely didn't affect `download_file()`
- there's a small bug in the ValueError call: it's missing the "f" at the front of the f-string. 
- the main issue: allowedSwapper is almost certainly nonzero, which means only pre-allowed addresses can grab it. Therefore the user can't grab it. 
- This is default behavior for enterprise template. And imo, weird behavior, because people think they're publishing a free asset, yet no one can actually download it (because they need to be whitelisted). We had this before - see [market#1725](https://github.com/oceanprotocol/market/issues/1725) - opened on Oct 4, closed Nov 15

We need to do three things to fix this: 
1. tactical fix for the user, now
2. definitive fix in market, so that when assets are published as "free" in Ocean Market, anyone can dispense() them
3. workaround fix in ocean.py `download_file()`, enable download of assets that are {"free", "enterprise template", allowed_swapper != ZERO}. See "summary" at the top of this issue, and below

### Details For (1): tactical fix for the user, now
Here's the fix for the user: whoever is the owner of that asset, needs to set allowedSwapper to 0x000...000, via a call to [`Dispenser.sol::setAllowedSwapper()`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L205). It could be via etherscan, ocean.js, or ocean.py. Here's the key line for ocean.py

Example in python
```python
private_key = <set as needed>
config = <set as needed>
datatoken_address = <set as needed>

import os
from ocean_lib.web3_internal.constants import ZERO_ADDRESS
from ocean_lib.ocean.ocean import Ocean
from brownie.network import accounts

accounts.clear()
your_wallet = accounts.add(private_key)
ocean = Ocean(config)

# main work
ocean.dispenser.setAllowedSwapper(datatoken_address, ZERO_ADDRESS, {"from" : your_wallet})
```
        
### Details for (2): definitive fix in market

Goal: so that when assets are published as "free" in Ocean Market, anyone can dispense() them

Like mentioned, we had this issue before - see [market#1725](https://github.com/oceanprotocol/market/issues/1725) - opened on Oct 4, closed Nov 15.

But it seems like it's not fixed, given the behavior above.

[Here's the PR](https://github.com/oceanprotocol/market/pull/1728) that aimed to fix it. 

To recap: the issue in Ocean Market is: when publishing a free asset, in Ocean Market, people think that assume that anyone can actually download it. Yet dispense() doesn't work -- not only in ocean.py, but also anywhere else that people would try, like etherscan or web3.js.

Did the PR actually fix it? Investigating, the answer is no. https://github.com/oceanprotocol/market/blob/0ccd375738d3f51d23a66f9e0576a0f3b412a6fd/app.config.js#L21

Towards solving, [market#1725](https://github.com/oceanprotocol/market/issues/1725) has been re-opened.

### Details for (3): definitive fix in ocean.py

Note: the "summary" at the top of this issue is for (3).

Goal: enable download of assets that are {"free", "enterprise template", allowed_swapper != ZERO}

Note that ocean_assets::download_file() _did_ work for _both_ templates, exactly as expected.
- it uses dispenser functionality, which has the same interface for both templates
- if the dispenser is set to let anyone call dispense (allowed_swapper = ZERO), then download_file() does its thing
  - so: if a datatoken with template = 1 _or_ template = 2 (enterprise) has allowed_swapper = 0, then it does its thing
- if the dispenser is set to _not_ let anyone call (allowed_swapper != ZERO) then it complains.
  - so: if a datatoken with template = 1 _or_ template = 2 (enterprise) has allowed_swapper != 0, it complains
- which is exactly what it did! A template = 2 had allowed_swapper != ZERO, so it complained! 

So how does it relate to the issue at hand? 
ocean_assets::download_file() already works for {"free", "enterprise template", allowed_swapper == ZERO}
but because "enterprise template" weirdly set allowed_swapper != ZERO, even for "free", and that default is not changeable, **we want to find a workaround, so ocean.py can the asset anyway. That is: download in the case of {"free", "enterprise template", allowed_swapper != ZERO}**

A  tool:
- enterprise template has special functionality that combines dispense & order actions:  `Datatoken.sol::dt.buy_from_dispenser_and_order()`
- And it has a quirk: it lets anyone do this action. It doesn't care if allowed_swapper = ZERO or != ZERO.
- (That's weird since that action includes dispensing, and dispense on its own cares about allowed_swapper, like it should.)

But we can use this quirk as a workaround:
- for at least the case of {"free", "enterprise template", _allowed_swapper != ZERO_}
- and maybe for slightly broader cases. It depends on how tight & clean we can make the code.

**Comment by trentmc** [comment]
Marked as high priority (at least to do part 1), because it's blocking users of a current Data Challenge.

**Comment by alexcos20** [comment]
I will fix it in ocean.py

**Comment by calina-c** [comment]
@trentmc after merging the last part of the interface simplification in #1220, we can resume this.
