### ISSUE TITLE
release process is undocumented

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.py#118]
Release process is completely missing. How do tagged releases + GitHub release work? How is the CHANGELOG.md (currently empty) generated? How do builds end up on PyPi?

Note: Follow-up issue is #179 to _simplify_ the release process.

**Comment by trentmc** [comment]
High priority because not having it is big friction for anyone fixing bugs or enhancing ocean.py.

**Comment by trentmc** [comment]
Updates:
 * 5 days ago Samer added the file RELEASE_PROCESS.md
 * today I linked to it from developers.md.

So at least now we have a basic release process! I can turn off the "high" priority label.

> Also note how like 10 required steps are all automated behind one simple command in the above example. If the release process requires more than 3 steps, please automate it

This is what's needed to close the issue.

**Comment by trentmc** [comment]
> This is what's needed to close the issue.

I moved this to a new issue: #179. Therefore we can close _this_ issue.
