### ISSUE TITLE
Do OneDispenser class, similar to OneExchange class

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1181]
### Background / Motivation

Q (Calina): should we have OneDispenser?

A (Trent): For priced data, the recently-added OneExchange helped a lot because it meant we didn't have to pass in exchange_id to each method call. But for dispenser: there can only be one dispenser per datatoken. Therefore if you put dispense() on Datatoken, it is already good. So, the payoff for OneDispenser would be lower.

However, given how clean OneExchange came out -- specifically, having one really nice object to manipulate a specific exchange -- OneDispenser could be the same. Bonus: we'd have symmetry of classes to "get" datatokens, for free and for priced data.

### TODO

- Make OneDispenser in the same pattern as OneExchange

**Comment by calina-c** [comment]
@trentmc regarding this ticket, after adding dispense_and_order as well as other dispenser-related methods on the datatoken class, do you think this is still necessary? I personally changed my mind, I think we don't necessarily need it.

**Comment by trentmc** [comment]
> @trentmc regarding this ticket, after adding dispense_and_order as well as other dispenser-related methods on the datatoken class, do you think this is still necessary? I personally changed my mind, I think we don't necessarily need it.

I thought more about it too.

I agree with you. We don't need it.

And in fact, it will make the DX worse. Right now, we have one simple method on Datatoken to create the dispenser (sole dispenser for that datatoken), and one simple method to dispense. Adding this class will force the user to work with a separate object than datatoken, and it doesn't help.

Given that we're in agreement, I'm closing this issue.
