### ISSUE TITLE
Have *good* documentation, in the style of scikit-learn, web3.py, or eth-brownie

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1184]
### Background / motivation

For a lot of v3 (and early v4?), docs.oceanprotocol.com had a ocean.py "APY reference", for heavier users of ocean.py to know what was available. It was auto-created from the py code. However it wasn't great to use, the auto-creation made it not so smooth to read. So it got deprecated either on V4 release, or soon after (approx Jun 2022).

What do people do now?
- Our *main* source of documentation has been the READMEs. Keeping docs thin, to just that, has allowed us to evolve ocean.py rapidly towards being more useful. And it's worked, well:)
- The secondary source of documentation is for users to look in the ocean.py code itself. Note: with the addition of brownie, some of this got harder; [ocean.py#1165](https://github.com/oceanprotocol/ocean.py/issues/1165) will fix that.

Which means, our status-quo approach of READMEs + code is so-so. It helps use to evolve. But for ocean.py to be used by way more people, docs need to get better.

We're starting to see the light at the end of the tunnel for ocean.py getting stable, clean code, clean interface. Perhaps in 1-3 months it'll be in great shape.

On the heels of that, we'll be in a good position to start to have _good_ documentation. How? we can look to the docs of widely-used AI or Web3 projects: scikit-learn, web3.py, or eth-brownie. The goal of _this_ issue is to build something like that, probably with the help of documentation sw. 

### Pre-requisites

Do these first:

- [#1165](https://github.com/oceanprotocol/ocean.py/issues/1165): put docstrings into each `ocean.py/ocean_lib/model/*.py` module's class. The docstring uses Python notation to describe each Solidity method that the module exposes in Python. 

### TODO for this issue

Update oceanprotocol/docs repo to have docs, with form inspired by scikit-learn etc.

### Resources

To rapidly populate the docs, leverage the following content. From highest-level to finest-grained:
  - main [README.md](https://github.com/oceanprotocol/ocean.py/blob/main/README.md).
  - [main-flow.md README appendices](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/main-flow.md#appendix-publish-details).
  - ocean.py modules themselves, including the recently-added docstrings from # 1165

**Comment by AnaLoznianu** [comment]
@trentmc What do you think of the ocean.py documentation we released last week with the v2 docs? Does it fit with the requirements of this issue?

**Comment by trentmc** [comment]
It's a big improvement. Enough of an improvement to consider this issue closed.
