### ISSUE TITLE
Clean up datatoken.py::create_exchange() workaround for BT_decimals != 18

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1190]
### TODOs

1. [x] Triage: fix datatoken. Done: [PR](https://github.com/oceanprotocol/ocean.py/pull/1200), [commit](https://github.com/oceanprotocol/ocean.py/commit/65f1483a9bfa15dea8a78caa0eb0f1419c380e9a)
2. [ ] Properly fix the tests: (a) test_datatoken_enterprise.py::test_buy_from_fre_and_order, (b) test_exchange_fees.py

### Background / motivation

When working on [ocean_lib/models/test/test_exchange_fees.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/test/test_exchange_fees.py), I found that it would fail unless I gave it the _wrong_ number of decimals for the basetoken. 

Example: USDC has 16 decimals. The test uses USDC and 16 decimals. 
- If in `datatoken.py::create_exchange()`, if I called `self.contract.createFixedRate()` with `BT_decimals = BT.decimals()` (ie value of 16) then the test would fail. It's like it wouldn't register that the fees were gathered
- Yet if I put BT_decimals = 18, the test would pass. So inside `datatoken.py::create_exchange()`, I made the following workaround:

```python
        # test_datatoken_enterprise only passes when BT_decimals == 18,
        # even if BT.decimals() != 18. Accomodate with this workaround:
        if "DatatokenEnterprise" in str(self.__class__):
            BT_decimals = 18
        else:
            BT_decimals = BT.decimals()
```

### Goal of this issue

Obviously, the workaround above is ugly, and shouldn't be there. And maybe it causes more bugs! We need a clean solution. In doing the solution, maybe we'll find other bugs.

### Towards solving

Datapoint: test_exchange_fees.py was previously /tests/flows/test_exchange_swap_fees.py. I found that the old test file also erroneously had 18 decimals.

[`helper_functions.py::convert_bt_amt_to_dt()`](https://github.com/oceanprotocol/ocean.py/blob/4da2ade35660d92b39d75710387f57cceb8c3c87/tests/resources/helper_functions.py#L304) smells a bit off. Below is its code. (Note that I'd inserted in the comment '"`## FIXME: SHOULDN'T 18 BE bt_decimals ??`"

```python
def convert_bt_amt_to_dt(
    bt_amount: int,
    bt_decimals: int,
    dt_per_bt_in_wei: int,
) -> int:
    """Convert base tokens to equivalent datatokens, accounting for differences
    in decimals and exchange rate.
    When creating a pool, the "rate" argument is the datatokens per base token,
    and can be passed directly into this function.
    When creating an exchange, the "rate" argument is the base tokens per datatoken,
    so it needs to be inverted before passing into this function.
    Datatokens always have 18 decimals, even when the base tokens don't.
    """
    unit_value = Decimal(10) ** 18  ## FIXME: SHOULDN'T `18` BE `bt_decimals` ??
    amt_wei = Web3.toWei(
        Decimal(bt_amount) / unit_value * Web3.fromWei(dt_per_bt_in_wei, "ether"),
        "ether",
    )
    return 
```

**Comment by alexcos20** [comment]
```
if "DatatokenEnterprise" in str(self.__class__):
            BT_decimals = 18
        else:
            BT_decimals = BT.decimals()
```

that code could open a immunify bug issue of 100.000 usd :)
First:
 1. there is no relationship between datatoken template and basetoken decimals no
 2. you cannot hardcode bt.decimals=18.  Because if somebody is going to use the enterprise template to create a fixed rate schema with USDC (which has 6 decimals), somebody will loose a lot of money :)

Most likely, in ocean.py, there is something hardcoded, when it shouldn't be.
And please , revert it from main, cause I already see it in main (https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/datatoken.py#L165-L168)

**Comment by trentmc** [comment]
Thanks for the notes @alexcos20 . I will investigate this now, so that we can have both (a) unit tests passing (b) not the risk to users with eg USDC.
