### ISSUE TITLE
Add pricing schema to asset creation

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#1196]
We should allow our users to add a pricing schema when creating an asset via the ocean.py.
This minimizes the number of transactions needed. The creation of the NFT and a pricing schema can be done in 1 transaction onlu

**Comment by AnaLoznianu** [comment]
cc @trentmc @alexcos20 @calina-c

**Comment by trentmc** [comment]
Duplicate with #1192. Closing.

**Comment by AnaLoznianu** [comment]
But it's not a duplicate. This is for attaching a pricing schema to the asset and the other issue is to incorporate publishing via pybundlr on arweave.

**Comment by trentmc** [comment]
> But it's not a duplicate. This is for attaching a pricing schema to the asset and the other issue is to incorporate publishing via pybundlr on arweave. What am I missing?

Whups, I linked to the wrong issie.

The _correct_ issue is https://github.com/oceanprotocol/ocean.py/issues/1166
