### ISSUE TITLE
Add ocean.py support for python 3.11

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#1197]

**Comment by trentmc** [comment]
This issue is duplicate with #1159 "Expand CI to more OSes & Py versions"

**Comment by AnaLoznianu** [comment]
We discussed during our planning to split that in 2. Why?

1. We have a bug with the 3.10 version that we need to fix. 
2. We need to add support for 3.11. That means: adding CI, making sure everything works with the new version, updating readmes and so on.

@calina-c is the one doing both of these issues. So if she prefers to have 2 issues, let's please give her this liberty 🙏

**Comment by trentmc** [comment]
> We discussed during our planning to split that in 2. Why?
> 
> 1. We have a bug with the 3.10 version that we need to fix.
> 2. We need to add support for 3.11. That means: adding CI, making sure everything works with the new version, updating readmes and so on.
> 
> @calina-c is the one doing both of these issues. So if she prefers to have 2 issues, let's please give her this liberty pray

OK, do it how you like. Then perhaps change #1159 so that this issue and #1159 don't overlap?
