### ISSUE TITLE
Install readme requires the same python console to run the code

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#1202]
Feedback from one of our Predict-ETH participants:

"If the steps are run one by one but I exit the console halfway, it seems like I can’t retrieve my minted data token object since it wasn’t saved to disk before I exit. Maybe I could retrieve the python object by querying some API but it isn’t clear to me"

**Comment by AnaLoznianu** [comment]
cc @trentmc

**Comment by trentmc** [comment]
Thanks for cc'ing me, Ana!

The predict-eth README (main2.md) already has the following, right after the datatoken is created:
```python
print(f"New asset created, with did={asset.did}, and datatoken.address={datatoken.address}")
```

So, someone can recover a datatoken object via this code:
```python
config = <like in README>
datatoken_address = <need to print out earlier, then write it down>
from ocean_lib.models import Datatoken
datatoken = Datatoken(config, datatoken_address)
```

Therefore to solve this issue, perhaps add to the README:
"""
To recover your datatoken as an object in the future, here's how.:
...
"""

Thoughts @AnaLoznianu ?

**Comment by AnaLoznianu** [comment]
sounds good :)
