### ISSUE TITLE
Txs to polygon hang. Why: gas price it tried << gas price needed

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1213]
### Background

I'm working with polygon network to grab predict-eth round 2 results. I'm in the step where I'm given a datatoken address, and I need to call `ocean.assets.download_asset()`. Polygon block latency is a few seconds. However it takes me 2-5 min for a tx to go through. 

I observed that the gas price I'm giving (31.9058) is much lower than what polygon matic gas station suggests. That's the problem! (Or at least one of them). Details below.

### TODOs for this issue

Ensure that we pay a more reasonable gas price in Polygon, so that users aren't waiting around. (Without reinventing the wheel. Brownie will likely make this easy, if we're smart about it.)

### Details of my call

This is in `predict-eth-judges` repo.

```text
(venv) trentmc@trentmc-xps:~/code/pej$ pej getpreds outdir-round2/
pej getpreds: Begin
Args: CSV_DIR=outdir-round2/
alice_wallet.address=0xA54ABd42b11B7C97538CAD7C6A2820419ddF703E. bal=9.928745801526913 MATIC
Loaded 2 DT addrs.
DT #1/2: Begin
dt_addr=0xb8187192f79E88eF942E50Ba433B71b6d226D5e1, nft_addr=0x53105b05E5a78B26e70aE6E6169C7e9CDe15b47A, did=did:op:fe8ffa177b719476bef1b8cbfb28b4e8043515817304812f018554afd04d7ef0
INFO:ocean_lib.data_provider.data_service_provider:Service initialized successfully initializeEndpoint https://v4.provider.polygon.oceanprotocol.com/api/services/initialize
Transaction sent: 0x2cf67f1596a71bd47f0e61ec7242a6dd9b2ed09324863c61f4d5b567dc59564a
  Gas price: 31.905822902 gwei   Gas limit: 96654   Nonce: 8
```

The key thing to note here is "Gas price: 31.905822902 gwei".

### Details of gas station

And, doing a call (as of Dec 14, 21:00 UCT) to https://gasstation-mainnet.matic.network/v2 outputs the following: `{"safeLow":{"maxPriorityFee":35.848027238,"maxFee":44.510349484},"standard":{"maxPriorityFee":36.741326008,"maxFee":45.403648254000004},"fast":{"maxPriorityFee":39.64206791064286,"maxFee":48.30439015664286},"estimatedBaseFee":8.662322246,"blockTime":3,"blockNumber":36834265}`

Note that even the lowest of these values is _much_ higher than the gas price that our tx gave.

### Details: my current brownie network-config.yaml

```text
development:
  - name: development
    chainid: 8996
    host: http://127.0.0.1:8545
    id: development
    required_confs: 1
live:
  - name: polygon-test
    networks:
      - chainid: 80001
        host: https://rpc-mumbai.maticvigil.com
        id: polygon-test
        required_confs: 1
  - name: polygon-main
    networks:
      - chainid: 137
        host: https://polygon-rpc.com
        id: polygon-main
        required_confs: 15
```

**Comment by AnaLoznianu** [comment]
We discussed during our refinement: Let's set aggressive gas cost for polygon transactions
