### ISSUE TITLE
Add support for creating arweave assets

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#1223]

**Comment by trentmc** [comment]
If this is about getting [PR#860](https://github.com/oceanprotocol/ocean.py/pull/860) over the line, please hold back. I'm going to discuss with Alex about this today. 

And: there's a bigger picture wrt arweave.

What we _should_ have, from a product perspective:
- publishers should have a low-friction flow to get their file into arweave, and publish as an arweave asset. Via (a) Market (b) ocean.py, and (c) maybe ocean.js. "Low friction" ideally means not needing AR tokens, and minimizing waiting time. (Arweave default block time is 10 min) 
- consumers should have a low-friction flow to consume an arweave file. Via (a) Market (b) ocean.py, and (c) maybe ocean.js.

Ideally this gets built by (i) using best-in-class off-the-shelf components (ii) minimizing extra complexity in Ocean stack.

**Comment by alexcos20** [comment]
Please do not use #860 !!

Should look something like https://github.com/oceanprotocol/ocean.py/pull/912

**Comment by calina-c** [comment]
That's what I had in mind :)

**Comment by trentmc** [comment]
Also as an update from the chat between Alex & me (and Mihai B), for ocean.py itself:

- for step (1a), ocean.py will import [pybundlr](https://github.com/oceanprotocol/pybundlr). Pre-requisite: pybundlr gets lighter dependencies via [pybundlr#7](https://github.com/oceanprotocol/pybundlr/issues/7), I will have Berkay take this over the line in the next couple weeks
- for step (1b), that's what _this_ GH issue is, therefore "Should look something like [#912](https://github.com/oceanprotocol/ocean.py/pull/912)"
- for step (2), it will also fall out of (1b)
- once (1a, 1b, 2) are done, then we can do [#1192](https://github.com/oceanprotocol/ocean.py/issues/1192) "Bundle together (a) store on arweave via pybundlr (b) ocean_assets::create"

**Comment by calina-c** [comment]
@AnaLoznianu @trentmc  seeing how #1192 covers the rest of the aspects and step 1b is merged from #1226, should we close this issue?

**Comment by trentmc** [comment]
> @AnaLoznianu @trentmc seeing how #1192 covers the rest of the aspects and step 1b is merged from #1226, should we close this issue?

OK with me.

I defer to @AnaLoznianu to close the issue, given that she opened it.

**Comment by AnaLoznianu** [comment]
Closed with: https://github.com/oceanprotocol/ocean.py/pull/1226
