### ISSUE TITLE
CI fails: "Exception: Address not found for network_name=development". Barge issue?

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1259]
### The Bug

Example: [this CI log](https://github.com/oceanprotocol/ocean.py/actions/runs/3829882340/jobs/6517062682) from [this PR](https://github.com/oceanprotocol/ocean.py/pull/1256).

Every test fails.

We are also seeing this in df-py CI, reported in [df-py#421](https://github.com/oceanprotocol/df-py/issues/421).

### Example traceback

```
_________________________ ERROR at setup of test_init __________________________

config = {'ADDRESS_FILE': '/home/runner/.ocean/ocean-contracts/artifacts/address.json', 'DOWNLOADS_PATH': 'consume-downloads', 'METADATA_CACHE_URI': 'http://172.15.0.5:5000/', 'NETWORK_NAME': 'development', ...}

    @pytest.fixture
    def ocean_address(config) -> str:
>       return get_address_of_type(config, "Ocean")

conftest_ganache.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/ocean/util.py:20: in get_address_of_type
    addresses = get_contracts_addresses(config_dict)
/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

config = {'ADDRESS_FILE': '/home/runner/.ocean/ocean-contracts/artifacts/address.json', 'DOWNLOADS_PATH': 'consume-downloads', 'METADATA_CACHE_URI': 'http://1[72](https://github.com/oceanprotocol/ocean.py/actions/runs/3829882340/jobs/6517062682#step:7:73).15.0.5:5000', 'NETWORK_NAME': 'development', ...}

    @enforce_types
    def get_contracts_addresses(config: dict) -> Optional[Dict[str, str]]:
        """Get addresses for given NETWORK_NAME, from info in ADDRESS_FILE"""
        network_name = config["NETWORK_NAME"]
        if network_name == "polygon-test":
            network_name = "mumbai"
    
        if network_name == "polygon-main":
            network_name = "polygon"
        addresses = get_contracts_addresses_all_networks(config)
    
        network_addresses = [val for key, val in addresses.items() if key == network_name]
    
        if not network_addresses:
            address_file = config.get("ADDRESS_FILE")
>           raise Exception(
                f"Address not found for network_name={network_name}."
                f" Please check your address_file={address_file}."
            )
E           Exception: Address not found for network_name=development. Please check your address_file=/home/runner/.ocean/ocean-contracts/artifacts/address.json.

ocean_lib/web3_internal/contract_utils.py:67: Exception
```

**Comment by calina-c** [comment]
It seems it works in the morning and fails in the afternoon intermitently. I suspect some issues with loading on Github Action servers or something similar. I did increase the waiting time, but will keep observing this.

**Comment by AnaLoznianu** [comment]
One idea to debug this is to display the contents of the addresses.json as a step on the github actions. In this way, we will find out if the development object is available.

**Comment by calina-c** [comment]
> One idea to debug this is to display the contents of the addresses.json as a step on the github actions. In this way, we will find out if the development object is available.

We already integrated this and it does seem like the developjment entry does not exist.

**Comment by calina-c** [comment]
Adding a Github Action run for reference https://github.com/oceanprotocol/ocean.py/actions/runs/4053397106/jobs/6973966513

**Comment by calina-c** [comment]
And it happens on Aquarius, too. Here is a dependabot-triggered action that updates pylint (absolutely no change to any functionality): https://github.com/oceanprotocol/aquarius/actions/runs/4219656434/jobs/7325231234

**Comment by calina-c** [comment]
Closed by https://github.com/oceanprotocol/ocean.py/pull/1342

**Comment by calina-c** [comment]
Update: It only happened during dependabot PRs last week. It could have been a fluke. I'll keep this open until next week's dependabot PRs to make sure it doesn't happen again. I'll close it if not reproducible.

**Comment by trentmc** [comment]
Closing, this is old. Will open new issue if it reappears
