### ISSUE TITLE
Update setup-remote.md to include specific commands and file locations for Windows OS

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1285]
In setup-remote.md, chapters [1.1 - Configuration File](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-remote.md#11-configuration-file) and 1[.3 - RPCs and Infura](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-remote.md#13-rpcs-and-infura) include commands and file locations specific only to Linux and MacOS. 
Add the corresponding commands and file locations for Windows OS. 
For instance, on Windows, the file network-config.yaml is located in <virtual_environment_directory>\Lib\site-packages\brownie\data.

**Comment by calina-c** [comment]
@mariacarmina maybe you can advise here.
I think we are copying the network-config file to the home folder or rely on a previously installed brownie, making the path ~/.brownie/network-config.yaml
However the network-config in the home folder is NOT the one from the venv directory. Does Windows add a network-config.yaml in another place, somewhere OS-specific? Because the path provided from venv is most certainly not the one we're interested in.

**Comment by MBadea17** [comment]
I did some tests and the location of the network-config.yaml file on Windows is on C:\Users\<user_name>\.brownie. 

The same procedure applies to Windows as to Linux OS: in order to create the C:\Users\<user_name>\.brownie, first you have to run a eth-brownie function from the python console.

**Comment by mariacarmina** [comment]
> @mariacarmina maybe you can advise here. I think we are copying the network-config file to the home folder or rely on a previously installed brownie, making the path ~/.brownie/network-config.yaml However the network-config in the home folder is NOT the one from the venv directory. Does Windows add a network-config.yaml in another place, somewhere OS-specific? Because the path provided from venv is most certainly not the one we're interested in.

We do not use the path from venv and we rely on the network-config file to the home folder, without copying. We should integrate the commands for Windows as well in the `install.md`.

**Comment by AnaLoznianu** [comment]
https://github.com/oceanprotocol/ocean.py/pull/1322
