### ISSUE TITLE
Retry mechanism enhancements

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#1289]
This issue was created as a follow-up on #1288 where we discussed how to improve the code quality & readability.
The following list contains problems that we noticed such as:

- [ ] assert `TypeError` message

- [ ] use `tx.wait(1)` to avoid `invalid operand` error

- [ ] #1291
(*first approach*: encapsulating the arguments in `args` as well)

**Comment by MBadea17** [comment]
Closed as obsolete.
