### ISSUE TITLE
Expose gas strategy util function for polygon network in the README

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#1326]
In [our code](https://github.com/oceanprotocol/ocean.py/blob/main/tests/integration/remote/util.py#L45), we have an util function that retrieves the fees for polygon network and I think that we can mention it in the `setup-remote` README for more visibility for users, especially for ETH-Predict challenge. 
Another approach would be to create another function to include other networks as well, not only Polygon related ones.

**Comment by calina-c** [comment]
I would suggest a separate readme for different gas tweaks we've learned.

**Comment by mariacarmina** [comment]
I agree with this approach.
