### ISSUE TITLE
CI test fails: test_script_execution, fails on "assert 'error' not in response"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1331]
### Background / motivation

I just did a tiny change to main that should not break things, [here](https://github.com/oceanprotocol/ocean.py/commit/0d7c3c56dae8906e4e065c85ccf35f0edeccd5c7). (One-character change to fix a typo in a README.)

Yet remote CI failed. [Here's the log.](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426)

The main traceback:
```text
_______________ ERROR at setup of test_script_execution[script0] _______________

config = {'ADDRESS_FILE': '/home/runner/.ocean/ocean-contracts/artifacts/address.json', 'DOWNLOADS_PATH': 'consume-downloads', 'METADATA_CACHE_URI': 'http://1[72](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426#step:8:73).15.0.5:5000', 'NETWORK_NAME': 'development', ...}
ocean_address = '0x24[73](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426#step:8:74)f4F7bf40ed9310838edFCA6262C17A59DF64'

    @pytest.fixture
    def ocean_token(config, ocean_address) -> Datatoken:
>       connect_to_network("development")

conftest_ganache.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/web3_internal/utils.py:66: in connect_to_network
    network.disconnect()
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/main.py:65: in disconnect
    if not is_connected():
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/main.py:[84](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426#step:8:85): in is_connected
    return web3.isConnected()
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/web3.py:117: in isConnected
    return super().isConnected()
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/main.py:343: in isConnected
    return self.provider.isConnected()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <web3.providers.rpc.HTTPProvider object at 0x7f14fea[94](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426#step:8:95)cd0>

    def isConnected(self) -> bool:
        try:
            response = self.make_request(RPCEndpoint('web3_clientVersion'), [])
        except IOError:
            return False
    
        assert response['jsonrpc'] == '2.0'
>       assert 'error' not in response
E       AssertionError: assert 'error' not in {'error': {'code': -32601, 'message': 'the method web3_clientVersion does not exist/is not available'}, 'id': 25, 'jsonrpc': '2.0'}

/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/providers/base.py:[108](https://github.com/oceanprotocol/ocean.py/actions/runs/4192761417/jobs/7268766426#step:8:109): AssertionError
=
```

**Comment by calina-c** [comment]
Seems to be internal to web3 and happens rarely. I've seen it a couple of times but I don't think there's anything we can do except one of those retry/wait mechanisms, which would only clutter the ocean.py logic for the sake of an intermittent and rare CI-only issue. I propose we close this.

Somehow similar: https://github.com/oceanprotocol/provider/issues/606 which also causes intermittent failures in ocean.py. Should I open an issue here for that as well?

CC: @trentmc

**Comment by trentmc** [comment]
ocean (including ocean.py, largely because of components it uses) is still fairly unreliable. E.g. it's caused enough problems to predict-eth competitors that just 7 of 25 of them submitted using the target flow. (And there may be many more that simply didn't submit because it didn't work).

We should take efforts to improve reliability when using ocean.py.

>  an intermittent and rare CI-only issue

Is it? Perhaps it's elsewhere too, it's simply only CI that is "definitively" catching this? (Searching for lost wallet under streetlamps)

> `>       connect_to_network("development")`
Does it only happen in `connect_to_network()` on barge? Or does it happen in other functions, or other networks?

If it's just connect_to_network, we can keep the retry logic in one place. And ideally it's just a couple lines. I _do_ lean to doing this, for the reliability reason given above. (If it looks like way more lines / complexity, let's re-discuss.)

> Somehow similar: oceanprotocol/provider#606 which also causes intermittent failures in ocean.py. Should I open an issue here for that as well?

Yes, ocean.py should be resilient to this, eg via a retry. (If it looks like way more lines / complexity, let's re-discuss.)

**Comment by trentmc** [comment]
Closing, this is old. Will open new issue if it reappears
