### ISSUE TITLE
Ocean-lib may not work when using a version of Python installed on the machine via Anaconda

### ISSUE THREAD

**Issue by graceful-coder** [oceanprotocol/ocean.py#1352]
**Describe the bug**
Cannot import connect_to_network module when following the setup-local.md instructions on Mac M1. 

**To Reproduce**
[1. Go to setup-local.md README
](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-local.md)2. Follow the steps 1-4 on a Mac or Windows
3. See error on 4th step

**Expected behavior**
No python errors when setting up Alice and Bob in python with ETH and OCEAN.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 
 **Screenshots**
![bug](https://user-images.githubusercontent.com/101472818/222620655-ae99dc77-bf2a-409c-b6af-ba6d2edd8fc0.png)

**Additional context**

**Comment by graceful-coder** [comment]
@mariacarmina @calina-c Tagging you here because I do not have the permissions yet to assign this issue directly to you.

**Comment by mariacarmina** [comment]
I don't think is due to ocean-lib and it seems to come from your python setup. I have searched the problem a bit and found an answer [here](https://stackoverflow.com/questions/55277328/unable-to-solve-importerror-dynamic-module-does-not-define-module-export-funct). It seems that mixes Python 2 with Python 3.

**Comment by graceful-coder** [comment]
As a user, I shouldn't have to update my main_wrapper.c file on my machine to run ocean-lib properly. [Here](https://drive.google.com/drive/folders/1HDyu1F0poBJV3jCsK9rB8kw2KDRi0WCf?usp=sharing) is a screen recording to show my installation process from the readmes and the import failure.

**Comment by mariacarmina** [comment]
There is a problem related on how did you manage to install python on your machine. It's a Python version issue that you have encountered, not an ocean-lib issue.

**Comment by graceful-coder** [comment]
So what you're saying is that I can't run Ocean-lib with Python 3.9.12 as installed by Anaconda?

**Comment by mariacarmina** [comment]
Anaconda is not yet fully supported, check in install.md https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/install.md#install-oceanpy-library. The comment right above `python3 -m venv venv`. So if the python is installed by Anaconda, maybe that's why you are facing these issues.

**Comment by graceful-coder** [comment]
It shouldn't be a problem with Python 3.9.12 being installed by Anaconda... That comment refers to not being able to use a conda virtual environment. Either way, I will go through uninstalling python entirely on my system and install an old version of python to try to get this working. Will report back.

**Comment by graceful-coder** [comment]
Resolved by installing Python 3.10.4.

Takeaway: Cannot use either conda virtual environment, nor even a Python install by Anaconda with ocean-lib.

**Comment by ChristianCasazza** [comment]
I got the following import error message after setting up my virtual enviornment and installing ocean-lib. I am using Windows.  


 ImportError: cannot import name 'Accounts' from partially initialized module 'brownie.network.account' (most likely due to a circular import) (C:\Users\Chris\oceanpy\venv\lib\site-packages\brownie\network\account.py)

**Comment by mariacarmina** [comment]
@calina-c has a PR on anaconda project and this issue seems related to #1203. I'll also assign @calina-c on this one as well.

**Comment by calina-c** [comment]
Closing as discussed on Slack with Christian.
