### ISSUE TITLE
Binance API does not work when downloading in publish-flow-restapi.md

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#1375]
After publishing the rest API asset on mumbai, file info couldn't be fetched from provider and it crashes at the download part (in Ocean Market and also from ocean.py console) https://market.oceanprotocol.com/asset/did:op:c5cc054e0e1eab4a0e4a6669e697c14b27061d0aca6fd4c01f2a767a331b9376. It is due to the URl, because Binance API has some limitations and it's not available anymore in some places.

Created another one based on Kraken API URL and it worked https://market.oceanprotocol.com/asset/did:op:3447dc6a8761ec5b22d55510ff39d734e9f89b61eee1772628e08dc21a0342b5

Update the URL from the README to avoid the errors.

**Comment by calina-c** [comment]
As far as I know, this issue has been encountered before. I remember Trent creating a Binance API readme a few months ago, but we decided to change it due to the same limitations. Am I remembering this correctly, @trentmc? Or was it an entirely different thing?

How should we proceed here? If the link is not "stable" we can not guarantee anything from within the Ocean tools.

**Comment by trentmc** [comment]
Example api url (without start time & end time params): https://api.binance.com/api/v3/klines?symbol=ETHUSDT&interval=1d

Works for me.

Christian reported: it blocks him from usa - "restricted region"

**Comment by mariacarmina** [comment]
Tested with  https://api.binance.com/api/v3/klines?symbol=ETHUSDT&interval=1d and it failed at download again. The URL is accessible and I can publish the asset, but the problem is at the `initialize` part. Maybe these URLs have an encoding that cannot be decrypted by provider.

Error from provider: NoneType :)
```
2023-03-21 16:26:22	
NoneType: None
ERROR Error: Asset URL not found, not available or invalid. Payload was: ImmutableMultiDict([('documentId', 'did:op:577761687ddee26bf0a9ba7260916cb9f293a6f312dbcc5b72fdc98751351476'), ('serviceId', '0'), ('fileIndex', '0'), ('consumerAddress', '0xCa757bFbF46E2de1f171e1eBcc70C15Fc0F28096')])
```

**Comment by mariacarmina** [comment]
UPDATE: Provider is hosted in U.S., so it won't work with Binance API.

**Comment by trentmc** [comment]
We discussed in planning, we all agreed the solution will be:

Switch to using kraken not binance

Other potential solutions:
- move Provider to EU data center
- tell the user: if region problem, run your [REDACTED]
- don't use Provider lol (Template 3)
