### ISSUE TITLE
Allow publishers to use credentials

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#1394]
When helper functions were created (create_url_asset, create_arweave_asset, etc), credentials parameter was not included in the argument list.

Fix:  

- [x] add credentials to helper functions as optional
- [x] have a README
- [ ] link to new README from main README.

**Comment by trentmc** [comment]
Please link to this from the main README, in its ["Tools" section](https://github.com/oceanprotocol/ocean.py#tools). Otherwise there's no real way to discover this.
