### ISSUE TITLE
Proper use of getting fixed rate and dispensers addresses

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#1426]
NEVER hardcode fixedrates, dispensers in your flow like

```fre_address = get_address_of_type(self.config_dict, "FixedPrice")

        # import now, to avoid circular import
        from ocean_lib.models.fixed_rate_exchange import OneExchange

        if not isinstance(exchange, OneExchange):
            exchange = OneExchange(fre_address, exchange)
```
(https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/datatoken2.py#LL44C9-L50C58)

That is why we have templates, so everything can be dynamic..
Always read them from the contract with getFixedRates() or getDispensers()(https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L1050C14-L1052)

**Comment by calina-c** [comment]
I don't understand the problem, exactly. Here, the exchange parameter can be either a string (the address) or the object itself. If it is not the object, we retrieve the object based on the address. Is that not right?
