### ISSUE TITLE
Cannot Find Contract Address

### ISSUE THREAD

**Issue by the0riginalgandalf** [oceanprotocol/ocean.py#144]
**Describe the bug**
Working my way through the getting started tutorial for ocean.py. Followed it exactly but when I run the script I get a  FileNotFoundError. The `get_contracts_addresses` function is what's returning the error.

**To Reproduce**
```
import os
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.wallet import Wallet

NETWORK_URL = os.getenv('NETWORK_URL')
meta_key = os.getenv('meta_key')
config = {'network': os.getenv('NETWORK_URL')}

ocean = Ocean(config)
```

cannot find contract addresses: 
artifacts path is C:\Users\USER\\.ocean\ocean-contracts\artifacts, address file is C:\Users\USER\\.ocean\ocean-contracts\artifacts\address.json
address file exists? False
artifacts path exists? False
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-79d1b8f3e94b> in <module>
----> 1 ocean = Ocean(config)

~\AppData\Roaming\Python\Python39\site-packages\ocean_lib\ocean\ocean.py in __init__(self, config, data_provider)
    105 
    106         network = Web3Helper.get_network_name()
--> 107         addresses = get_contracts_addresses(network, self._config)
    108         self.assets = OceanAssets(
    109             self._config, data_provider, addresses.get(MetadataContract.CONTRACT_NAME)

~\AppData\Roaming\Python\Python39\site-packages\ocean_lib\ocean\util.py in get_contracts_addresses(network, config)
    113         print(
    114             f"contents of artifacts folder: \n"
--> 115             f"{os.listdir(ContractHandler.artifacts_path)}"
    116         )
    117     return addresses or {}

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\USER\\\.ocean\\ocean-contracts\\artifacts'

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Using conda environments. Ocean-lib was pip installed using local environment's pip and being run inside same environment.
 - Error is the same regardless of running inside Jupyter Lab, VS Code, etc.

**Additional context**
Most of my coding experience is AI and pytorch, so this stuff is new to me. Obviously it's looking for some addresses, but I'm unclear how to find what this script is looking for.

**Comment by trentmc** [comment]
Note: #95 should address this, I'm working on it soon

**Comment by trentmc** [comment]
I'm done ocean.py #95 now. However it didn't make changes that would have affected the outcome here. 

But, the learnings from that led to issue [MultiRepo#83](https://github.com/oceanprotocol/multi-repo-issue/issues/83). It points to a brittleness in how artifacts might get imported in some environments. You're running Windows, so there's a good chance that it does things a little differently. I'll be working on this new issue over the next week.
----

Independent of the above, @the0riginalgandalf could you share with me this detail: which specific .md file and specific step you had got through, which led to this? It will help to make sure you solve it well. Thanks!

**Comment by trentmc** [comment]
Update: today we greatly updated the quickstarts for using ocean.py. There's a good chance that your issue will go away. However I won't close this issue until we've done MultiRepo#83.
