### ISSUE TITLE
ocean.py: Only allow code merges if unit test code coverage ratchets up

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#146]
(Prerequisite: #121 made code coverage more visible)

**Is your feature request related to a problem? Please describe.**
We constantly have bug "fixes" where it's just a change to the code, but there are no unit tests. Over time the quality of the sw deteriorates. The excuse is "not enough time" but this is simply untrue because we *do* pay back in spades. Quality comes for free, and then some. So we need to do more tactics to enhance quality. And helping to ratchet up code coverage ratchets up is a good one.

Towards code quality, if we have a constraint where % code coverage must go upwards, it not only prevents code quality from degrading due to missing tests, over time it ratchets the % coverage upwards and therefore quality upwards.

**Describe the solution you'd like**
Only allow a PR to be merged (or a direct commit) if % code coverage doesn't go down.

This is pretty common SW engineering practice. We did it on the bigchaindb code base with good success. Let's do it here.

**Comment by trentmc** [comment]
Making high priority to prevent further slippage of quality.

**Comment by trentmc** [comment]
Suggestion of how to do it:
https://github.com/oceanprotocol/ocean.js/issues/626#issuecomment-784216054

**Comment by kremalicious** [comment]
this implies the existing codequality tool used in here supports GitHub commit status notifications for each pull request, only after that is setup this repo's branch protection rules can be adapted

**Comment by calina-c** [comment]
Assigning this to Alex, since he already started on the new checks.

**Comment by alexcos20** [comment]
done

**Comment by trentmc** [comment]
Having this done makes me especially happy:)
