### ISSUE TITLE
rename default branch to `main`

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.py#155]
ocean.py, aquarius, provider are the only repos using `master`. This repo should follow the same pattern as all other repos by using `main` as the default branch:

- rename default branch (GitHub has even interface for that in repo settings), deleting `master` in the process
- if any, update all references to `master` branch to `main`
- make sure to switch default branch in any attached tools, like code quality tools, DockerHub etc.

**Comment by calina-c** [comment]
Done for all 3 repos: ocean.py, aquarius and provider. Added DockerHub rules and started image builds from the new branch. Everyone should please remember to update their local settings.

**Comment by trentmc** [comment]
@calina-c are there any remaining steps to close this?

**Comment by calina-c** [comment]
Just discovered a reference in the bumpversion script. I will do that tomorrow.
