### ISSUE TITLE
"--with-provider2" flag apparently needed on barge. If we really do need it, fix docs. If no, deprecate the need

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#166]
## Problem
Until recently, we could run unit tests with barge without any special flags. But I ran into issues, reported eg in #162. Calina noted that in order to give any chance of working, I needed it to have "--with-provider2" flag.

To be precise, the current "recommendation" to test things locally is: 
* Follow steps 1-5 of developers.md, choosing barge steps; except in step 2, make sure barge is clean, and run with provider 2 as follows
```console
run docker system prune -a --volumes    # cleanup the old containers
./start_ocean.sh  --with-provider2   # run barge with provider on
```

This is not not currently in our READMEs (quickstarts and developers.md). Therefore it's a bug because people importing ocean-lib or developers working on ocean.py will fail.

And it's a pretty weird flag.

@kremalicious comment: "I'm also confused about that new --with-provider2. It seems both libraries have this now set in Travis since yesterday. If this flag is required to run anything successful against barge, it should be a default over there"

## Describe the solution you'd like

Do we really need that flag? 
- If no, then let's deprecate the need for it. 
- If yes, then let's improve the documentation

BTW this could be considered an `aquarius` bug, not ocean.py. I wrote it here since I'm approaching this from an ocean.py user perspective.

**Comment by kremalicious** [comment]
yup, basically 2 solutions, either:

1. make `--with-provider2` a default option in barge, effectively deprecating that (undocumented) option there
2. update all repo READMEs where barge is a requirement for running tests with that option, and document that option in barge README

We should probably discuss this over on barge, but from what I can see the `--with-provider2` is only there to workaround an issue which only happens when using barge to run integration tests against it. Since half of barge's use case is to run tests against it, I would be in favor of 1., defaulting to that option. If we opt for 2. then a better name reflecting the use case for that option might be better, like `--testMode` or something

**Comment by trentmc** [comment]
Update: so that at least people using developers.md aren't stranded, I added `--with-provider2` to its instructions as part of commit https://github.com/oceanprotocol/ocean.py/commit/da350f3ab4d1df20cfe85220d97c343f78c30322 (towards #113 better dev instructions).

**Comment by alexcos20** [comment]
--with-provider2 is needed on barge if you want to test compute to data with an asset served by provider1 and an algo served by provider2

Not sure if we need this as default in barge (unless we decide that barge is used mostly for our integration tests)

**Comment by kremalicious** [comment]
ok, then it sounds like we want to go with [option 2](https://github.com/oceanprotocol/ocean.py/issues/166#issuecomment-785816504), updating barge & libraries READMEs. Would still advocate for naming that option based on what it is intended to be used for, like `--test`.

Then we can document it maybe like so:

```
`--test` | For running Compute-to-Data integration tests. Will start an additional `provider` where an asset is served by provider1 and an algorithm served by provider2
```

**Comment by ssallam** [comment]
resolution: keep this option as is and document it in Barge.

**Comment by trentmc** [comment]
> document it in Barge

New issue created for that: [barge#233](https://github.com/oceanprotocol/barge/issues/233)

So we can close this issue.
