### ISSUE TITLE
Deprecate 'Makefile', it's obsolete

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#167]
**Is your feature request related to a problem? Please describe.**
"Makefile" in the main directory seems to be obsolete. Being there confuses things. 

Note that there's also a sub-directory with "docs", and their own Makefile. We don't currently use those, though we could in the future, either for api reference or more generally for "readthedocs" [related epic](https://github.com/oceanprotocol/multi-repo-issue/issues/80).  

**Describe the solution you'd like**
Delete "Makefile". Make sure it doesn't break things, eg for deployment.

Leave the "docs" repo for now, it could be useful soon.

**Notes**

trentmc to ssallam 20200225: "Quick Q: is Makefile in ocean.py used at all? Last update was July 2020. I don't see it referenced in developers.md , RELEASE_PROCESS.md or anywhere really."

ssallam response: "most likely not"

**Comment by calina-c** [comment]
It seems the Makefiles were used for Sphinx documentation, not the actual build. However, Sphinx seems to run perfectly fine without them, too.

**Comment by trentmc** [comment]
Thanks for digging and for the info. So we can delete then? :)

**Comment by trentmc** [comment]
Note: this was deleted in https://github.com/oceanprotocol/ocean.py/commit/c661ee65548d72209a4daf574fe67bf81df7d1f2
