### ISSUE TITLE
Deprecate 'setup.cfg' if appropriate

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#168]
**Is your feature request related to a problem? Please describe.**

ocean.py has both setup.cfg and setup.py. From what I know, you only need one (setup.cfg for static, setup.py for more dynamic setup). Put another way: do we actually need setup.cfg, or can we deprecate it? 

BTW setup.cfg only had one real commit ever, in June 2020. Calina did a change recently but that was part of a more global housekeeping.

**Describe the solution you'd like**

Deprecate setup.cfg, if we can.

**Comment by calina-c** [comment]
Investigating.

**Comment by calina-c** [comment]
@trentmc I'm partial to the idea of using setup.cfg to configure helper tools, such as isort, flake, black and pytest (all only required in development), while keeping setup.py unaware of those options, for "real" environments. Does that make sense?

**Comment by trentmc** [comment]
setup.py has sections for different environments. "development" is one of them. Is it possible to use it for helper tools? What's better?

BTW it seems that the py community isn't at consensus about this. For example:
https://stackoverflow.com/questions/39484863/whats-the-difference-between-setup-py-and-setup-cfg-in-python-projects

The main thing is to pick _a_ way, and then make sure our repos document clearly why we have things that way. (E.g. "we use setup.py for everything, don't use setup.cfg, because __"; or "we use setup.cfg for __, and setup.py for __, because __).

**Comment by calina-c** [comment]
So I should add something like this to the docs? https://stackoverflow.com/a/46090408/14214722

**Comment by trentmc** [comment]
That comment's line of thinking is ok with me. We probably don't need it in the docs. Perhaps instead just at the top of setup.cfg, write "Here is how we view setup.cfg vs setup.py: https://stackoverflow.com/a/46090408/14214722"

And that's it, we can close this issue:)
