### ISSUE TITLE
Get all codacy issues passing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#174]
**Is your feature request related to a problem? Please describe.**

Codacy does linting other tests. 
- It auto-runs remotely. 
- And we can now run locally too, as of #164 :) [Here's the PR](https://github.com/oceanprotocol/ocean.py/pull/169/files).
 
[This Codacy ocean.py dashboard](https://app.codacy.com/gh/oceanprotocol/ocean.py/dashboard) reports *many* issues in ocean.py.
- One subset is from [this PR on developers.md](https://github.com/oceanprotocol/ocean.py/pull/145) leading to [these issues](https://app.codacy.com/gh/oceanprotocol/ocean.py/pullRequest?prid=6996426). 
- But that's just a subset. We should get everything to work.

**Describe the solution you'd like**

- [ ] pass all codacy tests, both local *and* remote

**Comment by trentmc** [comment]
High priority because it makes tox think things fail

**Comment by calina-c** [comment]
Created https://github.com/oceanprotocol/ocean.py/issues/201 for the last issue that wasn't discussed.
As agreed with Trent, we are keeping the static/"self not used" warnings until we upgrade to a correct version of the code, that is aware of the instance and network being used (cross-chain).

**Comment by calina-c** [comment]
The final batch of ignored issues (unused `self`) will take after the next `main` branch merge and build. The raw SQL warning is moved do a different ticket. So this can be closed.
