### ISSUE TITLE
No documentation on developing with Django

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#180]
**Is your feature request related to a problem? Please describe.**

"Use case: I'm a developer building a Django app and want to publish an asset. There's not a single example or instruction in this repo on how to do that. There's a docs folder but nothing helping in there." (from @kremalicious, originally in #113)

**Describe the solution you'd like**
Address the issue above. (See possibilities in the comments).

**Comment by trentmc** [comment]
Using django means a webapp running ocean.py server-side. It's much safer to run ocean.js client-side (in the browser).
 
Therefore (imo) _this_ issue is lower priority. 

*Or*, maybe solving it is simply to put into ocean.py docs: "if you're thinking of doing a webapp with django, we recommend instead to use ocean.js because it can be run the browser without any custodial issues". 

Thoughts, @kremalicious ?

**Comment by kremalicious** [comment]
depends on what we think ocean.py is for. Building web apps with Python/Django seems an industry-standard, and telling someone to use another tech stack completely raises the question what ocean.py then can actually be used for. Not aware of how exactly this works in Python world with interaction with user wallets in a browser. But if we think ocean.py can be used in a Python/Django app we should have a simple setup example. I remember some Python/Django app from Outlier Ventures they did in Python with squid-py back then so seems a valid use case

**Comment by trentmc** [comment]
The main use case for ocean.py is data science use cases. Not webapps.

**Comment by calina-c** [comment]
I propose closing this. Django uses libraries like any other Python package, so I'm not sure what we should document? As to writing a wrapper for django, I don't think that is in our list of priorities. Overall it seems like a wild goose chase, imo.

**Comment by AnaLoznianu** [comment]
Needs more flashing out and more details about what problems Django users encounter.

**Comment by trentmc** [comment]
I agree with @calina-c on this one, you just import it and use it the way you would for any other python lib.

If someone is actually trying to build in Django and sees / wants / needs specific ways to improve, we do stuff then. In the meantime I think we can and should close this issue (imo).

**Comment by trentmc** [comment]
@kremalicious any problems if we close this ticket? Much bigger fish to fry, and we can revisit if/when someone using ocean.py in django has needs and feedback.
