### ISSUE TITLE
'example' folder doesn't do much; either delete or flesh out

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#181]
**Is your feature request related to a problem? Please describe.**
ocean.py code has an `example/` folder but there's only an example how to structure metadata. This is kinda weird, and potentially confusing to new developers.

Related: the marketplace quickstart has an implicit metadata example. And there are unit tests on metadata. 

**Describe the solution you'd like**

Here are some potential ways to address this. 
1. Delete the folder, let the other locations suffice
2. Delete the folder, and place a more thorough metadata example elsewhere in the docs. (Where?)
3. Flesh out the folder with many examples. Risk: redundant with quickstarts and unit tests

We should discuss before we choose one. 

Note: this was originally a one-liner by @kremalicious in #113. I created this new issue discuss more specifically. (Personally I lean towards 1 and just being done with it!)

Note: one more comment from Matthias from #113 which leans towards (3): "all the various documents in the READMEs folder should be extracted into the example folder (why are there examples in code but also in markdown?) with multiple examples. It's painful going through all those files and code snippets, and again not being able to run tests at the end. The examples folder could then have one (!) readme if more explanation is needed for the examples"

**Comment by calina-c** [comment]
I incline towards 1. The purpose of the "garden path" is to have developers learn. It's much more likely that they pay attention to what they paste as an example, as opposed to having the examples readily made. We want them to derive new inputs, not use "templates". That's my 2c, but of course either one of these options can be argued for.

**Comment by trentmc** [comment]
> I assume we are discussing the `examples` folder.

yes

> I incline towards 1.

alright. let's do this then.

> It's painful going through all those files and code snippets [in the READMEs]

FYI it's less painful now, I've merged many py snippets into much larger chunks, and simply used python `#` comments to help demarcate what's going on.
