### ISSUE TITLE
'Connection reset by peer' issues in travis/tox testing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#188]
**Is your feature request related to a problem? Please describe.**
I was working on [this PR](https://github.com/oceanprotocol/ocean.py/pull/171) for ocean.py (for #95). The remote Travis/tox tests are getting failures that look like maybe `provider` issues. 

E.g. line 19316+ gives:
```console
        except (ProtocolError, socket.error) as err:
>           raise ConnectionError(err, request=request)
E           requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
.tox/py38/lib/python3.8/site-packages/requests/adapters.py:498: ConnectionError
```

Here's the full log: https://travis-ci.com/github/oceanprotocol/ocean.py/builds/218812471

My changes were not related to this at all. It looks like provider issues. 

This is a problem because the auto tests in PR come back as "failed", even though they should be passing.

**Describe the solution you'd like**

Issue doesn't come up, so that auto tests in PR do come back as "pass" when they're supposed to pass.

**Additional context**
We've had other related issues in provider in the last two weeks. This issue may possibly be a duplicate with one of those; or maybe something new. Either way it should be solved.

BTW this issue could easily be in `provider` repo too. But I'm including it based on where I observed it -- `ocean.py` repo -- and because it _is_ affecting that repo.

cc @mariacarmina @calina-c

**Comment by calina-c** [comment]
@mariacarmina I think I've seen this on ocean.py on your branch before we made the testing fixes (for validation error response from compute jobs), but I'm not sure. Let's check this after we merge the secure algo branch.

**Comment by trentmc** [comment]
Labeled high priority because it means builds that should pass, don't pass. Hurts our ability to progress the code.

**Comment by ssallam** [comment]
https://github.com/oceanprotocol/provider/issues/114
