### ISSUE TITLE
Deprecate SQL statements

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#201]
**Is your feature request related to a problem? Please describe.**

SQL statements are obsolete as of Ocean V3. So deprecate them.

(Rather than: Right now, we are using raw SQL for statements in ocean_lib/data_store/auth_tokens.py. This is flagged as a potential security risk, via SQL injection. And suggested solution:  We should move to using Flask SQL Alchemy instead.)

**Describe the solution you'd like**
Deprecate

Note: blocked by "remove fake OCEAN"

**Comment by alexcos20** [comment]
kill it

**Comment by calina-c** [comment]
Done, but blocked by deprecating fake OCEAN.
