### ISSUE TITLE
[EPIC] singletons for Web3Provider and more is surprising, non-standard, and won't work for multi-chain

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#202]
**Is your feature request related to a problem? Please describe.**

Status quo: ocean.py has these singletons, via class-level attributes:
1. Web3Provider. Pointer to web3 provider: `ocean_lib/web3_internal/web3_provider.py:Web3Provider` with attribute `_web3` stored at _class_ level. Which makes it a singleton.
2. ContractHandler. The class `ocean_lib/web3_internal/contract_handler.py:ContractHandler` has attribute `_contracts` which caches contracts. It also has `artifacts_path`. 
3. ConfigProvider. The class  `ocean_lib/config_provider.py:ConfigProvider` with attribute `_config` which caches config params including pointer to the network. It's basically like having a bunch of global variables; though at least it's in one place.

Issues with this:
- It's non-standard in web3. The main web3 python tool, web.py, allows a separate object for each web3 connection. Same with brownie.
- The behavior is surprising. You don't really know that it's there unless you know. 
- It won't work for cross-chain, such as Eth mainnet + matic at once. And that is extremely useful behavior for Ocean as we support cross-chain, not to mention other dev users who want to do things like cross-chain arbitrage.
- It gets in the way of unit tests, because right now `./tests/conftest.py::setup_all()` instantiates a local singleton all the time. So you can't easily run tests for more specific behavior with these side effects happening

Note: we _do_ use the brownie pattern of passing in `wallet` as the last parameter into methods that do a blockchain tx. That's good! :) 

**Describe the solution you'd like**

Behave like web3.py and brownie. That is: each ocean = Ocean() object has its own connection to a chain. For example, a single py file with:
```python
ocean_matic = Ocean(matic_config)
ocean_ethmainnet = Ocean(ethmainnet_config)
```

General Strategy:
- Web3Provider: make it an object instance (not singleton)
- ContractHandler: make it an instance instance (not singleton)
- ConfigProvider: make it an instance, or move some of its attributes into instances (eg network url). We'll try different things and see what works best.
- Note: in sw eng, there's a natural tension of providing global variables for convenience, vs tighter scoping for maintainability. A useful middle ground is to have a "context" object that gets passed around (ref Osterhout). "Make it an object" above follows this. We could also have a _single_ object that holds each of these as sub-objects if we like. Let's see what looks best.

**Comment by trentmc** [comment]
Note: doing this will help to prevent issues like #185 and #205 in the future

**Comment by trentmc** [comment]
Preliminary investigation shows that this will break the interface, unless we resort to global variables (and even then it may break the interface; plus we've introduced other global variables!). 

Therefore defer this to V4. (Work will start soon anyway, so ok!)

**Comment by trentmc** [comment]
> I struggle to see the usefulness of a ConfigProvider instance

Yeah, I think you're right, it's probably ok to leave as a singleton. We will need to generalize some of its config parameters to be able to accommodate multiple chains though. But that could be simply stored as a list of configurations for each network, and still "global" in ConfigProvider. Or some other way.

Web3Provider and ContractHandler still need to move away from being singletons.

**Comment by DMats** [comment]
@trentmc My apologies, I was unclear.  I propose that we eliminate the ConfigProvider entirely - singleton variant is effectively global and poor design, instance variant is useless. 

>Web3Provider and ContractHandler still need to move away from being singletons.
Agreed.  We might actually want to eliminate them too :thinking: but I'm not sure yet.

**Comment by DMats** [comment]
# Regarding `Web3Provider`
I think we should eliminate all of it except the `init_web3` function which could be moved to the `web3_internal.utils`.

# Regarding `ContractHandler`
I really like this file - it's well documented and well designed.  But, I think we should eliminate it.  Now that we can import the ocean addresses and ABIs from the `ocean_contracts` module, the ContractHandler seems entirely unnecessary. 

1. All of the file loading stuff is trivially replaced by importing ocean_contracts. Creating a Contract instance is just a few lines:

```pycon
>>> from web3 import Web3
>>> from web3.contract import ConciseContract
>>> from jsonsempai import magic
>>> from artifacts import address, Metadata
>>> web3 = Web3()
>>> contract = web3.eth.contract(address=address.development["Metadata"], abi=Metadata.abi, bytecode=Metadata.bytecode)
>>> contract
<web3.utils.datatypes.Contract object at 0x7f2a32b083a0>
>>> ccontract = web3.contract.ConciseContract(contract)
>>> ccontract
<web3.contract.ConciseContract object at 0x7f2a36a08040>
```

2. I question whether caching (a performance optimization) is worth the extra complexity. Creating a Web3 Contract instance via the python console seemed near instant to me.
3. For 3rd parties that use custom addresses or ABIs (stored as JSON files), we can create a solution that uses jsonsempai.

**Comment by trentmc** [comment]
Re Web3Provider and ContractHandler -- eliminating looks entirely reasonable to me. I love when we can chop away large parts of code and still get the same functionality. So if we can get away with it let's do it.

Re ConfigProvider -- if we eliminate it, how do we handle parameter setting?

**Comment by DMats** [comment]
ocean.py parameters are handled by `ocean_lib.config.Config`, which is passed into `Ocean` upon initialization.

```python
from ocean_lib.config import Config
from ocean_lib.ocean import Ocean
config = Config() # Defaults to whatever CONFIG_FILE is pointing to
ocean = Ocean(config)
```

If we eliminate `ConfigProvider`, that means that internally, `Ocean` will need to pass the config instance to anything that needs it. This approach can seem messy due to the increased parameter passing, but ultimately this is a better design because it avoids global state, makes it clear what the inputs of a function are, and is easier to test.

**Comment by trentmc** [comment]
From a few comments ago:
> [David] I propose that we eliminate the ConfigProvider entirely

From previous comment:
> need to pass the config instance to anything that needs it

The above two statements appear contradictory. Are we going to have a config object or no?

**Comment by DMats** [comment]
Yes, we'll still have a config object - `ocean_lib.config.Config`. We can eliminate `ocean_lib.config_provider.ConfigProvider`

**Comment by trentmc** [comment]
> Yes, we'll still have a config object ...

Thanks. Perfect.

**Comment by alexcos20** [comment]
Moved to high prio, blocks multichain aqua

**Comment by DMats** [comment]
@alexcos20 Per the conclusion from yesterday's sprint planning meeting, I've added additional subtasks to this EPIC and added my estimates.
