### ISSUE TITLE
Several ocean.py modules don't have have test files

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#214]
TODO for this issue: make sure that there _is_ a test file for each module.

Note: this is a sub-issue of the epic in #149. The epic gives a more thorough description / context.

**Comment by calina-c** [comment]
@trentmc I reviewed the existing files.

In order to have full 1:1 correspondence to the modules, we need to create:
- ocean_lib/assets/test/test_asset.py
- ocean_lib/assets/test/test_asset_resolver.py
- ocean_lib/assets/test/test_utils.py
- ocean_lib/data_provider/test/test_exceptions.py
- ocean_lib/data_store/test/test_auth_tokens.py
- ocean_lib/models/test/test_metadata.py
- ocean_lib/models/test/test_order.py
- ocean_lib/ocean/test/test_ocean_compute.py

However, the test coverage is fine since the code lines are covered in combined/integration flows (since they depend on one another). Let me know how to proceed. This is the last issue of the testing epic, but I believe it's lower priority right now. Your call :)

**Comment by trentmc** [comment]
I think it's important to have both unit tests and system tests. The system tests almost certainly don't cover corner cases. And I bet we'll uncover some issues in these as we do them. BTW recently I wrote 50% of the tests for "test_utils.py".

**Comment by DMats** [comment]
Since we created #284 we should close this issue.
