### ISSUE TITLE
Move plecos, do basic cleanups

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#225]
[plecos](https://github.com/oceanprotocol/plecos) has its own pypi version, which makes maintenance a pain.

TODOs for this issue:
- [x] investigate move plecos into ocean.py/plecos or aquarius/plecos
- [x] copy/repurpose tests from plecos
- [x] rename "plecos" -> something else, anything else
- [x] do the low hanging fruit sw eng on plecos
- [x] (optional) Improve unit tests to get >90% coverage -> Călina: moved it to aquarius, where both code-diff and total coverage checks from CodeClimate are passing. I marked it as done, although with a different "meaning".
- [x] adapt/remove/rework usages from other repositories

Related: similar issue for common-util: #226

**Comment by trentmc** [comment]
@ssallam can you give your thoughts on scenario (1) vs (2) in the description, please?

**Comment by trentmc** [comment]
Close because now with #226

**Comment by calina-c** [comment]
@trentmc Added this into aquarius now, since we needed plecos updates and Alex asked to move it too. I addressed most of the concerns, except for renaming and work in other repos.

Ref. renaming: is it necessary? What would you suggest?
Ref. work in other repos: to be done after we merge stable-aqua.

**Comment by trentmc** [comment]
> Ref. renaming: is it necessary? What would you suggest?
Not strictly necessary, but having a random name is unnecessary complexity and can hinder DX. So I strongly suggest renaming it. E.g. to "validate-metadata" directory, or ideally a shorter name. (Open to suggestions! :)

**Comment by trentmc** [comment]
BTW It's great to see this ticket happening! :)

**Comment by calina-c** [comment]
Done on provider.
In review/discussion on ocean.py.
Blocked by stable-aqua merge in aquarius.

**Comment by AnaLoznianu** [comment]
@alexcos20 Please take a look over this one once we deploy stable aqua

**Comment by calina-c** [comment]
Moved in `aquarius/ddo_checker`. Marking this as closed.
