### ISSUE TITLE
Move common-util & plecos into ocean.py, test better, do basic cleanups

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#226]
[common-utils-py](https://github.com/oceanprotocol/common-utils-py)  has its own pypi version, which makes maintenance a pain.

TODOs for this issue:
- [x] move common-utils into ocean.py/common
- [x] copy/repurpose tests from common-utils
- [x] do the low hanging fruit sw eng on common-utils

**Comment by trentmc** [comment]
@ssallam can you give your thoughts on scenario (1) vs (2) in the description, please?

**Comment by calina-c** [comment]
Here is my audit, please give me feedback and instructions on how to proceed.

[https://app.zenhub.com/files/266274883/8f92c653-3a81-4a84-9f3e-5aaf711dcb9a/download](https://app.zenhub.com/files/266274883/8f92c653-3a81-4a84-9f3e-5aaf711dcb9a/download)

**Comment by trentmc** [comment]
Here are A's to Q's in the doc. 

> what is a keeper ?

A blockchain node. Was more important in Ocean V1 and V2 when Ocean had its own network. For V3 we deprecated having its own network and therefore removed the need for "keeper".

> Question: why are we validating metadata here? Shouldn’t this be a part of plecos ?

We shouldn't be, it should be part of plecos.

> Public Key Base
> there is a lot of duplicated code 

Move to DRY of course.

> Public Key Base
> Question: Are we supporting all these types of keys? Is it worth it to keep all the options?

We can probably reduce, as some of them are probably leftovers from V1 / V2 complexity.

**Comment by alexcos20** [comment]
We should leverage as much as we can from ocean.py and ditch common-utils.

**Comment by trentmc** [comment]
How about:
- move all of common-util into a sub-directory of ocean.py/ocean_lib/
- move all of plecos ""
- aquarius and provider use ocean.py as needed
- we only have to maintain ocean.py

**Comment by trentmc** [comment]
Note: updated description heavily

**Comment by trentmc** [comment]
I just moved the plecos TODOs back into its original issue: #225 

Therefore _this_ issue's TODOs are done. We can close! :)
