### ISSUE TITLE
References to aquarius_url & metadata_store_url are inconsistent; replace with metadata_cache_uri everywhere

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#229]
There are multiple references inside ocean.py to metadata_store_uri and aquarius_url, and they are loaded from the same configuration option, called aquarius_url. However, the user can supersede these with metadata_cache_uri. Currently we have 3 names for the same thing, or things that are very similar, and it is confusing to users and code maintainers.

**Solution**
Settle on one of these and adjust variable naming and config loading to use one name, or document why and when different names can be used.

The one to use is: `metadata_cache_uri`. 
- Details: `aquarius_url` was the first name, then it was changed to `metadata_store_url` to move away from "aquarius" in general. 
- Some places were kept simply for backwards compatibility. But the essence of this ticket is correct: things could be a lot cleaner without sacrificing backwards compatibility.

**Additional context**
This has been tackled in a previous issue (#126), but only in terms of config. The naming is still random in the codebase itself.

**Comment by trentmc** [comment]
@calina-c fyi I updated the description for which name to change to

**Comment by mariacarmina** [comment]
Update: References to `aquarius_url` & `metadata_store_url`.

**Comment by DMats** [comment]
Should usages of `aquarius_url` be changed to `metadata_cache_uri` as well? I've listed examples below.

For the `OceanAssets._aquarius_url` property, would it make sense to create a new `OceanAssets._metadata_cache_uri` property that contains the same value as `_aquarius_url`?

```
21 results - 4 files

ocean_lib/ocean/ocean_assets.py:
   54:         self._aquarius_url = config.aquarius_url
   69:         return AquariusProvider.get_aquarius(url or self._aquarius_url)
  369:         return resolve_asset(did, metadata_cache_url=self._config.aquarius_url)
  372:         self, text: str, sort=None, offset=100, page=1, aquarius_url=None
  381:         :param aquarius_url: Url of the aquarius where you want to search. If there is not
  389:             for ddo_dict in self._get_aquarius(aquarius_url).query_search(
  395:         self, query: dict, sort=None, offset=100, page=1, aquarius_url=None
  405:         :param aquarius_url: Url of the aquarius where you want to search. If there is not
  410:         aquarius = self._get_aquarius(aquarius_url)
  578:         return self._get_aquarius(self._aquarius_url).validate_metadata(metadata)

ocean_lib/ocean/ocean_compute.py:
  131:                 trusted_algorithms, ConfigProvider.get_config().aquarius_url
  209:             "metadataUri": config.aquarius_url,
  288:         asset = resolve_asset(did, metadata_cache_url=self._config.aquarius_url)
  393:             asset = resolve_asset(did, self._config.aquarius_url)

ocean_lib/test/test_config_provider.py:
   29:     assert "http://ItWorked.com" == ocean_instance.config.aquarius_url
   36:     assert "http://ItWorked.com" == ocean_instance.config.aquarius_url
   71:     assert config.aquarius_url == "https://custom-aqua.url"
   73:     assert config.metadata_store_url == config.aquarius_url
  146:     assert config.aquarius_url == "https://another-aqua.url"

tests/integration/test_compute_flow.py:
  240:         [algorithm_ddo.did], setup.publisher_ocean_instance.config.aquarius_url

```

**Comment by trentmc** [comment]
We should get rid of all instances of `aquarius_url` and `metadata_store_uri`, and _only_ have `metadata_cache_uri`. 

(This is alright from a semantic versioning perspective, as ocean.py is still in 0.x.x.)

> Update: References to aquarius_url & metadata_store_url are inconsistent. 

There should only be one thing. And it should be `metadata_cache_uri`.

> Should usages of aquarius_url be changed to metadata_cache_uri as well? I've listed examples below.

Yes, absolutely, just like the description of this ticket says.

**Comment by mariacarmina** [comment]
@trentmc I was curious if it's needed to update the name of the env vars too, because actually we have the `AQUARIUS_URL` env var. I have discussed with @DMats and we thought that maybe it could cause breaking of the code and it's better to avoid this change of the env vars. What is your opinion about this aspect?

**Comment by trentmc** [comment]
Remember we are still in 0.x with ocean.py, therefore with semantic versioning it's ok to break the api. 

David's changes on base18 api are gonna massively change the api in the coming week or two. So users of ocean.py will have to make changes for that. 

But we're in the midst of a big C2D release and changes here might affect Aquarius and more. I don't want to mess with that.

Therefore I recommend to have backwards compatibility to `AQUARIUS_URL` for now:
- it can set the value from either envvar `AQUARIUS_URL` _or_ `METADATA_CACHE_URL`. 
- If _both_ are set then raise an error
- If only `AQUARIUS_URL` url is set then give a warning that this will be deprecated in favor of `METADATA_CACHE_URL` in the future.

**Comment by mariacarmina** [comment]
Ok, got it now, need to do a fallback on `AQUARIUS_URL`.

**Comment by DMats** [comment]
Quoted from Slack:

>David Hunt-Mateo  11:27 AM
>@trentmc in your latest comment https://github.com/oceanprotocol/ocean.py/issues/229#issuecomment-820517285 you mention `METADATA_CACHE_URL`. Did you mean to say `METADATA_CACHE_URI`?
>
>trentmc  1:04 PM
Yes
