### ISSUE TITLE
Is ocean.py compatible with aquarius 2.2.5 ?

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#236]
As we started rolling out aqua 2.2.5 (already deployed on ropsten), we should make sure that ocean.py is compatible)

**Comment by ssallam** [comment]
Findings:
- search in ocean.py is currently broken
- aquarius query endpoint is too restrictive (https://github.com/oceanprotocol/aquarius/issues/416)
- ocean_util is not updated to reflect the new query interface in aquarius (https://github.com/oceanprotocol/common-utils-py/issues/25)
- query tests in ocean.py are not sufficient
