### ISSUE TITLE
polygon network not in ocean.util supported networks

### ISSUE THREAD

**Issue by kenbodnar** [oceanprotocol/ocean.py#238]
**Describe the bug**
The polygon network is not in ocean.util variables of supported networks

**To Reproduce**
View variable assignment of supported networks in ocean.util.py

**Expected behavior**
Expected to see this if polygon network is being used by aquarius to extract data

**Comment by trentmc** [comment]
Done in https://github.com/oceanprotocol/ocean.py/commit/700da80fbdf0e403ace1f23613ed8d4f093c9434
