### ISSUE TITLE
OceanPool isn't needed, so deprecate

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#239]
NOTE: we might not do this, we need to discuss whether we really want to do it first.

**Motivation**

OceanPool was intended as a thin wrapper for BPool, for convenience: so users wouldn't have to think about many steps to add OCEAN token, etc.

But there are issues:
- It has very poor test coverage. We could write tests but it will take time
- OCEAN is a less obvious default going forward: Ocean Market frontend will be moving to using a stablecoin (eg OceanO), and frontend forks may use other tokens too. 
- We've discussed internally and will move away from all of ocean.py thin wrappers, including this one. Having thin wrappers like this adds complexity and hurts maintainability. You can still have good DX by making modules easy to use, in the same way that web3.py and scikit-learn does.

**TODO for this issue**

- [ ] Deprecate OceanPool and any dependencies

** Notes **

- On timing: doing this causes breaking changes to the ocean.py interface, which means a major version change. So it needs to get shipped in eg "V4".
- #240 is similar, but for the ocean.py convenience methods
- Complementary: better readthedocs-style documentation

**Comment by AnaLoznianu** [comment]
Linked issue: https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/240

**Comment by DMats** [comment]
At today's sprint grooming meeting, I expressed concerns about removing OceanPool.

Currently: 
1. OceanPool in Ocean.py and OceanPool in Ocean.js are similar - they share an intent, even if the details differ.
2. BPool is a thin wrapper around the underlying Balancer V1 smart contracts.
3. OceanPool is a wrapper around BPool - it restricts pools to contain only Ocean and Datatokens

Questions:
1. Is there a good reason for the intent of OceanPool in Ocean.py to diverge from Ocean.js?
2. If we removed or changed OceanPool in Ocean.py, would Ocean.js follow suit?
2. What are the maintenance costs of the current OceanPool API?
2. Is the Ocean/DataToken pool use case common enough to warrant its own API?
4. Does the Ocean/Datatoken pool use case help drive our core KPIs?

I attempted to develop an opinion on this matter but ended up flip-flopping many times.

**Comment by calina-c** [comment]
Removing the Status:Refined label since it does not apply. Moving both this and #240 to issues that are not confirmed. There are still discussions related to this. Possibly we will improve OceanPool instead of removing it, but v4 takes priority (and might change the context for this one).

**Comment by calina-c** [comment]
@trentmc do you think we can close this?

**Comment by trentmc** [comment]
Closing this since we're keeping some convenience methods.
