### ISSUE TITLE
ocean.py convenience methods aren't needed, so deprecate

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#240]
NOTE: we might not do this, we need to discuss whether we really want to do it first.

**Motivation**

The `ocean()` object provides a number of convenience methods that are thin wrappers, like creating a data token. The idea was that users don't have to think about many more steps

But, this adds complexity and hurts maintainability. You can still have good DX by making modules easy to use, in the same way that web3.py and scikit-learn does.

**TODO for this issue**

- [ ] Deprecate the thin interface wrappers on `ocean()` object. Update the quickstarts to use the modules.'

**Notes**

- On timing: doing this causes breaking changes to the ocean.py interface, which means a major version change. So it needs to get shipped in eg "V4".
- #239 is similar, but for OceanPool convenience class
- Complementary: better readthedocs-style documentation

**Comment by calina-c** [comment]
Moving. to longer term and removing the "Status:Refined" label. See the discussion in #239 better.

**Comment by trentmc** [comment]
Closing this since we're keeping some convenience methods.
