### ISSUE TITLE
EIP-155

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#246]
With Geth v1.10.0, EIP-155 is enforced (see https://blog.ethereum.org/2021/03/03/geth-v1-10-0/, chapter "ChainID enforcement")

All transactions need to follow https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md or they will be rejected in the future (Infura runs v1.10.0, but with --rpc.allow-unprotected-txs, so we are safe for the moment ).

All sending transactions should include chainId as well.

**Comment by trentmc** [comment]
Note, based on AlexC comments: put to high priority because the current workaround is Infura, and they might stop support for this at any minute. Ideally by Apr 7 or so.

**Comment by mariacarmina** [comment]
I have assigned @md00ux  because he helped me a lot with the config for this task and the setup itself.
