### ISSUE TITLE
Fix code and logic duplication in event retrieval

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#252]
Right now there seems to be a lot of duplication with Ethereum events. Different classes have the same way of retrieving and filtering events, but instead of being one single point of failure, we have functions that are copies of one another. Moreso, there are functions that retrieve a single event (e.g. get_transfer_event), which have the same problem. Same for event log retrieval.

**Possible solution**
Devise a common entrypoint: a class or set of functions that handles event filtering. Call those instead. We could possibly use some of the existing classes e.g. EventFilters. Make sure to write documentation on filtering, to advise for these best practices, s.t. we don't end up in the same place after the refactor.

**Additional context**
Codacy does not currently support code duplication for Python, but moving to code climate might make this job easier, if that is in the plans.

The [eth-event](https://github.com/iamdefinitelyahuman/eth-event) repo is a small python library for handling events. Built & maintained over the last 2+  years by the brownie creator. This repo could help. It also introduces a [few error types](https://github.com/iamdefinitelyahuman/eth-event/blob/master/eth_event/main.py) that we could use as well.

**Comment by calina-c** [comment]
@alexcos20 tagging you for CodeClimate. I remember we discussed implementing it. Is there a ticket for that? Is it still a valid plan for the future? Does CodeClimate support Python duplication?

CC @trentmc, if you have anything to add to the issue description. Thoughts or points etc.

**Comment by trentmc** [comment]
Actually, we already have two common modules to handle events:
- `ocean_lib.web3_internal.event_listener.EventListener`
- `ocean_lib.web3_internal.event_listener.EventFilter`

But maybe those aren't used so extensively?

Therefore, perhaps the scope of this issue is: 
- for each module that has custom event functionality 
  - port its functionality to use the modules above (and extend functionality of modules above if needed)

**Comment by trentmc** [comment]
Note: in [Aquarius#403](https://github.com/oceanprotocol/aquarius/issues/403), its fix included cleaning up some event logic, maybe that's useful here too. [Here's the PR](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/438).
