### ISSUE TITLE
licenseheaders pre-commit hook always fails

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#258]
## Expected Behavior

`licenseheaders` pre-commit hook should pass when all changed files contain the copyright header

## Current Behavior

`licenseheaders` pre-commit hook always fails when run via `git commit` or `pre-commit run`, even when all the changed files contain the copyright header. It passes when run via `licenseheaders -t .copyright.tmpl -f X` where X is a space-delimited list of file paths for any changed files.

## Failure Information (for bugs)

I attempted to debug the issue and documented my efforts https://github.com/oceanprotocol/ocean.py/pull/254#issuecomment-810786192

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Make a change in any file and add it to the stage using `git add`
2. Attempt to commit the change using `git commit`
3. Observe the failure.

### Possible Solution

Might require a fix in licenseheaders.

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: v0.5.14
* Python: 3.8.5
* OS: Ubuntu 20.04.2 LTS (Focal Fossa)

## Failure Logs

```console
Traceback (most recent call last):
  File "/home/david/.cache/pre-commit/repoq7hxw3il/py_env-python3.8/bin/licenseheaders", line 8, in <module>
    sys.exit(main())
  File "/home/david/.cache/pre-commit/repoq7hxw3il/py_env-python3.8/lib/python3.8/site-packages/licenseheaders.py", line 823, in main
    arguments = parse_command_line(sys.argv)
  File "/home/david/.cache/pre-commit/repoq7hxw3il/py_env-python3.8/lib/python3.8/site-packages/licenseheaders.py", line 379, in parse_command_line
    known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in TYPE_SETTINGS.items() if "extensions" in conf]
  File "/home/david/.cache/pre-commit/repoq7hxw3il/py_env-python3.8/lib/python3.8/site-packages/licenseheaders.py", line 379, in <listcomp>
    known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in TYPE_SETTINGS.items() if "extensions" in conf]
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by calina-c** [comment]
@DMats can you run `pip freeze | grep licenseheaders`? I just did a full run for all the files in ocean.py, I had no issues.

**Comment by DMats** [comment]
@calina-c Here's my licenseheaders version.  I'll try the other two suggestions the next time I have changes to commit. I know I had tried `pre-commit clean` back when I was troubleshooting this error.

```
(venv) david@david-Inspiron-5502:~/projects/aquarius$ pip freeze | grep licenseheaders
licenseheaders==0.8.7
```

**Comment by calina-c** [comment]
I can reproduce it after merging the changes in main. It's a problem with licenseheaders itself, but I've opened a PR with the maintainer: https://github.com/johann-petrak/licenseheaders/pull/58

Fingers crossed!

**Comment by johann-petrak** [comment]
I merged the PR. Please test and let me know if it works I will upload a new version. 
Thanks!

**Comment by calina-c** [comment]
@DMats can you please test with the master version of license-headers? If it works, we'll let Johann know and we can move back to 0.8.x

**Comment by DMats** [comment]
@calina-c @johann-petrak 
I re-installed the pre-commit hooks (which pulls the latest from licenseheaders master branch) and tried committing a trivial change (added a space to a docstring) and the licenseheaders hook passed! In other words, it looks like the fix worked. Please proceed with the 0.8.x version release.

```
(venv) david@david-Inspiron-5502:~/projects/ocean.py$ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[WARNING] The 'rev' field of repo 'https://github.com/johann-petrak/licenseheaders.git' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/johann-petrak/licenseheaders.git.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/johann-petrak/licenseheaders.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
(venv) david@david-Inspiron-5502:~/projects/ocean.py$ git commit
[WARNING] The 'rev' field of repo 'https://github.com/johann-petrak/licenseheaders.git' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
licenseheaders...........................................................Passed
```

**Comment by johann-petrak** [comment]
OK, I created and uploaded version 0.8.8 from the latest master.
