### ISSUE TITLE
Improve type hints

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#259]
This issue is a follow-on of https://github.com/oceanprotocol/ocean.py/issues/37

Possible improvements:

- [x] In cases where a function docstring includes type hints, but the function signature does not, add the type hints to the signature.
- [x] Apply the `@enforce_types_shim` decorator to every class and function.

**Comment by calina-c** [comment]
I have reestimated this ticket since it now covers typing throughout all the modules, not just a partial improvement.
