### ISSUE TITLE
Resolve or ignore issues in codacy coverage report

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#261]
The ocean.py codacy coverage report PR check fails. Despite it being a non-required check, it's probably a good idea to either resolve or ignore the issues it identified.

Codacy Issues List: https://app.codacy.com/gh/oceanprotocol/ocean.py/issues

**Comment by calina-c** [comment]
Ref codacy static analysis: I did some ignoring cleanup and asked Maria to integrate the issues with the non-assigned variables from test_config (as part of her branch to improve testing). Once that is done, can you let me know @mariacarmina? I'll re-check to see if any Codacy Static Analysis issues re-appear.

Ref codacy code coverage, there are two tickets about this in provider and aquarius (i.e "only allow merges if code coverage is ratcheting up". I'll reformulate this one to say the same thing, *after* we re-fix the Static Analysis part.

**Comment by calina-c** [comment]
We no longer send coverage reports to Codacy. :) Issues are moved to CodeClimate.
