### ISSUE TITLE
Support changing rate in FixedRateExchange (FRE)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#264]
Ocean.py should be able to allow users to update the rate for a given fixed rate exchange
(https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/ocean/ocean_exchange.py)

**Comment by calina-c** [comment]
Closed by https://github.com/oceanprotocol/ocean.py/pull/265, only it seems I did not connect it to this ticket.
