### ISSUE TITLE
Add good compute-to-data example README

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#279]
Pre-requisite: #101

Motivation:
- Help stabilize compute-to-data
- Nice onboarding for python users to (a) use compute-to-data, in (b) a data science context

Basic flow of README
- Alice mints datatokens and publishes data asset
- transfers some to Bob
- Bob consumes in a CtD setting. The algorithm can be simple, eg `average()`

What it does _not_ need, and should not have
- Marketplace stuff
- Conversion between fiat value and OCEAN
- AI/ML tool (eg logistic regression from scikit-learn), since Raven is already working on that.

Potential sources of useful info:
- https://github.com/oceanprotocol/ocean.js-cli/blob/main/src/commands.ts
- https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/ocean/test/test_ocean_compute.py
- #101 has a flow shared by Alex C
- simple README, marketplace README
- 20210429 Matthias list of CtD resources: https://oceanprotocol.slack.com/archives/C0D6JB45D/p1619638827175700
- Ocean docs "Writing Algorithms for Compute to Data" [link](https://docs.oceanprotocol.com/tutorials/compute-to-data-algorithms/)
- [ocean_lib/data_service_provider::start_compute_job()](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/data_provider/data_service_provider.py)
- [test_start_compute_job_fails_empty(), more](https://github.com/oceanprotocol/ocean.py/blob/ae45e4207f8c268c8d7a9d28704663de152d4608/ocean_lib/data_provider/test/test_data_service_provider.py)
- https://docs.oceanprotocol.com/tutorials/compute-to-data-algorithms/

**Comment by trentmc** [comment]
@mariacarmina @calina-c I will take over this issue

**Comment by calina-c** [comment]
Waiting on the computeResult endpoint, where I encountered some trouble.

**Comment by trentmc** [comment]
> Waiting on the computeResult endpoint, where I encountered some trouble.

Where's the being worked on / who's working on it? (More context please:)

**Comment by calina-c** [comment]
I'm working on it. Alex helped and it's just a missing env var to be defined in that task. So I'll unblock this in ~30mins
