### ISSUE TITLE
Assert vs AssertError pattern

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/ocean.py#282]
So far the code base has two different patterns for the assertion handling:

```python
# first option
if <CONDITION>:
     raise AssetsError()
# second option
assert <CONDITION>, <ERROR MSG>
```

Both of them are equivalent except that `assert` statements can be globally disabled with the `-O` command-line flag.

**Comment by trentmc** [comment]
The nuances for these two patterns are different:
- The first can raise any error type, which gives the opportunity for specificity
- The second can only raise an AssertionError

Therefore this ticket is a wontfix. Closing.
