### ISSUE TITLE
Add unit tests and improve code coverage (part 2)

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#284]
Follow-on of Issue #214 and PR #267. 

A couple of high-priority bug fixes became wrapped up in #267 so it was cut short and merged before adding all the desired unit tests. This issue #284 is for adding the unit tests that were missing from #267.

TODO:
Add unit tests for the following files (list copied from issue #214 and then augmented):

- [x] ocean_lib/assets/test/test_asset.py
- [x] ocean_lib/assets/test/test_asset_resolver.py
- [x] ocean_lib/assets/test/test_utils.py
    - [x] test that attempts to remove an algo that doesn't exist in the trusted algos list
    - [x] test that attempts to add an algo that already exists in the trusted algos list
    - [x] improve `test_create_asset_with_owner_address` (see below)
- [x] ocean_lib/data_provider/test/test_exceptions.py
- [x] ocean_lib/data_store/test/test_auth_tokens.py
- [x] ocean_lib/models/test/test_metadata.py
- [x] ocean_lib/models/test/test_order.py
- [x] ocean_lib/ocean/test/test_ocean_compute.py
- [x] ocean_lib/ocean/test/test_ocean_assets.py
    - [x] improve `test_create_asset_with_owner_address` (see below)
- [x] ocean_lib/ocean/test/test_util.py

# Improve `test_create_asset_with_owner_address`
Problem:
This test only checks whether the asset is created when both `owner_address` and `data_token_address` parameters are set. I think more assertions are warranted. 

Details:
After digging into `OceanAssets.create()` I realized that the `owner_address` parameter is silently ignored if `data_token_address` parameter is set.

Possible Solution:

```python
# Create two assets: one with `owner_address` set, the other without.
asset_1 = ocn.assets.create(
        asset.metadata,
        alice,
        [auth_service],
        owner_address=alice.address,
        data_token_address=token.address,
    )
assert asset_1
asset_2 = ocn.assets.create
        asset.metadata,
        alice,
        [auth_service],
        data_token_address=token.address,
    )
assert asset_2
# Verify that the resulting assets are equivalent.
assert asset_1 == asset_2
```

# Improve `test_create_asset_with_owner_address` 
Problem:

The current test calls `OceanAssets.create()` with the `owner_address` parameter set to the same address as the `publisher_wallet`. 

Possible Solution:

1. Duplicate this test.
2. Change the first test so that the owner_address parameter is different from the publisher address.
3. Keep the second test the same.

Reasoning:
This tests both the intended and unintended usage of the method.

**Comment by DMats** [comment]
@mariacarmina Just a head's up.  The list of files in the description of this issue is simply copied from the original issue #214 and then I added some more. So it's entirely possible that some of the files already have sufficient unit tests. If that's the case, please just go ahead and mark them complete.

**Comment by mariacarmina** [comment]
Thank you  @DMats, I saw that there are some duplicates, but it's ok.

**Comment by mariacarmina** [comment]
To test the `exceptions.py`, can I add to `ocean_lib/test` folder instead of `ocean_lib/data_provider/test/`?

**Comment by mariacarmina** [comment]
`auth_tokens.py` is obsolete, checked with @calina-c. No unit tests needed for that.
