### ISSUE TITLE
Replace camelCase occurrences with snake_case in ocean.py

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#338]
Replace camelCase occurrences with snake_case in ocean.py except where the camelCase is a 1:1 match with an underlying smartcontract method. Required in #333.

**Comment by DMats** [comment]
I updated the task description to include the caveat mentioned by @trentmc here: https://github.com/oceanprotocol/ocean.py/pull/333#issuecomment-850413138
