### ISSUE TITLE
Asset status object

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#339]
**Describe the bug**
Ocean.py should follow the new status object in the metadata (https://github.com/oceanprotocol/OEPs/tree/master/8/v0.5#status-attributes)
The status object is located in the metadata service, and not in root

Actual code:
https://github.com/oceanprotocol/ocean.py/pull/314/files#diff-4fe12d33e5b6cf223d037f7ebc710c73cca03d661a204ab6cf19a5a3951f084aR74

(This will require a provider update as well)

**Comment by calina-c** [comment]
Won't need provider update, since we are using the ocean.py functions in provider. But I'll bump version to make sure everything is well "under the hood"

**Comment by calina-c** [comment]
#349 works on moving the status object in its right place, but per @trentmc we are not sure whether the scope of this issue is just to move the existing implementation of `isOrderDisabled` (done in #349) or if it includes the other flags as well.

**Comment by trentmc** [comment]
I think it makes sense for ocean.py to support all the flags. You can do it in this issue, or create a new one.
