### ISSUE TITLE
Resolve ABI Mismatch warnings in marketplace-flow README

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#348]
- [ ] resolve the `ABI Mismatch` issue;
 Code: `data_token = ocean.create_data_token('DataToken1', 'DT1', alice_wallet, blob=ocean.config.metadata_cache_uri)`

 _Log:_ `/home/maria/Desktop/test3/venv/lib/python3.8/site-packages/web3/contract.py:1162: UserWarning: The log with transaction hash: b'\x15\x87\x0f\x1a\xe5I \xc5\x8a#\x00\xfc\x19\xdb\xc49\xb2;~oM3\xbb\xcb$$\xd2K\xc0\x07\xfa\x0b' and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.`

Code: `order_tx_id = ocean.assets.pay_for_service(quote.amount, quote.data_token_address, asset.did, service.index, fee_receiver, bob_wallet, None)`

 _Log:_ `/home/maria/Desktop/test3/venv/lib/python3.8/site-packages/web3/contract.py:1162: UserWarning: The log with transaction hash: b'\x07S^\xadT\xd4\xcbl/\xcc\xde\xd3\x1dZ\x8f\xefg\x83N.$k\xc0\x82\x82\xe8\x80\xb6?f\x84\xba' and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.`

**Comment by DMats** [comment]
Yesterday @mariacarmina and I spent a couple of hours investigating this issue. Unfortunately, we were not able to diagnose the problem.  

We know that the issue started occurring after #333 when we upgraded from Web3 v4 to v5. 

The `MismatchedABI` exception is thrown at line events.py::211 inside `get_event_data`.

```python
@curry
def get_event_data(abi_codec: ABICodec, event_abi: ABIEvent, log_entry: LogReceipt) -> EventData:
    """
    Given an event ABI and a log entry for that event, return the decoded
    event data
    """
    if event_abi['anonymous']:
        log_topics = log_entry['topics']
    elif not log_entry['topics']:
        raise MismatchedABI("Expected non-anonymous event to have 1 or more topics")
    # type ignored b/c event_abi_to_log_topic(event_abi: Dict[str, Any])
    elif event_abi_to_log_topic(event_abi) != log_entry['topics'][0]:  # type: ignore
        raise MismatchedABI("The event signature did not match the provided ABI") # <-- Exception originates here
    else:
        log_topics = log_entry['topics'][1:]
... <snip> ...
```

At the moment the exception occurs:

* event_abi_to_log_topic(event_abi) = b'C~\x99\xa6\x9ccA(\xe6z\x85ek\x80\xd0;\x02\x8b\xa3u%\xb1Pp`n\\(\xe8F\x98J'
* log_entry['topics'][0] = <HexBytes, len() = 32>
* str(log_entry['topics'][0]) = 'b"\\x11|r\\xe6\\xc2_\\n\\x07.6\\xe1H\\xdfqF\\x8c\\xe2\\xf3\\xdb\\xe7\\xde\\xfe\\xc5\\xb2\\xc2W\\xa6\\xe3\\xebe\'\\x8c"'
* event_abi = {'anonymous': False, 'inputs': [{...}, {...}, {...}, {...}, {...}, {...}], 'name': 'TokenRegistered', 'type': 'event'}
* log_entry = AttributeDict({'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xc132c3ca2804838a5250de001cf60fa59c9a2c48236d8aeacd550cb6bef5365f'), 'blockHash': HexBytes('0x2d3870df0872c3db7436e5ab90cd632866318b5dfc1767454225a03d737eed8c'), 'blockNumber': 20, 'address': '0x726baA2f854A3BEC2378a707AeB38c9d933Ebad6', 'data': '0x00000000000000000000000028a45568638aa936d2046c970a107e74371bb2e8', 'topics': [HexBytes('0x117c72e6c25f0a072e36e148df71468ce2f3dbe7defec5b2c257a6e3eb65278c')], 'type': 'mined', 'removed': False})


In Web3.py v5, the `web3._utils.events.get_event_data()` function gained an `ABICodec` parameter so whenever `get_event_data() is used in ocean.py, we now pass it `web3.codec`. I hypothesized that the codec we pass doesn't match the codec used to deploy the contracts and that somehow caused the ABI mismatch warnings.  However, looking at the `get_event_data()` logic revealed that the `MismatchedABI` exception is raised before the `ABICodec` parameter is used. From this, I conclude that the ABICodec is not the cause of the error.

**Comment by mariacarmina** [comment]
Due to the fact that there are plenty of issues regarding `MismatchedABI` on the internet, I have discussed with @alexcos20 and we establish that it might be an issue from web3 library. But I am not quite about that
For reference, I attached the links with some similar problems:

- https://github.com/ethereum/web3.py/issues/1830 (I need to mention here that I have tried to reproduce this and this information could not help at all, because of the web3 type constraints)

I have also used the latest version on `ocean-contract` which is `0.6.4` and I have replaced `processReceipt` with `processLog`, but the actual warnings that we were struggling, were transformed into actual errors with the same message. The approach of replacement the `processReceipt` with `processLog` came up after reading these https://github.com/cartesi/arbitration-dlib/commit/871bf47ef49ff2d7740e3b0bc131bd6a01974ed7 and https://github.com/cartesi/arbitration-dlib/commit/0c5fd5713233eac8f1d5b81751a9cab4c5d80202, but I guess it works for partition events.

After some time of discussion with @DMats , we find a temporary fix, but this approach do NOT resolve the warning itself, it just discards the warnings, but we wanted to actually fix it and to know from where this `MismatchedABI` warning comes. The temporary changes are available on the linked PR and hopefully @alexcos20 can share his thoughts on it.

**Comment by DMats** [comment]
@mariacarmina @alexcos20 @calina-c @trentmc 

# `MismatchedABI` warnings are harmless and should be suppressed with `errors=DISCARD`
I have determined that the `MismatchedABI` warnings are harmless and it is OK to suppress them by passing `errors=DISCARD` to the `processReceipt` method like so:

```python
ContractEvent().processReceipt(receipt, errors=DISCARD)
```

# Why do the `MismatchedABI` warnings occur?
The `ContractEvent.processReceipt()` method processes all of the event logs included in the transaction receipt, even those that don't match the ContractEvent's ABI. Each time an event log is processed that doesn't match the ContractEvent's ABI, the `MismatchedABI` warning is raised.

Take the `DTFactory.createToken()` contract method as an example.  When executed it emits 3 events:
1. InstanceDeployed - https://github.com/oceanprotocol/contracts/blob/v0.6.4/contracts/utils/Deployer.sol#L44
2. TokenCreated - https://github.com/oceanprotocol/contracts/blob/v0.6.4/contracts/DTFactory.sol#L99
3. TokenRegistered - https://github.com/oceanprotocol/contracts/blob/v0.6.4/contracts/DTFactory.sol#L100

If the caller then processed the resulting transaction receipt using `DTFactory.events.TokenRegistered().processReceipt()` the first two event logs would cause `MismatchedABI` warnings because they don't match the `TokenRegistered` ABI.

# Why didn't Web3.py v4 emit `MismatchedABI` warnings?
`ContractEvent.processReceipt()` calls `ContractEvent._parse_logs()` which contains an exception handler for the `MismatchedABI` exception.  

* [Web3.py v4 `_parse_logs`](https://github.com/ethereum/web3.py/blob/v4/web3/contract.py#L1282) catches the `MismatchedABI` exception and continues without emitting a warning. This behavior was not configurable.
* [Web3.py v5 `_parse_logs`](https://github.com/ethereum/web3.py/blob/v5.19.0/web3/contract.py#L1140) catches the `MismatchedABI` exception and emits a warning but it can be configured to mimic the v4 behavior by passing `errors=DISCARD`. See the docs for a full list of error handling behaviors (WARN, STRICT, IGNORE, DISCARD): https://web3py.readthedocs.io/en/stable/contracts.html?highlight=processReceipt#web3.contract.ContractEvents

# Reference
Here's the test script I used to debug this issue. It simply creates a token and processes the transaction receipt.

```python
from ocean_lib.config import Config
config = Config('config.ini')

from ocean_lib.ocean.ocean import Ocean
ocean = Ocean(config)

import os
from ocean_lib.web3_internal.wallet import Wallet
alice_wallet = Wallet(ocean.web3, private_key='0xbbfbee4961061d506ffbb11dfea64eba16355cbf1d9c29613126ba7fec0aed5d')

blob = "blob"
name = "TestToken"
symbol = "TEST"

from web3.main import Web3
cap = Web3.toWei(1000, "ether")

dtfactory = ocean.get_dtfactory()
transaction_id = dtfactory.createToken(blob, name, symbol, cap, from_wallet=alice_wallet)

from ocean_lib.web3_internal.contract_base import ContractBase
tx_receipt = ContractBase.get_tx_receipt(ocean.web3, transaction_id)

from web3.logs import DISCARD
# logs = dtfactory.events.TokenRegistered().processReceipt(tx_receipt)
logs = dtfactory.events.TokenRegistered().processReceipt(tx_receipt, errors=DISCARD)
```
