### ISSUE TITLE
Error while running the datatokens-flow

### ISSUE THREAD

**Issue by MrAliFar** [oceanprotocol/ocean.py#353]
Running the datatokens-flow code results in an error when running the following line:
`datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet)`

The error is as follows:
`WARNING:root:No logs were found for tx 0xed828d0612b1251a92a7e3e2564c3fc56f895c7e3a6c59cdd9c2759d62979aa8.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ali/barge/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean.py", line 179, in create_data_token
    assert address, "new datatoken has no address"
AssertionError: new datatoken has no address`

I have used the instructions in this link:
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/datatokens-flow.md

**Comment by calina-c** [comment]
Tried with the ocean-lib current version (0.5.26).
The only issues encountered were the ABI Mismatch warnings, but no such error.

I can not reproduce this. Can you give us more details? e.g. ocean-lib version, Python version, OS. Did you create the config file as in the instructions? Is the environment isolated in a folder of its own? Anything helps. Thank you!

**Comment by MrAliFar** [comment]
My OS is Ubuntu 20.04, the Ocean-lib version is 0.5.24, and Python version is 3.8.5. Yes the config file is exactly the same, and the environment folder is isolated.

I noticed that when installing ocean-lib using the command `pip install ocean-lib`, the installed ocean-lib has some inconsistencies with the code in the repository. For instance, the function `mint_fake_OCEAN()` takes a config file as an argument in the example provided here:
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/marketplace-flow.md

But the corresponding function in the installed ocean-lib does not have any arguments.

**Comment by calina-c** [comment]
> My OS is Ubuntu 20.04, the Ocean-lib version is 0.5.24

Yes, it's possible that 0.5.24 was broken and superseded by newer versions, where that issue was corrected. Can you try with the latest ocean-lib version? Or at least with 0.5.25?

**Comment by calina-c** [comment]
@MrAliFar any updates on this? Does it work with a newer version?

**Comment by MrAliFar** [comment]
@calina-c I haven't had a chance to test it with a newer version. I'll come back once I've done it.

**Comment by trentmc** [comment]
> @MrAliFar any updates on this? Does it work with a newer version?

We haven't heard back from you.

I went through the datatokens README from a fresh git clone, and encountered no issues.

Therefore closing this issue for now.

@MrAliFar if you update to the latest version, and still encounter the issue, please reopen this issue. Thank you:)
