### ISSUE TITLE
Revive dynamic type checking

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#37]
Motivation: to help harden ocean.py

We had this in earlier days, using `enforce` library (enforce.py). We'd turned it off due to weird interaction with Brownie. But now we've removed Brownie dependency. So we can revive this. Samer kept a branch that's a snapshot of master before enforce was removed.

And, `enforce` only works up to python3.6. However `enforce_typing` library works for 3.8. So let's use that. To minimize work for ourselves, we can still use the type hints that we'd had in the times of using enforce library. The [tokenspice2 repo](https://github.com/oceanprotocol/tokenspice2) uses it, look there for examples.

Finally, we can use static type checking. Also look to `tokenspice2` for good usage patterns. 

Summary of what to do:
- [x] Start using `enforce_typing` library, and make sure all the existing type hints work fine. 
- [x] Ensure that the util.typecheck config parameter can successfully toggle runtime type checking on and off 
- [x] Add unit test to check that that TYPECHECK is true
- [x] Write a future issue capturing possible next TODOs

**Comment by trentmc** [comment]
Note: even without Brownie, the `enforce` library plays badly with python versions > 3.6. 

However the library `enforce_typing` does work ok. Here's an example of using it, in a PR to replace `enforce`: https://github.com/oceanprotocol/tokenspice2/commit/63f22e33949932cfaeb1e9aa240aae1f93dc4840

**Comment by DMats** [comment]
> Samer kept a branch that's a snapshot of master before enforce was removed.
@ssallam can you point me to where this branch is stored?

**Comment by trentmc** [comment]
Thinking about it, I don't know if it matters to see the old branch. Why: The type hints are all still in the ocean.py code. So you can simply bring in the `enforce_typing` library.

Also worth knowing: `constants.py` has a setup where you can use an envvar to turn on or off type checking.  This is because because type checking can cause code to run 10x slower; so during rapid iterations of development you turn off type checking; then before commit you turn it back on.

**Comment by DMats** [comment]
@trentmc Thanks for the info.  I've updated the issue description with a TODO checkbox regarding the TYPECHECK envvar defined in `constants.py`

Questions: 

1. Should I write unit tests for the runtime type checking?
2. Where should I import `constants.py`? Some options:
    1. At the unit test and system test entry points.
    2. Everywhere that `enforce_typing` is imported.

**Comment by DMats** [comment]
I created a branch https://github.com/oceanprotocol/ocean.py/tree/issue37-enforce-typing and enabled dynamic (runtime) type checking for all classes and functions that contained type hints.

I ran the unit tests and many of them failed. I've listed the test summary below. I'll work on fixing these TypeErrors tomorrow.

```
====================================================================================================== short test summary info ======================================================================================================
FAILED ocean_lib/assets/test/test_asset_downloader.py::test_ocean_assets_download_indexes - TypeError: Expected type 'typing.Union[int, NoneType]' for attribute 'index' but received type '<class 'range'>')
FAILED ocean_lib/assets/test/test_asset_downloader.py::test_ocean_assets_download_destination_file - TypeError: Expected type '<class 'str'>' for attribute 'destination' but received type '<class 'py._path.local.LocalPath'>')
FAILED ocean_lib/ocean/test/test_ocean_assets.py::test_register_asset - Exception: Unable to search for DDO: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Ser...
FAILED ocean_lib/ocean/test/test_ocean_assets.py::test_ocean_assets_search - Exception: Unable to search for DDO: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Interna...
FAILED ocean_lib/ocean/test/test_ocean_exchange.py::test_ocean_exchange - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
FAILED ocean_lib/test/test_config_provider.py::test_metadataCacheUri_version - TypeError: Expected type '<class 'str'>' for attribute 'ocean_token_address' but received type '<class 'NoneType'>')
FAILED ocean_lib/test/test_config_provider.py::test_metadataStoreUri_version - TypeError: Expected type '<class 'str'>' for attribute 'ocean_token_address' but received type '<class 'NoneType'>')
FAILED tests/integration/test_compute_flow.py::test_compute_raw_algo - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
FAILED tests/integration/test_compute_flow.py::test_compute_multi_inputs - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
FAILED tests/integration/test_market_flow.py::test_market_flow[implicit_none] - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
FAILED tests/integration/test_market_flow.py::test_market_flow[explicit_none] - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
FAILED tests/integration/test_market_flow.py::test_payer_market_flow - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_balancer_core_direct_flow.py::test_complete_flow - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_balancer_simple_for_users_flow.py::test_quickstart - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_balancer_simple_for_users_flow.py::test_ocean_balancer_helpers - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bfactory.py::test_bpool_creation - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_notokens_basic - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_setSwapFee_works - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_setSwapFee_fails - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_setController - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_setPublicSwap - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_2tokens_basic - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_unbind - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_finalize - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_public_pool - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_rebind_more_tokens - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_gulp - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_spot_price - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_joinSwapExternAmountIn - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_joinswapPoolAmountOut - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_exitswapPoolAmountIn - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_exitswapExternAmountOut - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcSpotPrice_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcOutGivenIn_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcInGivenOut_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcPoolOutGivenSingleIn_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcSingleInGivenPoolOut_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcSingleOutGivenPoolIn_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_bpool.py::test_calcPoolInGivenSingleOut_base - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_btoken.py::test_ERC20 - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_ERC20 - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_status_functions - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_blob - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_blob_json - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_setMinter - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_transfer_event - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_verify_transfer_tx - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_verify_order_tx - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_datatoken.py::test_download - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_dtfactory.py::test_data_token_creation - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_dtfactory.py::test_data_token_event_registered - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_dtfactory.py::test_get_token_minter - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/models/test/test_fixed_rate_exchange.py::test_fixed_rate_exchange - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
ERROR ocean_lib/web3_internal/test/test_contract_base.py::test_main - TypeError: Expected type '<class 'float'>' for attribute 'amt' but received type '<class 'int'>')
================================================================================== 12 failed, 69 passed, 3 skipped, 42 errors in 117.09s (0:01:57) ==================================================================================
```

**Comment by trentmc** [comment]
> 2. Where should I import constants.py? Some options:
>   i. At the unit test and system test entry points.
>   ii. Everywhere that enforce_typing is imported.

Great Q. Here's the general goal: you want it to be imported before `enforce_typing` is imported in a library to be used, so that can get redefined to `noop` if desired. We only really need it for unit & system tests, it doesn't have to be enforced for users of the library (but it could). 

Therefore:
- (i) could work. You could probably call it just in ./conftest.py, which is currently the first port of entry for all tests. 

- (ii) could work, though that's a lot of import calls, and a pain to maintain (e.g. if functionality is moved from constants.py)

Here are a couple more options.

- (iii) When type checking was first written, `./ocean_lib/config.py` did not exist yet. config.py is really the place where constants are handled now. config.py is always imported early on. So we could move the functionality from constants.py to config.py; you won't need further imports. And we could deprecate constants.py, for better hygiene.

- (iv) Define a small wrapper module e.g. enforce_types2, that inherits all of enforce_types functionality but can be turned on and off in one place. Then make all the files use enforce_types2 not enforce_types.

Analysis: 
- (ii) could work, (iv) improves upon it
- (i) could work, (iii) improves upon it

So it's either (iii) or (iv). Perhaps play with both and see which feels cleanest. Or just pick one! :)

**Comment by trentmc** [comment]
> Should I write unit tests for the runtime type checking?

There are two possible types of tests:
- (a) A test that the type checking system is in fact running during unit tests
- (b) Test content itself that certain variables follow the target types

For (a), we should definitely have at least one test for this, because that will help make _all_ remaining unit & system tests more thorough. Perhaps it simply checks that `TYPECHECK` is True.

For (b), much of this can be implicit. However if there are particularly tricky areas where we need to make sure types are clean, then write explicit tests.

**Comment by trentmc** [comment]
> I ran the unit tests and many of them failed. I've listed the test summary below. I'll work on fixing these TypeErrors tomorrow.

Thanks for the report. This is great to see: recall that part of the aim to revive was to ferret out latent bugs. Looks like we have many. 

>  I'll work on fixing these TypeErrors tomorrow.

Perfect, yes let's clean this up:)

**Comment by DMats** [comment]
I'm skipping these errors because they seem unrelated to this issue. I also verified that they also occur on `main` so they're not caused by the `enforce-typing` changes I've made.

```
FAILED ocean_lib/ocean/test/test_ocean_assets.py::test_register_asset - Exception: Unable to search for DDO: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Ser...
FAILED ocean_lib/ocean/test/test_ocean_assets.py::test_ocean_assets_search - Exception: Unable to search for DDO: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Interna...
```

**Comment by trentmc** [comment]
Makes sense. There are other github issues for those, targeted to address in this sprint.

**Comment by DMats** [comment]
I updated the `issue37-enforce-typing` with the latest from `main` and finished fixing all of the TypeErrors. I'll work on fixing the TYPECHECK toggle tomorrow.

I made an interesting discovery - `enforce_typing` doesn't seem to support class objects - type hints like `data_provider: Type[DataServiceProvider]`. For details, see https://github.com/oceanprotocol/ocean.py/commit/5f4acdde2e3fabe3dda8bcdc502ae992f88108f2

**Comment by DMats** [comment]
I added the TYPECHECK parameter to `config.py` and removed `constants.py`. Then I moved the monkey patch logic that changes `enforce_types()` to a no-op into the `conftest.py::setup_all()` function. However, I'm having trouble making it work properly.  I think the issue is that most of the places that use the `enforce_types` decorator don't actually import `config.py` or `conftest.py` so the monkey patch is not applied. 

So I moved onto creating `enforce_typing2.py` containing the logic shown below.  The problem with this is that the  `enforce_types()` decorator seems to be called before `conftest.py::setup_all()` so the config has not been set yet.

```python
from enforce_typing import enforce_types
from ocean_lib.config_provider import ConfigProvider

def enforce_types(func):
    if not ConfigProvider.get_config()["util"].getboolean("typecheck"):
        return func
    else:
        return enforce_types(func)
```

**Comment by DMats** [comment]
I've iterated on my `enforce_typing2.py` logic and I'm testing using `util.py::to_base_18(amt: float)` because most of the TypeErrors that I fixed earlier in the week were from tests passing `int` instead of `float`. I injected such an error into `test_contract_base.py::test_main`. Here's the command I'm using for testing.

```
pytest ocean_lib/web3_internal/test/test_contract_base.py::test_main
```

Since `conftest.py::setup_all()` uses `ExampleConfig.get_config()`, I've made `enforce_typing2::enforce_types2()` fallback to doing the same. This solved the issue mentioned in my last comment

Unfortunately, I've hit a circular dependency error - `example_config.py` imports `ocean/util.py` which imports `enforce_typing2.py` which imports `example_config.py`

What I've described above is reflected in the latest commits on https://github.com/oceanprotocol/ocean.py/tree/issue37-enforce-typing

*enforce_typing2.py*
```
from enforce_typing import enforce_types
from ocean_lib.config_provider import ConfigProvider
from ocean_lib.example_config import ExampleConfig

def enforce_types2(func):
    config = ConfigProvider.peek_config()
    if config is not None and config["util"].getboolean("typecheck"):
        return func
    elif not ExampleConfig.get_config()["util"].getboolean("typecheck"):
        return func
    else:
        return enforce_types(func)
```

*util.py*
```
from ocean_lib.enforce_typing2 import enforce_types2
...
@enforce_types2
def to_base_18(amt: float) -> int:
    return to_base(amt, 18)
```

**Comment by DMats** [comment]
I was able to get myself unstuck. 

The solution is a combination of options (iii) and (iv) explained by @trentmc in a [previous comment](https://github.com/oceanprotocol/ocean.py/issues/37#issuecomment-804632090). It allows us to toggle type checking using a config parameter in `config.ini`! :tada: It uses a shim instead of the monkey patch logic that was used with the legacy type checker. 

The solution relies on a few conventions:

1. Anywhere a developer would normally decorate with `@enforce_types` they must instead use `@enforce_types_shim`. 
2. The `setup_enforce_typing_shim()` function must be called before importing any module that uses the `enforce_types_shim` decorator.
3. `setup_enforce_typing_shim()` relies on the `CONFIG_FILE` envvar which by default points to `config.ini`. If this file does not exist, the function will fail.

**Comment by trentmc** [comment]
👍

**Comment by DMats** [comment]
Future improvement idea: I saw at least a few instances where type hints were coded into function docstrings, but were not included in the actual function signatures. It would be good to add these type hints to the function signatures.
