### ISSUE TITLE
Fuzz tests

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#38]
Motivation: to help harden ocean.py

**Comment by kremalicious** [comment]
what does this mean? What should be done here? There's not even 70% coverage in the existing unit tests right now so what exactly is the goal of those so far undescribed tests?

**Comment by trentmc** [comment]
We already have several github issues to fix tests for code coverage.

Fuzz tests aren't going to be that beneficial. 

Therefore this issue isn't going to happen.
