### ISSUE TITLE
BSC support in ocean.py

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#388]
Update ocean.py to support BSC(chainId, networkName)

**Comment by DMats** [comment]
Update the following structs to include BSC.

* util.py::SUPPORTED_NETWORK_NAME
* constants.py::NETWORK_NAME_MAP
* constants.py::NETWORK_TIMEOUT_MAP

No need to do a full marketplace flow test on BSC. Instead, it's sufficient to just lookup an account balance.

**Comment by mariacarmina** [comment]
@DMats, I searched for NETWORK_TIMEOUT_MAP in ocean.py and it doesn't exits. It only provides `SUPPORTED_NETWORK_NAME` and `NETWORK_NAME_MAP`.

**Comment by DMats** [comment]
@mariacarmina my mistake. The timeout map will be added in issue #227 (PR #309)
