### ISSUE TITLE
Eliminate unnecessary properties

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#400]
Python properties allow for the creation of complex setters and getters.  But if no setter is defined, and the getter simply returns the similarly named instance variable, then the property is unnecessary and bloats the codebase.

This issue is to eliminate properties that look like this:

```python
    @property
    def service_endpoint(self) -> str:
        return self._service_endpoint
AND
    @service_endpoint.setter
    def service_endpoint(self, service_endpoint: str) -> None:
        self._service_endpoint = service_endpoint
OR
    def set_service_endpoint(self, service_endpoint: str) -> None:
        self._service_endpoint = service_endpoint
```

The above snippets is the equivalent of a simple `service_endpoint` instance variable.

```python
    def __init__(self, service_endpoint: str):
        self.service_endpoint = service_endpoint
```

**Comment by calina-c** [comment]
I second this.

**Comment by DMats** [comment]
It occurred to me that property setters might allow for type enforcement when altering attributes, so I decided to test it.  Conclusion: `@enforce_types` doesn't work on setters so type enforcement is **not** a reason to keep using properties.

test.py
```python
@enforce_types
class GetterAndSetter:

    def __init__(self, prop: str) -> None:
        self._prop = prop

    @property
    def prop(self) -> str:
        return self._prop

    @prop.setter
    def prop(self, prop: str) -> None:
        self._prop = prop
```

python console
```pycon
>>> from test import GetterAndSetter
>>> getter_and_setter = GetterAndSetter("hello")
>>> getter_and_setter.prop = 1  # This line would have thrown a TypeError
>>> getter_and_setter.prop
1
```
