### ISSUE TITLE
Compute flow example: impossible block of code

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.py#420]
In the compute flow example in step 5. after getting the price of datatoken, code then tries to get this price converted into fiat by getting the USD value of OCEAN from one specific pool: https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/compute-flow.md#5-marketplace-posts-asset-for-sale-using-price-obtained-from-balancer-pool

But that pool does not exist on either network, there simply is no OCEAN-USD(sic!) pool anywhere, creating some confusion. 

At same time, using one DEX pool to get a price for a token is not reliable at all and I see 3 different solutions to this instead:
- use [ChainLink price feeds](https://docs.chain.link/docs/using-chainlink-reference-contracts/)
- use CoinGecko API, like [the `market` does](https://github.com/oceanprotocol/market/blob/main/src/providers/Prices.tsx)
- just remove that block of code as converting to fiat might be out of scope of that simple example

And while we're at it, maybe remove this line at beginning:

> Note: this README is out of date and will not work. Here's the issue to fix it.

**Comment by trentmc** [comment]
This file is obsolete, as it states at the top. We'd only kept it around to make it easier for reviving C2D. But given that it's _still_ causing confusion, it should be deleted. So I created #446 for that. And completed the issue, ie deleted the file.

Therefore this issue also goes away too.
