### ISSUE TITLE
For an address: published assets, pools, fixed-rate exchanges

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#45]
- [ ] published assets for an address
- [ ] list of pools (list of assets that you have provided liquidity)
- [ ] list of FixedRateExchanges

**Comment by trentmc** [comment]
This was already in the "long term" section. But it's sufficiently low priority it's not going to get done anytime soon. If users really want this, we will hear about it.

(Reopen if you feel otherwise:)
