### ISSUE TITLE
Compare features list ocean.py-ocean.js

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#450]

**Comment by trentmc** [comment]
Some guidance.

We should not expect ocean.js and ocean.py to be the same.

1. They should support the same base flows as (a) drivers for the solidity code, and (b) with datatokens + marketplace quickstarts.
2. Beyond that, we should expect them to varu significantly. Here's why. >90% of data science is in python, <0.1% is in JS. Accordingly, ocean.py will support for fancier flows like C2D README doing data science or visualization. You'd never see such a flow for ocean.js.

As a baseline in V4, we want to ensure that (1) is met. Beyond that, it would be worth explicitly documenting what each does, and doesn't do, and if there is a difference decide what changes to make (if any - ref 2).
