### ISSUE TITLE
Secure C2D Outputs

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#457]
Right now, the result of a C2D data (outputs/algo logs) are sent as a URL to the consumer.
Which means that anyone who has those URL has access to them, even if he/she is not the actual consumer.

Proposal:

- GET /compute    (get job results) hides the urls, exposing only an array of output file names, size & type
```json
[
  {
    "agreementId": "0x111111",
    "algoDID": "did:op:87bdaabb33354d2eb014af5091c604fb4b0f67dc6cca4d18a96547bffdc27bcf",
    "dateCreated": 1629281470.08931,
    "dateFinished": 1629281491.05138,
    "inputDID": [
      "did:op:1384941e6f0b46299b6e515723df3d8e8e5d1fb175554467a1cb7bc613f5c72e"
    ],
    "jobId": "6951125396154f2da719f097ae758bb5",
    "owner": "0xC41808BBef371AD5CFc76466dDF9dEe228d2BdAA",
    "removed": 0,
    "results": [
      {
        "filename": "output.log",
        "filesize": 85,
        "type": "output"
      },
      {
        "filename": "algorithm.log",
        "filesize": 127,
        "type": "algorithmLog"
      }
    ],
    "status": 70,
    "statusText": "Job finished",
    "stopreq": 0
  }
]
```

Provider exposes new endpoint:   GET /computeResult, which retrieves an output from a job (index based)
```
parameters:
      - name: consumerAddress
        in: query
        description: The consumer address.
        required: true
        type: string
      - name: jobId
        in: query
        description: JobId
        required: true
        type: string
      - name: index
        in: query
        description: Result index
        required: true
      - name: signature
        in: query
        description: Signature of (jobId+index+consumerAddress+nonce) to verify that the consumer has rights to download the result
    """
(see https://github.com/oceanprotocol/provider/pull/201)


Ocean.py should use that endpoint

**Comment by alexcos20** [comment]
for reference:  https://github.com/oceanprotocol/ocean.js/pull/983

**Comment by calina-c** [comment]
I have succeeded in making this work, I get a binary response. However it is a draft since:
- I am confused about the naming, our previous function was already called results
- I suppose the binary content of the file is what I should be getting, but I am not entirely sure.
- It doesn't work with the barge version of provider, only with a local provider spun up by me from the secure c2d branch. So I probably configured Barge wrong.

So this is an intermediary form I need to discuss with Alex, when he's back from vacation.

**Comment by calina-c** [comment]
Intermediary form fixed, waiting for review.
