### ISSUE TITLE
Refactor or remove OceanCompute and DataServiceProvider

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#471]
Everytime we make a change in Provider, we are forced to break the ocean.py interface by adding parameters to the data_service_provider.py functions. The state of the OceanCompute and DataServiceProvider classes has snowballed and is far more cumbersome than it should be. Instead of letting the snowball role, we have to take some actions. During a call with Trent and Maria, we explored several options:

- the lists of partameters could be replaced with a dict or object that is self-validating and self-formatting. Adding new parameters will only affect that object's structure, and not the ocean.py interface itself
- separating OceanCompute and/or DataServiceProvider into a different utilitary repo, dealing with API calling only
- removing OceanCompute and/or DataServiceProvider altogether, asking users to use the REST APIs directly.

@alexcos20 how elaborate is the ocean.js analogous code? What are your thoughts on this?
Keeping this ticket open for opinions and discussions. After we fully define it, I can start working on it :)

**Comment by calina-c** [comment]
@trentmc @mariacarmina I have discussed this with Alex and his recommendation is we keep both classes, and work on the smart input objects.

@AnaLoznianu perhaps this can be integrated into the current sprint if nothing else arises.

**Comment by trentmc** [comment]
Python to do x
   ||
REST to do x
   ||
Python to do x

Why?

**Comment by calina-c** [comment]
Closing this as treated in v4. There were still useful features there, and with the parameters reorganised in both provider and the two classes, this point is now moot.
