### ISSUE TITLE
ADDRESS_FILE not provided in READMEs when using ExampleConfig & update the private keys in the ocean.py codebase

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#476]
1. `ADDRESS_FILE` is not provided in READMEs. Where the `ExampleConfig` is used, needs to have in the env, `ADDRESS_FILE`
2. Update the private keys in the ocean.py codebase

**Comment by mariacarmina** [comment]
I have tested again with the same private keys from the README and as far as I saw they have sufficient balance, but it fails on `create_data_token`.
![Screenshot from 2021-09-07 10-52-48.png](https://images.zenhubusercontent.com/5ff442e8d03d4b2d4051265f/e3b9fb1f-4b0b-4a8d-a1d3-fc918a2a3db1)

**Comment by mariacarmina** [comment]
I wanted to see the `tx_receipt` and different fields. Apparently, neither `TokenCreated` and neither `TokenRegistered` were emitted. 
BTW, I used `getLogs` to get the stateless logs
![image.png](https://images.zenhubusercontent.com/5ff442e8d03d4b2d4051265f/d097ff6b-d161-4980-9c9c-bcdc5b88cf97)
![image.png](https://images.zenhubusercontent.com/5ff442e8d03d4b2d4051265f/cb8cb65f-656f-4251-a4e2-acc75bc83100)

**Comment by mariacarmina** [comment]
**EDIT3**: The fix when testing on `ganache` network is to `mint_fake_OCEAN` before, but when I tried reproducing the marketplace-flow README, another error occurred from the contract. I attempt to investigate further.
![Screenshot from 2021-09-08 16-17-19.png](https://images.zenhubusercontent.com/5ff442e8d03d4b2d4051265f/37df9717-330b-4f33-b6bd-09946c37807d)

**Comment by trentmc** [comment]
It might be related to `mint_fake_ocean`. 

However if Alice doesn't even have ETH to begin with, then your problem is happening before that.

In my quick testing, I found that Alice didn't even have ETH to begin with.

**Comment by mariacarmina** [comment]
So, `mint_fake_OCEAN` transfers ether in those accounts if they have sufficient balance, the exception that I receive when I call `mint_fake_OCEAN` is from the contract: `web3.exceptions.BadFunctionCallOutput: could not transact with/call contract function, is contract deployed correctly and chain synced?` when I call `balanceOf` from `DataToken` contract.

**Comment by trentmc** [comment]
The error you get means that it can't see the ABIs. Perhaps looking at the wrong addresses? Or even the wrong chain uri?

**Comment by mariacarmina** [comment]
I saw other comments mostly regarding the ABIs problem.

**Comment by mariacarmina** [comment]
I have read this [thread](https://github.com/ethereum/web3.py/issues/185) from GitHub and seems they are facing the same issue. Maybe is there a problem with the contract code?

**Comment by trentmc** [comment]
You don't need to create another issue. Just keep hunting down on this one to the root of this problem.

**Comment by mariacarmina** [comment]
Sure @trentmc.

**Comment by alexcos20** [comment]
1. where did you get TEST_PRIVATE_KEY ?
ganache has a mnemonic (https://github.com/oceanprotocol/barge/blob/main/start_ocean.sh#L52) and if you use https://iancoleman.io/bip39/ with that mnemonic, you will NOT find address 0x66a in the list of addresses with ETH balance

2. ocean-contracts.   Where run by barge, it will call https://github.com/oceanprotocol/contracts/blob/main/scripts/deploy_docker.sh , which at the end will deploy a DataTokenTemplate with a cap of 100000 as 'fakeOcean'. The owner of the token is the first account from barge (0xe2DD09d719Da89e5a3D0F2549c7E24566e947260). also, that's the only address that can mint and transfer at the begining

**Comment by mariacarmina** [comment]
Ok, thank you for the info, I will try with different private key then. the address that begins with 0x66a is from marketplace-flow README.

**Comment by alexcos20** [comment]
problem solved, you should always specify address.json path using ENV  (https://github.com/oceanprotocol/ocean.py/blob/main/tox.ini#L17)

**Comment by mariacarmina** [comment]
Based on the discussion with @alexcos20, I noticed that in some of the READMEs the `ARTIFACT_PATH` isn't provided so the contract addresses from my venv were mismatched. This is the root of this problem.
