### ISSUE TITLE
Kill Travis

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.py#481]
For some time Travis is no fun anymore since they were bought by some VC-backed company, neglecting their core product in the process. This is just the latest reason for concern, there were many more before that: https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

Just with other repos this repo here should use GitHub Actions for its CI alone and migrate away from Travis. Because of above linked flaw, all env vars used in this repo for CI should be considered compromised and need to be rotated.

**Comment by alexcos20** [comment]
all tokens were deleted from pypi

**Comment by calina-c** [comment]
Done, but due to a mixup I also added the new aquarius version in the same branch, so now we're waiting on the barge components to be bumped. In the meantime, we have Travis.
