### ISSUE TITLE
Publish flow

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#489]
- [ ] add functional tests

**Comment by DMats** [comment]
I attempted running the `tests/integration/test_publish_flow.py::test_publish_flow` integration test on the `publish-flow` branch. Aquarius logs the following error. The error occurs when aquarius calls the `nonce` endpoint in provide and receives a `Connection refused` response.

```
aquarius_1         | 2021-12-15 22:41:52,148 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: HTTPConnectionPool(host='localhost', port=8030): Max retries exceeded with url: /api/services/nonce?userAddress=0xF41681F0BE4A914d447d7A94C91906E74A6561D0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10b8bffc40>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by DMats** [comment]
Now that https://github.com/oceanprotocol/aquarius/pull/647 is merged, the issue with the `nonce` endpoint appears to be resolved but a new error occurs: The `decrypt` endpoint responds with `Connection refused`.

```
aquarius_1         | 2021-12-17 00:07:07,603 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: HTTPConnectionPool(host='localhost', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe648eb4280>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by DMats** [comment]
Since https://github.com/oceanprotocol/ocean.py/pull/604 is merged, I'm closing this issue.
