### ISSUE TITLE
Consume flow

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#490]

**Comment by calina-c** [comment]
As part of the consume flow, please reinstate the following things missing in v4:
- the OceanAssets download function and its usages https://github.com/oceanprotocol/ocean.py/blob/e914696b126e2a4304752ca4bd4c9b32380936c2/ocean_lib/ocean/ocean_assets.py#L515
- unskip and adapt the test `test_download_fails` in test_ocean_assets.py. Hopefully by that point this PR: https://github.com/oceanprotocol/ocean.py/pull/627 will be merged
- adapt and fix tests in `ocean_lib/assets/asset_downloader.py` which are now TODO.

CC @mariacarmina
