### ISSUE TITLE
Update marketplace-flow README to use ExampleConfig

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#502]
**Solution**
Update marketplace-flow README to use ExampleConfig.

**Problem**
Ganache does not have auto-mining and wait_for_transaction_receipt_and_block_confirmations loops to infinity. It was discovered testing the marketplace-flow README using `mint_fake_ocean` function which sends ether and waits for block confirmations as well.

**Comment by DMats** [comment]
I disagree with the proposed design.

While a daemon that sends dummy transactions would probably alleviate the issue, it is far easier to set the `block_confirmations` option to 0 when testing with Ganache. We can encourage this by updating all the READMEs to get their `Config` from the `ExampleConfig`. When `ExampleConfig` detects that the user is connected to Ganache, it will set the `block_confirmations` option to 0.

I'm also open to discussion for setting the default `block_confirmations` value to 0; Currently, it is 1. This value applies when the user doesn't use `ExampleConfig` and doesn't specify a `block_confirmations` value anywhere (neither in config.ini nor `BLOCK_CONFIRMATIONS` env var). I think that `block_confirmations=1` is a sensible 

CC @mariacarmina @trentmc @calina-c

**Comment by trentmc** [comment]
I'm ok with David's simpler design

**Comment by mariacarmina** [comment]
I agree with setting in example config the `block_confirmations`. If a user wants to modify the `block_confirmations` from the "default" 0 value to 5 for example, how do we handle the infinity loop then? I am asking this because marketplace-flow README uses a config.ini file, not a `OCEAN_NETWORK_URL` envvar to get the config object directly from `ExampleConfig` class. Should we specify in the config.ini file that the `block_confirmations` is 0 for ganache?

**Comment by DMats** [comment]
>I am asking this because marketplace-flow README uses a config.ini file, not a OCEAN_NETWORK_URL envvar to get the config object directly from ExampleConfig class. 

I believe we should change the marketplace-flow README (along with all other READMEs) to use `OCEAN_NETWORK_URL=<whatever the ganache RPC is> and `ExampleConfig.get_config()`.

**Comment by mariacarmina** [comment]
Just as we have for FRE flow and dispenser flow, right?

**Comment by DMats** [comment]
@mariacarmina 
The FRE flow appears to be correct and would serve as a good model to base your work on.

The dispenser flow appears to be missing the OCEAN_NETWORK_URL, so I'm suspicious of whether the `ExampleConfig.get_config()` call actually works.

**Comment by mariacarmina** [comment]
I will update the dispenser flow as well. Thanks.
