### ISSUE TITLE
Upgrade web3.py to latest stable version, continue using legacy transactions

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#521]
This issue is to upgrade web3.py to the latest version, v0.24.0 at the time of this writing. 

EIP-1559 support was added in web3.py v0.21.0 and changes the way gas price is specified.  ocean.py will need to be updated to accommodate the new EIP-1559 transaction format.

--
EDIT: 
Upgrading to use EIP-1559 transactions is blocked by oceanprotocol/barge#277.

So we have decided to reduce the scope of this issue to simply update to the latest stable Web3.py but continue using legacy transactions.

- [x] v3 (target `main` branch, #611)
- [x] v4 (target `v4main` branch, #610)

**Comment by calina-c** [comment]
here is the commit from aquarius, for reference https://github.com/oceanprotocol/aquarius/pull/639/commits/d2ba878baa814f4a2c1eef002cd9fb4d9db55e97

**Comment by DMats** [comment]
Upgrading to use EIP-1559 transactions is blocked by oceanprotocol/barge#277.

So we have decided to reduce the scope of this issue to simply update to the latest stable Web3.py but continue using legacy transactions.
