### ISSUE TITLE
A lot of services code is stale, obsolete, poorly handled

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#526]
**Motivation**

Stale aspects in services, service descriptors etc., which are leftovers since v1 and are either obsolete or poorly used/handled. Calina discovered some of these during the removal of ocean-lib from provider.

**Example TODOs**

Note: PR #524 was created before the ticket. This section simply copies PR description to here. Treat the PR as the source of truth.

- remove OceanServices, since it was unused
- remove ServiceDescriptors: they were tuples of service name, service dict of attributes and endpoint. We can use Service seamlessly, i.e. service.type, service.attributes and service.service_endpoint -> use Service class instead of ServiceDescriptor class where appropriate
- remove ServiceAgreeement: the overriding of things in Service is now seamlessly integrated (default indices in place), there is no reason to have two classes that do the same thing
- remove code duplication in service creation
- remove ServiceAgreeement.from_ddo functionality since it does the same thing as Asset.get_service
- remove ServiceFactory, whose only purpose was to convert ServiceDescriptors into Services. Now Services are used directly, so there is no need for conversion.
- remove authorization service, which was obsolete. I kept the default index in place not to disturb the convention, but there is no more authorization service put in assets.

**Comment by calina-c** [comment]
Closed by #524.
