### ISSUE TITLE
Do we need to add another base token different from OCEAN token?

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#533]
I got a question after some fixed-rate-exchange README refactors if we can create an exchange and buy data tokens using another base token address different from the OCEAN one. Do we need this right now in ocean.py?

**Comment by mariacarmina** [comment]
Agreed, it's considered as low prio task for the moment. Then #532 can be merged after a review.

**Comment by calina-c** [comment]
This is done in v4 and any base token can be used. @trentmc do you want us to add to the FRE readme explaining that?

**Comment by mariacarmina** [comment]
I could add in the READMEs extra info regarding this aspect.
