### ISSUE TITLE
Update c2d-flow.md

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/ocean.py#597]
**Describe the bug**
When I try to run c2d example I am getting error in the [4th step](https://github.com/oceanprotocol/ocean.py/blob/11c361d10d013f8ef9531ab5a7406d250a8c8957/READMEs/c2d-flow.md?plain=1#L259):

![image](https://user-images.githubusercontent.com/16358982/144229266-b5686d67-0ab4-4ce3-9654-55b288f91100.png)

**To Reproduce**
1. Go to [c2d-flow.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md)
2. Follow the steps till 4th step i.e [4. Alice allows the algorithm for C2D for that data asset](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md#4-alice-allows-the-algorithm-for-c2d-for-that-data-asset)

**Expected behavior**
No error

**Screenshots**
Already provided.

**Fix**

Update [4th step](https://github.com/oceanprotocol/ocean.py/blob/11c361d10d013f8ef9531ab5a7406d250a8c8957/READMEs/c2d-flow.md?plain=1#L259) as follows:

```python

from ocean_lib.assets.trusted_algorithms import add_publisher_trusted_algorithm
add_publisher_trusted_algorithm(DATA_ddo, ALG_ddo.did, config.metadata_cache_uri)
ocean.assets.update(DATA_ddo, publisher_wallet=alice_wallet)

```

**Comment by anirbancdev** [comment]
![Screenshot From 2024-11-27 10-53-01](https://github.com/user-attachments/assets/46d79045-7d8b-425c-8af1-da23d5dda7cc)
I am getting this error using the proposed solution in https://github.com/oceanprotocol/ocean.py/issues/597#issue-1068313708
