### ISSUE TITLE
Unable to retreive compute result in C2D flow

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/ocean.py#602]
**Describe the bug**
Using ocean.py 0.8.5

![image](https://user-images.githubusercontent.com/16358982/144418679-19844ba7-0eca-4011-9bf0-85a3722ccabf.png)

Above error appears in last step in [C2D-flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md).

**To Reproduce**
1. Go to https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md
2. Follow all the steps. 
3. See error at last step.

**Expected behavior**
No error

**Screenshots**
Already provided

**Other References**
- https://github.com/akshay-ap/ocean.py-playground/blob/main/5.C2D.ipynb
- https://github.com/AlgoveraAI/generative-art/blob/main/notebooks/3-C2D-flow-ocean.ipynb

**Comment by maldo-ctrl** [comment]
As described here: https://oceanprotocol.slack.com/archives/C01PJ00QE2V/p1638791410261800

Summary: 

This problem occurs in the test environments (using the stable operator environment: https://nextv.operator.oceanprotocol.com//api/v1/operator/getResult ) but not locally with barge. This problem will be solved once we deploy the latest cluster of C2D in the production environment but before this issue needs to be fixed: https://github.com/oceanprotocol/market/issues/853

Explanation:
The `ocean.compute.result_file(DATA_did, job_id, 0, bob_wallet)` is implicitly calling through `provider` the operator service enpoint `get_config().operator_service_url + "/api/v1/operator/getResult"` and `getResult` is only deployed in https://c2d-dev.operator.oceanprotocol.com//api/v1/operator/getResult  (https://github.com/oceanprotocol/provider/blob/main/tox.ini#L18)

Before the operator updates are merged to the production environment, this issue needs to be solved: https://github.com/oceanprotocol/market/issues/853

**Comment by akshay-ap** [comment]
@maldo-ctrl thanks for the update. We have our own operator service defined here which is giving the error: https://gpu01.dataunion.app/

May I know what version of operator service should be used to fix this error?
