### ISSUE TITLE
"C2D Flow" README works in v4

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#624]
The v4 version of this flow
https://github.com/oceanprotocol/ocean.py#compute-to-data-flow

should run end-to-end without errors.

This means updating the README, and if needed, underlying components.

- [x] Fix c2d README
- [x] Add integration test that mirrors the c2d README
- [x] Reinstate the skipped integration test `test_c2d_flow_readme` after c2d backend updated to support v4

**Comment by DMats** [comment]
Retrieving the final algorithm output is blocked until the c2d backend supports v4, so the newly added `test_c2d_flow_readme` integration test is skipped, and another PR is required to reinstate it.
