### ISSUE TITLE
Reinstate OceanExchange tests and properties in Ocean

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#647]
Currrently in ocean.py we commented those functionalities out in order to focus on the other tasks. But we need to reinstate them and adapt for v4 at some point.

- Ocean class must have the exchange properties, now commented out
- unskip tests for test_ocean_exchange

**Comment by calina-c** [comment]
@AnaLoznianu discussing with Alex, now there is no standard Ocean pool and Ocean exchange. OCEAN is just a particular case of a base token for pools, just a regular ERC20. For the purposes of Ocean Pool, we offer a utilitary inside the Ocean class to create this pool, and all operations are supported inside BPool directly.

- The former OceanPool/OceanExchange classes were bloated and overconfigured
- they were tying down users to using a specific syntax for pools with an OCEAN side, while using another syntax for "generic" BPools. -> meaning more points of failure and difficulty when updating the code
- the benefits were limited to trivialities such as abstracting the part where we retrieve the OCEAN token/address, but that is well supported in the Ocean class (ocean/ocean.py), so it's not very useful.

That being said, I think there is reason to consider these issues (#647 and #632) moot.
#632 is already handled as a pool creation utility function as part of the marketplace flow (#650, merged)
and #647 will folllow the same principles, and it is a WIP as part of issue #649.

CC: @AnaLoznianu @trentmc @alexcos20 if you have any objections, let's discuss.
