### ISSUE TITLE
Replace "data token" -> "datatoken" etc, everywhere

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#651]
**Is your feature request related to a problem? Please describe.**

It's not "data token". There is no space,  it's "datatoken"; It's a single word; there are several reasons for this. 

v3 wasn't filly consistent this way. Let's take the opportunity to make v4 consistent, before we ship the first version.

**Describe the solution you'd like**
Everywhere in ocean.py, replace:
- "data token" -> "datatoken"
- "data_token" -> "datatoken"
- "dataToken" -> "datatoken"
- "DataToken" -> "Datatoken"
- "Data Token" -> "Datatoken"
- etc

**Additional context**
A "datatoken" is the ERC20 fungible token. Complementary to it is the "Data NFT", an ERC721 non-fungible token. "Data NFT" _does_ have a space.

Related issues: [ocean contracts](https://github.com/oceanprotocol/contracts/issues/450), [ocean.js](https://github.com/oceanprotocol/ocean.js/issues/1217)

**Comment by calina-c** [comment]
A draft PR is done, but we need to have contracts updated before we move forward.
