### ISSUE TITLE
Replace web3.toWei with to_wei utility

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#662]
It seems in some places we are using to_wei utility, while in others we use the web3 one. Replace web3.toWei with to_wei utility for consistency. See [comment](https://github.com/oceanprotocol/ocean.py/pull/659#discussion_r786496854)

**Comment by AnaLoznianu** [comment]
Add it to the Ocean class and use like ocean.to_wei everywhere
