### ISSUE TITLE
Large DRY violations in quickstart READMEs

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#687]
**Summary**

We have page after page of repeated code, at the beginning of each README. This is going to be a maintenance nightmare. We've got to fix this.

**Background**

- DRY = Don't Repeat Yourself.
- Large DRY violation = big copy-and-paste of code, which is a 
problem because you have to maintain all of them. The ideal to aim for is "never have duplicates".

In the beginning of V3, we had 2 quickstart READMEs (simple flow, marketplace flow). They partly differed in which components needed installing. So for user simplicity, we made each of those quickstart READMEs be self-contained, even if there was slight overlap. Only a small DRY violation. It was maintainable because it was just two READMEs.

Then the C2D README got added. It also had slightly different component needs, so we let it be self-contained. Small DRY violation. It made things slightly harder to maintain, but not a huge problem.

But now in V4, we have three more quickstart-like READMEs, [see here](https://github.com/oceanprotocol/ocean.py/tree/v4main/READMEs): 
- dispenser-flow.md
- fixed-rate-exchange-flow.md
- get-test-ocean.md

In addition to the prior ones:
- datatokens-flow.md
- marketplace-flow.md
- c2d-flow.md

All of these READMEs are repeating the following sections - about a page of code at the top of each README :
- "Prerequisites" section (3 lines)
- "Run barge services"  (7 lines)
- "Install the library" section" (6 lines)

Also, all the READMEs have:
- "Set envvars" a bit, but several differences here (10 lines)

And, some of these READMEs have:
- "Alice publishes data asset" (or very similar) (35 lines)

Maintaining this is going to be a nightmare. More likely, it won't be well maintained, then we will be living with buggy READMEs that are always half-broken. Therefore we need to do this as part of V4, to maximize the chance of all ocean.py READMEs working in V4.

**TODOs**

Solve this, according to the goals:
- It's not a maintenance nightmare
- It's still a nice UX for users going through

Proposed approach: 
- The simplest quickstart (datatokens-flow.md) stays unchanged
- In other quickstarts:
  - At the very top, ask the user to go through the simplest quickstart first" and link to it. (datatokens-flow.md)
  - Deprecate: "pre-requisites", "run barge", "install library" sections 
  - Where possible, deprecate "envvars" section. 
  - Where possible, deprecate "publish data asset" section

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/687?planning-poker) with ZenHub @md0x
