### ISSUE TITLE
Functions & variables renaming to conform to the nomenclature

### ISSUE THREAD

**Issue by md0x** [oceanprotocol/ocean.py#700]
As described here: https://github.com/oceanprotocol/ocean.py/pull/697#discussion_r79791971 we need some renaming  to align with our terminology :

- `create_nft_token() ` -->  `create_data_nft()`
- `erc721_token` -->  `erc721_nft`
- `nft_token` -->  `erc721_nft`

**Comment by trentmc** [comment]
I'm really happy to see this all. Here's the current spec:

```
0. create_nft_token() --> create_data_nft()
1. erc721_token --> erc721_nft
2. nft_token --> erc721_nft
3. erc721_token.py --> erc721_nft.py
4. ERC721Token --> ERC721NFT
```

I just realized: to make naming even more consistent, we could update (0) to:
```0. create_nft_token() --> create_erc721_nft()```
