### ISSUE TITLE
Too many calls for resolve asset in OceanCompute

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#703]
Currently, in #683, in OceanCompute class, there are multiple calls for resolving the asset which can be avoided.
See the [discussion](https://github.com/oceanprotocol/ocean.py/pull/683#discussion_r793898923)

**Comment by DMats** [comment]
The proposed fix is to change the `OceanCompute` API convention:  Instead of taking `did` argument (and then resolving it from aquarius), take `Asset` argument (assume user already has the `Asset`)
