### ISSUE TITLE
Update image processing c2d example to v4, and bring into ocean.py repo

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#705]
Currently, the c2d readme mentions two external resources for learning to use other algorithms with Compute-to-data.

```markdown
TODO: Update these examples based on v4
1. simple image processing at [ocean-lena](https://github.com/calina-c/ocean-lena/blob/main/c2d-flow.md)
2. logistic regression for classification [blog post](https://medium.com/ravenprotocol/machine-learning-series-using-logistic-regression-for-classification-in-oceans-compute-to-data-18df49b6b165) with both GUI and CLI flows.
```

This issue is to either:

1. Update these examples to v4 and bring them into the ocean.py repo as new READMEs
2. Remove them

**Comment by trentmc** [comment]
Option 3: don't change them, keep them listed, and mention these are still v3 and would need some adapting for v4. Pros: let people see other examples, without having to do more v4 stuff now. In the future we could update them.

**Comment by trentmc** [comment]
Tbh I think it's best if we do (1), when all the c2d stuff is fresh, and use the same DRY-preserving patterns as the other READMEs.
