### ISSUE TITLE
"create_nft_with_erc" and similar labels are nonsensical

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#707]
**Background / Motivation**

"ERC" refers to one of many possible Ethereum proposals, it could be ERC721 (nft), ERC20 (fungible token), ERC725 (identity/metadata), ERC1155, and literally thousands more.

"ERC" without a number means the whole group of Ethereum proposals.

`erc721_factory` includes the following methods:
- `create_nft_with_erc` 
- `create_nft_erc_with_pool`
- `create_nft_erc_with_fixed_rate` 
- `create_nft_erc_with_dispenser` 

These labels don't make any sense, because there's no number beside the "erc". I'm marking this as a bug because it is also nonsensical in the DX: developers will have no idea what "erc" refers to here.

**Prerequisite:**
- [contracts#485](https://github.com/oceanprotocol/contracts/issues/485): "createNftWithErc" and similar labels are nonsensical

**TODO for this issue:** 
- [ ] fix the labels above by putting a number beside them
- [ ] identify any other places in ocean.py (or other py) that has "erc" without a number, and put a number beside them too

Related issues:
- [ocean.js#1251](https://github.com/oceanprotocol/ocean.js/issues/1251) - like this one, but for js

**Comment by trentmc** [comment]
cc @mariacarmina

**Comment by trentmc** [comment]
From @mariacarmina in #693:

> I wanted to match the contract names for these functions, but replace with underscore. Check here as well
> https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/ERC721Factory.sol#L607.

**Comment by trentmc** [comment]
> From @mariacarmina in #693:
> > I wanted to match the contract names for these functions, but replace with underscore. Check here as well
> > https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/ERC721Factory.sol#L607.

Alright, I have now created an issue in ocean contracts repo for that, and made it a prerequisite here. In this issue's description:

> ocean [contracts #485](https://github.com/oceanprotocol/contracts/issues/485): "createNftWithErc" and similar labels are nonsensical

**Comment by mariacarmina** [comment]
Updated in #713

**Comment by mariacarmina** [comment]
Close this because #713 is merged.
