### ISSUE TITLE
V4 DX: common methods have clumsy argument structure

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#725]
**Background**

Here's an example from the [V4 datatokens README](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/datatokens-flow.md):
```python
# Create ERC20 token related to the above NFT.
erc20_data = CreateErc20Data(
    template_index=1, # default value
    strings=["ERC20DT1", "ERC20DT1Symbol"], # name & symbol for ERC20 token
    addresses=[
        alice_wallet.address, # minter address
        alice_wallet.address, # fee manager for this ERC20 token
        alice_wallet.address, # publishing Market Address
        ZERO_ADDRESS, # publishing Market Fee Token
    ],
    uints=[cap, 0],
    bytess=[b""]
)
nft_factory = ocean.get_nft_factory()
erc20_token = erc721_nft.create_datatoken(erc20_data=erc20_data, from_wallet=alice_wallet)
```

Compare this to [V3 datatokens README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/datatokens-flow.md):
```python
datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet)
```

**Solution**

Make it support the following. Note how it doesn't fill in all the values; for ones not given it uses defaults. 

```python
erc20_token = erc721_nft.create_datatoken(
  name="DT1", symbol="DT1", cap=ocean.to_wei(100), from_wallet=alice_wallet)
```

Where to do this: 
- Any method that uses lists of parameters (because EVM workaround). Includes: any methods like this in the READMEs, including the "with_erc20" versions like `create_nft_with_erc20()`. 
- Note: ocean.js already does this! [Example for create erc20](https://github.com/oceanprotocol/ocean.js/blob/v4main/src/tokens/NFT.ts#L111)

----

NOTE: Brownie won't work. Brownie does a 1:1 mapping from smart contract interface. But the smart contract interface _itself_ is terrible, and can't be fixed because EVM only allows 4-5 arguments.

**Comment by trentmc** [comment]
cc @calina-c

**Comment by mariacarmina** [comment]
Discussed with @AnaLoznianu, I will take this task.

**Comment by trentmc** [comment]
@mariacarmina heads up - we can't use Brownie. I've updated the issue title & description with more info. cc @AnaLoznianu

**Comment by mariacarmina** [comment]
Thank you for updates.
