### ISSUE TITLE
Are v4 fees thoroughly tested? If no, do it 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#744]
**Is your feature request related to a problem? Please describe.**

V4 fees are considerably more complex than v3.
 
- so that marketplaces etc have more opportunities to earn, and more flexibility in setting fees. 
- Plus there can now be third party providers,

This is important to get right so that the community can monetize - we need to make sure that we have tested in thoroughly. It can and should be tested in contracts; but since these also affect data science flows, we should also have thorough testing in ocean.py.

I'm pretty sure that the fees are not well tested yet, especially not in ocean.py. Why: there was churn in fees in the last few weeks, yet I saw no signs of any updates to ocean.py to reflect this. And from what I gather, most of the tests so far have mostly zero fees.

**Describe the solution you'd like**

- Test all fees, in happy path, with nonzero values. Including for 3rd party providers. 
- Test for extremes of fees
- Test for unhappy paths. Truly try to break it! Eg is there some combination of fees where someone can make an (unfair) killing? Eg are there ways that a malicious marketplace can essentially steal from people?

**Comment by DMats** [comment]
I believe I must test:

- [ ] providerFee
- [ ]  consumeMarketFee
- [ ]  publishingMarketFee
- [ ]  swapOceanFee
- [ ]  swapNonOceanFee
- [ ]  OPC Fee (Ocean Protocol Community)

If I'm missing anything please let me know.

**Comment by trentmc** [comment]
There's more than the six fees given.

A full list is in [V4 Fees - Base doc](https://docs.google.com/document/d/1SufCXSWCUMN-x1d8hZY-7-JwUz-qzeBG-B081WfKNz4/edit#heading=h.wjhjoawwu1qk), table in section 2. 

There are about 15 rows. You should test each row at least once for nonzero values. Including in end-to-end flows for steps of publish, swap (fixed-rate), swap (pool), and consume.

**Comment by DMats** [comment]
In today's Daily stand-up @trentmc shared a blog post draft that @jamiehewitt15 is writing which describes the fees in more detail: https://docs.google.com/document/d/1TEjEn5hhzwC5PaRlyY0ISZjyXDbZxxkYBNQwgOnBSco/edit

**Comment by DMats** [comment]
Note to self: consider also adding a test for the `allowed_swapper` argument used when creating fixed-rate exchanges. Currently all unit tests set this to `ZERO_ADDRESS`

**Comment by DMats** [comment]
The v4 fees are documented at https://github.com/oceanprotocol/docs/blob/main/content/concepts/fees.md
