### ISSUE TITLE
`ocean.assets.download` not downloading correctly 

### ISSUE THREAD

**Issue by smejak** [oceanprotocol/ocean.py#746]
**Describe the bug**
Using the marketplace flow downloads datasets that cannot be opened. Output is either a zip file that doesn't open or a txt file that cannot be opened or a `view?usp=sharing` txt file. 

**To Reproduce**
1. Go to ocean marketplace flow
2. Run ocean.assets.download after getting the datatokens. I used the following
`data_did = 'did:op:8455EF25Ee6F838Ca6Baf305CF8E584C63CB0A6D'
data_pool = '0xaDedAb61c9161D601129fDc754905a9D6e68d85b'`

4. wait until the dataset downloads
5. try to open the zip file and see the error

**Expected behavior**
A downloaded zip file that can be opened and contains the dataset

**Screenshots**
Note: the code I was running is part of a jupyterlab extension we're building at Algovera to make interacting with Ocean Market more accessible to data scientists, it is running the ocean marketplace flow in the backend. Here is the code in the extension: https://github.com/AlgoveraAI/jupyterlab_extensions/blob/main/algovera/ocean_transaction.py

<img width="679" alt="Screenshot 2022-03-06 at 18 49 47" src="https://user-images.githubusercontent.com/20759274/156938075-31bf6fb8-a132-4706-8ee0-4031623c06ad.png">
<img width="652" alt="Screenshot 2022-03-06 at 18 50 52" src="https://user-images.githubusercontent.com/20759274/156938080-8b90d60b-fd21-4bbd-86a2-c18f2eba27e9.png">
<img width="640" alt="Screenshot 2022-03-06 at 18 51 01" src="https://user-images.githubusercontent.com/20759274/156938081-59ea6f29-28b9-4735-8b3b-235b34949613.png">
<img width="628" alt="Screenshot 2022-03-06 at 18 51 15" src="https://user-images.githubusercontent.com/20759274/156938083-4ea80ea7-f366-403f-bb34-d53d7b71c583.png">
<img width="944" alt="Screenshot 2022-03-06 at 18 51 44" src="https://user-images.githubusercontent.com/20759274/156938084-8e62576d-801b-4ec2-9c9b-dd3a17b4f43b.png">
<img width="486" alt="Screenshot 2022-03-06 at 18 52 02" src="https://user-images.githubusercontent.com/20759274/156938086-dc6308a2-e67d-4324-a0b9-873ee3593f12.png">

**Desktop (please complete the following information):**
 - OSX
 - Brave Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnaLoznianu** [comment]
Hello! Thank you for opening this issue
Right now we are focused on V4 features, it will take a bit till we get to debug and fix this.

Thanks for your understanding!

**Comment by calina-c** [comment]
Hi, @smejak! When you are creating the dataset, are you using the correct link (file URL)? If it's a google drive link protected by access rules, OCEAN will not be able to download it. Based on the "usp-sharing" part, I think it might be that. Try pasting the URL (before any encryption or altering) to an incognito window. If it downloads from there, OCEAN should be able to download it as well.

**Comment by AnaLoznianu** [comment]
@smejak If you encounter this issue again, please reopen it
