### ISSUE TITLE
ocean.assets.update() failing with an error giving no clear information

### ISSUE THREAD

**Issue by kboyeldieu** [oceanprotocol/ocean.py#75]
I'm trying to update a dataset description using the API. I'm calling `ocean.assets.update(asset, wallet)`, which returns `ValueError: Invalid value to publish in the metadata: {'code': -32000, 'message': 'execution reverted'}`, although `ocean.assets.validate(asset.metadata)` returns true.

I can't tell what's wrong from this error. Could we include some more meaningful information?

**Comment by alexcos20** [comment]
@kboyeldieu - can you print your asset and wallet values please?

**Comment by kremalicious** [comment]
@kboyeldieu please reopen if issue still persists on your side
