### ISSUE TITLE
V4 Cleanup

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#759]
ocean.py needs a few minor cleanups:

1. ERC721Factory methods are using unnamed argument lists. Should use named arguments instead.
2. Inconsistent argument names, especially for fees and "base_token" which is two words.
3. Large portion of models/ directory is missing type enforcement and as a result, many of the type hints are wrong.
4. There are places where `wait_for_transaction_receipt` is called unnecessarily (ContractBase automatically does this when calling send_transaction)

**Comment by trentmc** [comment]
I like the goals of this issue.

For the future, I strongly recommend creating four separate issues, each with smaller scope. And a related PR for each. This helps code review, and future maintainability too.

**Comment by DMats** [comment]
@trentmc I agree. FYI, The issues described here were discovered while working on #744, and this issue is already split out of that one. Under normal circumstances, I would have also split it into more granular issues but with the focus on the V4 release, i couldn't justify it in this case.
