### ISSUE TITLE
Fix DRY violations in test_erc721_token.py & related

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#765]
**Is your feature request related to a problem? Please describe.**

`ocean_lib/models/test/test_erc721_token.py` has ten calls to `deploy_erc721_erc20()`. There are four more in `test_erc20_token.py`, and five more in other test modules of this directory. Most of these take about 5 lines, and have exactly the same boilerplate code.

This violates DRY (DRY = Don't Repeat Yourself). In turn, this hurts maintainability, extensibility, etc.

**Describe the solution you'd like**

Use the directory's `conftest.py` more, as pytest intends it to be. Right now it's only being used to define wallets. Add routine(s) in it to create erc721 & erc20 with a single call to  `deploy_erc721_erc20()`. Then for each test function: (1) add `data_nft` or `datatoken` argument, drawing on the conftest info, and (2) remove its call to `deploy_erc721_erc20`.  

With this, we can remove most calls to `deploy_erc721_erc20()` in the test py files.

Note: there are probably other great opportunities to leverage conftest.py to fix DRY violations. This was simply the first one I noticed, as I hadn't looked at the tests in a while.

**Comment by mariacarmina** [comment]
UPDATE: remove `is False` & `is True` parts from the assert statements.
