### ISSUE TITLE
Outdated contract artifacts in ocean.py

### ISSUE THREAD

**Issue by akonale** [oceanprotocol/ocean.py#786]
**Description**
Steps described in READMEs/datatokens-flow.md does not work because abi files outdated under artifacts/contracts hence function signature do not match. So the quickstart does not work anymore. This might be discouraging for new users.

**To Reproduce**
1. Follow "Simple Flow" readme to try to setup ocean datatoken nfts
2. Error from blockchain call.

**Expected behavior**
New token with name 'NFTToken1' and symbol 'NFT1' is created in local ganache.

**Desktop (please complete the following information):**
 - OS: OSx 
 - Version 12.3.1

**Comment by mariacarmina** [comment]
I have tested this locally using `barge` on Ubuntu environment.
<details>
<summary> Datatokens flow run succeded </summary>
```python

```

(venv) maria@ubuntu:~/Desktop/test3$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config()
ocean = Ocean(config)
print(f"config.network_url = '{config.network_url}'")
config.network_url = 'http://127.0.0.1:8545'
print(f"config.block_confirmations = {config.block_confirmations.value}")
config.block_confirmations = 0
print(f"config.metadata_cache_uri = '{config.metadata_cache_uri}'")
config.metadata_cache_uri = 'http://172.15.0.5:5000'
print(f"config.provider_url = '{config.provider_url}'")
config.provider_url = 'http://172.15.0.4:8030'
import os
from ocean_lib.web3_internal.wallet import Wallet
alice_private_key = os.getenv('TEST_PRIVATE_KEY1')
alice_wallet = Wallet(ocean.web3, alice_private_key, config.block_confirmations, config.transaction_timeout)
print(f"alice_wallet.address = '{alice_wallet.address}'")
alice_wallet.address = '0x02354A1F160A3fd7ac8b02ee91F04104440B28E7'
from ocean_lib.ocean.mint_fake_ocean import mint_fake_OCEAN
mint_fake_OCEAN(config)
assert alice_wallet.web3.eth.get_balance(alice_wallet.address) > 0, "need ETH"
print("Create ERC721 data NFT: begin.")
Create ERC721 data NFT: begin.
erc721_nft = ocean.create_erc721_nft('NFTToken1', 'NFT1', alice_wallet)
print(f"Created ERC721 token: done. Its address is {erc721_nft.address}")
Created ERC721 token: done. Its address is 0xb38b5A1A0B7c48099a8C53dD179726bf8A416538
print(f"data NFT token name: {erc721_nft.token_name()}")
data NFT token name: NFTToken1
print(f"data NFT token symbol: {erc721_nft.symbol()}")
data NFT token symbol: NFT1
from ocean_lib.web3_internal.constants import ZERO_ADDRESS
print("Create ERC20 datatoken: begin.")
Create ERC20 datatoken: begin.
cap = ocean.to_wei(100)
nft_factory = ocean.get_nft_factory()
erc20_token = erc721_nft.create_datatoken(
...     template_index=1, # default value
...     name="ERC20DT1",  # name for ERC20 token
...     symbol="ERC20DT1Symbol",  # symbol for ERC20 token
...     minter=alice_wallet.address,  # minter address
...     fee_manager=alice_wallet.address,  # fee manager for this ERC20 token
...     publish_market_order_fee_address=alice_wallet.address,  # publishing Market Address
...     publish_market_order_fee_token=ZERO_ADDRESS,  # publishing Market Fee Token
...     cap=cap,
...     publish_market_order_fee_amount=0,
...     bytess=[b""],
...     from_wallet=alice_wallet
... )
print(f"Created ERC20 datatoken: done. Its address is {erc20_token.address}")
Created ERC20 datatoken: done. Its address is 0x0356a886Ad462e18880F1E6bfbBcb035759b127D
print(f"datatoken name: {erc20_token.token_name()}")
datatoken name: ERC20DT1
print(f"datatoken symbol: {erc20_token.symbol()}")
datatoken symbol: ERC20DT1Symbol

```
</details>

If you had previously V3 `.ocean` folder, I recommend you to remove `.ocean` folder from root, after `docker system prune -a --volumes` to remove all the docker images, `cd barge`, `git checkout v4main`, `git pull`, `./start_ocean.sh --no-dashboard`.

**Comment by akonale** [comment]
Hi,
I did not have v3 folder before. For me it was failing because solidity contract artifacts were incorrect in my environment. Maybe there is a step missing somewhere in the docs which tells about installing the artifacts.
Eg. 
```
pip install ocean-contracts
```
Or installs it from the script in codebase
eg.
```
set VIRTUAL_ENV=<> ./artifacts/install.sh
```

In any case I see files in artifacts/contracts does not reflect what is there in v4 version of ocean-contracts. If it is intended its fine. We can close the bug report :)

**Comment by mariacarmina** [comment]
The folder `artifacts` from ocean.py needs to be removed. It's strange that we already had a PR related to that https://github.com/oceanprotocol/ocean.py/pull/685/files, but I will create another PR that removes the artifacts folder from ocean.py, so no need to run `./artifacts/install.sh`. I have asked also macOS users to reproduce this flow and some python packages weren't installed properly and required to be installed manually (for example `scipy`), but nothing related to the artifacts. 
BTW, if you are using barge, make sure that you export the correct path that points to the artifacts,
[ADDRESS_FILE](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/datatokens-flow.md#set-envvars)
