### ISSUE TITLE
Vesting & cap aren't fully removed yet; will cause user confusion

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#811]
**Describe the bug**
We cut out vesting in the smart contracts a few weeks ago. Took much security risk for the benefits. The smart contract interface for vesting was kept, just for potential in the future.

But ocean.py should just hide it completely, just giving zero values so that the user doesn't even have to think about it. (Keeping it is a problem because the user will get confused.)

Related: Same thing for datatoken `cap`. Why: ERC20 datatokens created from ERC721 have cap hardcoded to max integer (see `_cap = 0xff.ff` [in ERC20Template.sol](https://github.com/oceanprotocol/contracts/blob/b937a12b50dc4bdb7a6901c33e5c8fa136697df7/contracts/templates/ERC20Template.sol#L285)). Yet ocean.py interface still allows for cap to be set, see e.g. [test_erc721_token.py](https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/models/test/test_erc721_token.py). 

Places to fix / to check:
- [marketplace readme](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/marketplace-flow.md) still has it, and sets a nonzero value. 
- [test_side_staking.py](https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/models/test/test_side_staking.py) still refers to it to 
- [test_erc721_token.py](https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/models/test/test_erc721_token.py) still sets `cap`, and (currently) doesn't even check what the value is. It shouldn't even set cap.
- And probably more! I just had a quick glance and already saw this

I suggest to search for "vest" and "Vest", and remove every place it shows up, except for the smart contract call itself where you insert a zero.

**Comment by calina-c** [comment]
@mariacarmina I think you fixed this in #799. Am I right?

**Comment by trentmc** [comment]
> @mariacarmina I think you fixed this in #799. Am I right?

I just checked, all three examples listed in the description have not been addressed. And there is probably more.

**Comment by mariacarmina** [comment]
I have deleted all vesting tests, vesting events on #799, sorry for my late response. That was a PR which resolved some conflicts, new contract release and a barge update, so we decided to fix in that PR (also discussed with @calina-c about this)

**Comment by mariacarmina** [comment]
I will delete the rest of occurrences of vesting if there are any.

**Comment by trentmc** [comment]
> I will delete the rest of occurrences of vesting if there are any.

I just checked, all three examples listed in the description have not been addressed. And there is probably more.

**Comment by mariacarmina** [comment]
Ok, I will create a PR based on this, thank you @trentmc.

**Comment by mariacarmina** [comment]
Hello @trentmc, I saw that removing the cap from `create_erc20` contract function call will raise an exception as is mentioned in the contracts (https://github.com/oceanprotocol/contracts/blob/v4main/contracts/ERC721Factory.sol#L339).
![Screenshot from 2022-05-19 16-32-09.png](https://images.zenhubusercontent.com/5ff442e8d03d4b2d4051265f/99c18c77-9bd3-49c1-86f2-8c300e25ef17)
Either the contracts need a fix in this case, either keep the cap in ocean.py tests.
I remember that I had a discussion with @alexcos20 regarding setting the cap to max integer value. The `cap` is a generic property of an ERC20 token and we kept in the contracts logic for ERC20 "standard methods". Maybe we can create an issue on the contracts to remove that `require` and also keep the cap aside.
What do you think @trentmc, @alexcos20 ?

**Comment by trentmc** [comment]
Don't change the contracts. Just pass in dummy values.

**Comment by trentmc** [comment]
Note: we should have done a new release on this, since it broke the interface. 

I created a new issue for it. https://github.com/oceanprotocol/ocean.py/issues/836
