### ISSUE TITLE
Change web3.eth.sign from the production code

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#820]
web3.eth.sign is not compatible with certain infura RPCs and it needs to be replaced with provider endpoint `initialize` which returns the fees for the provider. It is used [here](https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/ocean/ocean.py#L359)

**Comment by DMats** [comment]
Some additional context on this task: 

We realized that the `Ocean` API in ocean.py doesn't offer methods for calling `initialize`  or `initializeCompute` without also ordering the asset. This makes using the special erc20_enterprise methods difficult to use: `buy_from_fre_and_order` and `buy_from_dispenser_and_order`

So part of fixing this issue should include adding new methods at the `Ocean` API level that call `initialize` or `initializeCompute` without ordering.
