### ISSUE TITLE
Add a function to use the checkURL endpoint from provider

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#86]
The provider has a new endpoint to check the URL contentType and contentLength before proceeding. If the URL is missing, wrong, non-confoormant, does not support GET, or does not return anything, the checkURL endpoint returns a 400 response. This issue adds the possibility to call the checkURL endpoint from ocean.py.

**Comment by trentmc** [comment]
Could you provide a better description to the issue, please?

**Comment by calina-c** [comment]
@trentmc Added a description, and will do so for ocean.js as well.

**Comment by trentmc** [comment]
Great!
