### ISSUE TITLE
FileInfo Endpoint

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#869]
Right now, this endpoint supports only 2 scenarios:
 - did  - and provider will decode/decrypt whatever data source is used
 - url

2nd scenario (just url) breaks the current definition of url-storage (see https://docs.oceanprotocol.com/concepts/did-ddo/#files)
We should accept the full object, like:
```
[
    "type": "url",
    "url": "https://url.com/file1.csv",
    "method": "GET",
    "headers":
      [
       {"Authorization": "Bearer 123"}, 
       {"APIKEY": "124"},
]
```

Provider issue: https://github.com/oceanprotocol/provider/issues/504

**Comment by calina-c** [comment]
I've uploaded a screenshot of the Provider functionality in its ticket. The functionality already uses the object and not the single url. I'm uploading one here, too, from ocean.py. You can see there's a json containing the url object, not a single url.

![Screenshot 2022-06-28 at 07.34.51.png](https://images.zenhubusercontent.com/5795cf04e40e5714b16c76c5/750d4e35-a325-4003-8e0c-f62bea57309a
)
