### ISSUE TITLE
Create README for predicting ETH price

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#899]
### Background info

- Algorithm competitions like Kaggle are a big thing in AI / data science. Benefits: they connect people with data problems to AI / data scientists, and they offer an opportunity for up-and-coming AI / data scientists to show their chops and earn $. 
- Ocean has USPs to algorithm competitions: can handle private data; no middleman; competition can allow for arbitrary new data to be incorporate
- We want to bias more to DeFi users. To do that, Ocean needs to have more DeFi-related data available, and C2D needs to be able to demonstrably work well on that
- We want more tangible guidance for how to evolve Ocean products from a product marketing perspective

### Overall aim

Create a "predict" README that's the baseline tech to drive a regular competition to predict ETH price, eg as part of Data Bounties program. [Data Bounty Questbook Draft](https://docs.google.com/document/d/17naqb4J9IEiU1QDA0jZawI2xlzPYbgewvv1sIOyk3i0/edit)

This in turn will be used in Data Bounties, help to fix bugs in Ocean, drive specs in Ocean, and pull in more DeFi data.

### Specs

predict-eth.md will be the main point of entry for people in the competition. They should be able to go through it in 10 min, and result in doing a submission of an entry to the competition, by simply pointing to the correct chain. (This means low UX friction for the competition.)

**Steps in predict-eth.md:**
- get data locally from these assets on Ocean:
  - csv with many years of past ETH price [[link](https://drive.google.com/file/d/1sHwWniWrjxG4MKMbqrvgkkz6lUDgYqu1/view)]
  - Binance API price feed of ETH-USDT
- makes predictions : builds a simple ML model (client-side), and runs the ML model to make future ETH price predictions. Predictions are for a near-future 24h period, one prediction every hour on the hour.
- publishes the predictions as a csv in a new Ocean asset
- sends 1.0 datatokens to the competition organizers’ address

Predicted price should be tamper-resistant, so that competitors can't cheat.

The chain can't be local, it must be a remote testnet or production net. 

### TODOs for this issue

- [x] Create "publish-flow-api.md" README, which publishes a Binance price feed API as a data asset onto Mumbai
- [x] Create "predict-eth.md" README, which goes through the "Steps in predict-eth.md" listed above. It works off Mumbai by default. And at the tail end, show how to publish to Polygon instead.

### Resources:

- [How df-py uses Binance API to get price](https://github.com/oceanprotocol/df-py/blob/f4576559a852fccfabf19548372d016ffa81f67e/util/getrate.py#L36). Code: `"https://api.binance.com/api/v3/klines?symbol={token_symbol}USDT&interval=1d&startTime={int(st_dt.timestamp())*1000}&endTime={int(fin_dt.timestamp())*1000}"`, where `token_symbol` is e.g. `ETH`
- [DF Crunch slides - will have some useful details](https://docs.google.com/presentation/d/1MOgzlQWJB251rm7D_9dt4xwuKVsRxVbqsjweU05cC7Q/edit#slide=id.g114755ae868_0_0).
- Possible data source: [ETH/USD daily historical data since Aug-2015](https://drive.google.com/file/d/1sHwWniWrjxG4MKMbqrvgkkz6lUDgYqu1/view?usp=sharing) . OHLCV (Open, High, Low, Close, Volume), Historical Market Cap
- Possible data source: [BTC/USD daily historical data since Jul-2014](https://drive.google.com/file/d/1LNFfFXDR7ip35Pt93qdaf3UolZK0WVjs/view?usp=sharing). OHLCV (Open, High, Low, Close, Volume), Historical Market Cap

### Don't need for _this_ issue

Competitors have to use C2D. Then, the flow would be: Publish a C2D algorithm that inputs pricefeed data (Ocean asset), builds a model to predict ETH price, and outputs predicted price (also as an Ocean asset). 

Should be standalone: people don't need to be in a competition to use it.
 
Include an on-chain price feed, e.g. ETH-USDT on Chainlink. 

Include a TheGraph price feed, e.g. Uniswap V3 TWAP of ETH-USDT on TheGraph.

**Comment by trentmc** [comment]
We can parameterize data assets (not just alg assets). This is great news, because it will be simpler than using c2d algorithm to get binance api price feeds etc.

Alex shared details here: 
1. Docs on ddos. "But it looks like it's broken. So just search for 'consumer parameters on that page"
2. Ocean.py! https://github.com/oceanprotocol/ocean.py/blob/e30b20a8d09c5eef6124ccc7ee7c9e30a244f40c/ocean_lib/services/consumer_parameters.py

[Slack thread](https://oceanprotocol.slack.com/archives/CNDG1849Z/p1662668243262849?thread_ts=1662662307.615819&channel=CNDG1849Z&message_ts=1662668243.262849)

**Comment by trentmc** [comment]
Alex recently added graphql support, and parameterized :)
https://github.com/oceanprotocol/ocean.py/issues/911

Maybe useful here too

**Comment by trentmc** [comment]
For the future chainlink stuff, Alex is adding support for "smartcontract data service". 

"Not only that we can integrate chainlink and umbrella data feeds, but now we can use any smart contract as data source:
https://github.com/oceanprotocol/provider/pull/540 

(So , fetching historical data from chainlink would be a nice walk in the park:  https://docs.chain.link/docs/historical-price-data/)

PS: most complex work was done on this PR, ocean.js/py needs some attention, I will handle it during the weekend"

[slack thread](https://oceanprotocol.slack.com/archives/CNDG1849Z/p1663328005348869 )

**Comment by trentmc** [comment]
Super-high priority because data bounty related to this is _soon_. This is my focus for tomorrow (Sep 20).

**Comment by trentmc** [comment]
With the commit https://github.com/oceanprotocol/ocean.py/commit/a77367c0c325b3fc58a93df5aaa39f228710053b, it's done, well enough for launching the competition:)

But it isn't perfect yet. I will make more improvements in coming days, eg more fine-grained historical data, and a better demo AI model. I will use this issue to keep everything in the same place.

**Comment by kremalicious** [comment]
Existence of #981 implies this issue here is done.

**Comment by trentmc** [comment]
Re-opening because I still have improvements to do. Easier to track here, than a new issue.

**Comment by trentmc** [comment]
> Re-opening because I still have improvements to do. Easier to track here, than a new issue.

Ah, nevermind, #981 is better.
