### ISSUE TITLE
ocean.py has 10 stale branches. Leverage? Remove? 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#902]
ocean.py has 10 stale branches. All are >3 mos old, and most >6 mos old. See image below.

It's hard to maintain software - and software quality - with random branches hanging around.

**TODO for this issue**

For each branch:
- identify if we do want to leverage the code at all
- if "no", delete
- if "yes", then find an appropriate way to take it to completion. Eg (a) merge in main, (b) create a fresh branch and bring over relevant changes, then get it merged in, (c) let go, don't bother with it, and do "no / delete" and perhaps mark the github issue as wontfix as well.

Stale Branches: [link](https://github.com/oceanprotocol/ocean.py/branches/stale)

![branches](https://user-images.githubusercontent.com/5305452/188708776-65198a91-469d-4a9b-b5c1-53597c6b8d20.png)

**Comment by calina-c** [comment]
I cleaned up the branches. From the list of stale branches, I only kepy the parameters.md one, that we know we want to revive someday.

**Comment by trentmc** [comment]
> I only kepy the parameters.md one, that we know we want to revive someday.

Looks like there are two stale branches still open. Besides the parameters.md one you mention, there's a "v3" one by David H-M. We should resolve that too.
![stale](https://user-images.githubusercontent.com/5305452/188916111-1a3831d4-23e1-4b82-9f01-db2d32490f91.png)

**Comment by trentmc** [comment]
Thanks for the info.

It's kind of annoying to have this sitting here as a branch. We could also fork it into a different repo. If we did that, do you see any issues, with usability or maintainability?

**Comment by calina-c** [comment]
> Thanks for the info.
> 
> It clutters up ocean.py to have this sitting here as a branch. We could also fork it into a different repo. If we did that, do you see any issues, with usability or maintainability?

I think the problem would be especially with **overcrowding the list of repos**. It's not just ocean.py, but also provider, aquarius, barge (and others, maybe) that have a v3 version.

We would also have to **update PyPi directories and deployments** to use the new repos, with everything that entails: credentials, secrets and configurations for running release builds and tests. PyPi and GitHub releases would then also consider these different packages, not different versions.

From a strictly code-related perspective, I think it moving all these repos would generate some manageable confusion with our users and impair some abilities to cherry-pick fixes when needed. However, I think this is a minor argument to make, and the arguments above are more potent here.

I think the decision to keep v3 as branches was a sane one.

**Comment by trentmc** [comment]
Thanks for the thoughts. OK then! 

At some point - when people have had enough time to move over to v4 - we can merely delete the branch. But no rush, at least 6 mos, possibly much longer.
