### ISSUE TITLE
CI test randomly fails: test_compute_flow.py::test_compute_update_trusted_algorithm

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#905]
Pre-requisite to this issue: [#938](https://github.com/oceanprotocol/ocean.py/issues/938) "Streamline Config: no config.ini file, no dict, just envvars." Then, doing this issue will be much, much simpler.

This test is now skipped, until the issue is fixed. Commit: https://github.com/oceanprotocol/ocean.py/commit/1c15c1d37617547aa33cb32bb17ca04b4138ac18

----

**Describe the bug**

I just created a branch, made a trivial change (added a space to a README), and created a [PR](https://github.com/oceanprotocol/ocean.py/pull/903) from it. 

This of course invoked the CI automated tests.

The automated test results [show two failures](https://github.com/oceanprotocol/ocean.py/runs/8213667665?check_suite_focus=true):
```text
=========================== short test summary info ============================
FAILED ocean_lib/data_provider/test/test_data_service_provider.py::test_get_root_uri
FAILED tests/integration/test_compute_flow.py::test_compute_update_trusted_algorithm
```

UPDATE Sep 19: the first test now passes. The second fail still exists, randomly.

**Comment by calina-c** [comment]
I'm currently fixing that here: https://github.com/oceanprotocol/ocean.py/pull/898. We used a now-obsolete provider for some URL transform tests.

**Comment by trentmc** [comment]
Copied comment from @mariacarmina [here](https://github.com/oceanprotocol/ocean.py/pull/903#issuecomment-1238983167): 

> tect_data_service_provider.py::test_get_root_uri is outdated and will be fxed in @calina-c 's PR https://github.com/oceanprotocol/ocean.py/pull/898 (https://github.com/oceanprotocol/ocean.py/commit/440a8d5478e756069face84da005e3fa70e17790). The second one, test_compute_flow.py::test_compute_update_trusted_algorithm fails when the compute job is taking too long to run, when this happens, we usually re-run the tests on CI, but it doesn't happen everytime.

**Comment by trentmc** [comment]
Reopening this issue. @calina-c 's fix above was for the first issue: `tect_data_service_provider.py::test_get_root_uri`.

There is still not a fix for the second issue: `test_compute_flow.py::test_compute_update_trusted_algorithm`. It's unacceptable to have CI that randomly fails; it makes it hard to develop against. 

We can only close this issue when _all_ the issues reported have been resolved, not a subset.

**Comment by calina-c** [comment]
@trentmc the update trusted algorithm or some other compute-related test will fail sometimes due to c2d timeout issues. From ocean.py, we have no control over pod publishing, calculation, time spent on c2d setup and teardown etc. C2d-related tests are integration tests, so they run through the entire stack.

One solution would be for us to always wait an excessive time for these results to show up, slowing down tests. But since we always have 2 suites (pull request and push), and the probability of both failing at once is minimal, then we save some time by allowing this. I agree it is not the best solution, but also it is not an ocean.py fix.

**Comment by trentmc** [comment]
Thanks for the info. We still need to solve the issue: we can't have tests randomly failing. It makes sw development hard if we make changes then tests fail for other reasons.

So we need to make changes such that the chance of any test failing is zero, or near zero (eg <1/10000). 

Consider that the aim of this issue.

Now, let's find a way. It's ok if it's an ocean.py specific thing.

Some possible ways:
1. Wait an excessive time for the results, as you suggest
2. Like 1, but keep checking if there are results, and stops as soon as there are. This minimizes the time overhead compared to (1)
3.  don't run the two failing tests in ocean.py local or CI testing. Instead have a separate setup with its own CI, that runs daily; this could be in ocean.py or a different repo 

(3) is best if we see a way to do it easily.

(1) and (2) are similar, and (2) has less time overhead.

I recommend (3) if you (Calina) see a way to do it easily. Otherwise do (2).

**Comment by trentmc** [comment]
I just turned off the remaining test, until we can fix it.

Fixing it is now the goal of this issue
https://github.com/oceanprotocol/ocean.py/commit/1c15c1d37617547aa33cb32bb17ca04b4138ac18
