### ISSUE TITLE
UX Tweak: Streamline ocean.assets.create()

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#917]
I found in READMEs/publish-flow.md, that the call to `asset = ocean.assets.create()` passes in _many_ parameters that don't need passing in. 

TODO: change things such that we don't need to pass in these parameters.

This includes:

- update data_nft.py, ocean_assets.py, and related tests since they don't fully support optional args. I took a first swing at this, see the file: [changes.tar.gz](https://github.com/oceanprotocol/ocean.py/files/9535877/changes.tar.gz).

The file holds a direct diff from the ocean.py code state right after I merged in everything from "UX tweaks for READMEs, round one" https://github.com/oceanprotocol/ocean.py/commit/f1f5c35e185ee57e4f3c0d308f3f5a8fbab057e7. It also holds the .py files in that state, after the diff is applied.

**Comment by trentmc** [comment]
I've removed the "priority = low" label because doing this is a super-useful step in the UX of ocean.py for data scientists. And data scientists - especially ones in DeFi - are a key focus for us. Many of our activities are crystallizing around serving them better.

I will do this issue, because I have a strong idea of what I want. Once I'm done this issue, I will build from it to further enhance UX.

**Comment by AnaLoznianu** [comment]
@trentmc We are prioritizing the backlog issues together. If everything is high priority then nothing is high priority. 
The plan was to start working on this these days(that's why it's in the next sprint column).
If you want to do it then I'll assign it to you.

**Comment by trentmc** [comment]
Thanks, @AnaLoznianu. The issues that I plan to do, I've assigned to myself. So, we're in sync:)

**Comment by trentmc** [comment]
Just merged in the biggest chunk of work: https://github.com/oceanprotocol/ocean.py/commit/aa9bef2aea0fa32a82f516d22cd1b65345e66f34

Remaining TOODs in this issue:
* add unit tests for the 4 new methods
* publish-graphql.md was partly broken. l've partly fixed it as part of the merge above. Still a bit of work left.
* update publish-remote.md as well
