### ISSUE TITLE
Create README: add label to asset; search & filter by label

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#918]
There are several use cases where we want to retrieve data NFTs (or datatokens) by searching across all of them, and filtering down by label.

This should be easy for ocean.py users to figure out.

TODO for this issue: add a README where the user:
- creates a few data assets. Each asset has >= 1 labels
- searches & finds the assets by filtering by label

Potentially helpful resources:
- [df-py "Filter non-market assets" PR](https://github.com/oceanprotocol/df-py/pull/292) uses the patterns that we can use here.
- Base resource: https://docs.oceanprotocol.com/core-concepts/did-ddo 
- Another example: [https://1520763098-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FzQl[…]23f36dcef441e8fd76fdf6b6%2Fddo-flow%20(1).png?alt=media](https://1520763098-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FzQlpIJEeu8x5yl0OLuXn%2Fuploads%2Fgit-blob-fab9a027b0a25d4023f36dcef441e8fd76fdf6b6%2Fddo-flow%20(1).png?alt=media)

**Comment by kremalicious** [comment]
what's a "label"? We have `tags` & `categories` so which one is it? https://docs.oceanprotocol.com/core-concepts/did-ddo#metadata

**Comment by trentmc** [comment]
Either one. "Tag" is best. 

(If you ask me we should deprecate "category" because it's a subset of "tag", and its boundaries are fuzzy. But that's another story.)
