### ISSUE TITLE
Mumbai: ocean.create_data_nft() fails getting token_address from tx_receipt

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#921]
### To reproduce

How to reproduce:
1. set yourself up with the [ocean.py developers flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/developers.md). Note: You don't need barge going.
2. Have two mumbai accounts, each holding fake MATIC. In the console, make them available as envvars. That is:
```
export REMOTE_TEST_PRIVATE_KEY1=0x8c1..
export REMOTE_TEST_PRIVATE_KEY2=0x73d..
```
3. in console, run: `pytest tests/integration/remote/test_mumbai.py::test_nonocean_tx`. It should pass. This will confirm that you can indeed run simple non-Ocean transactions on Mumbai.
4. open `tests/integration/remote/test_mumbai.py`, and comment out the "@pytest.mark.skip(..)`
5. in console, run: `pytest tests/integration/remote/test_mumbai.py::test_ocean_tx`. It should fail, where it tries to create a data nft. (The first real call to Ocean.)

### Traceback

```python
data_nft = ocean.create_data_nft('NFT1', 'NFT1', alice_wallet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 185, in create_data_nft
    address = nft_factory.get_token_address(tx_id)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/models/data_nft_factory.py", line 444, in get_token_address
    return registered_event[0].args.newTokenAddress
IndexError: list index out of range
```

### Background

I first encountered this issue [here](https://github.com/oceanprotocol/ocean.py/issues/920#issuecomment-1248442537). I've made it easy to reproduce, as a unit test (that's currently skipped), via [this work](https://github.com/oceanprotocol/ocean.py/pull/924).

**Comment by trentmc** [comment]
For reference, below is df-py's oceanutil.py::createDataNFT(). It gets a token address from the NFT-creating tx. It's short and compact, thanks to using brownie.

Key line:
```python
data_NFT_address = tx.events["NFTCreated"]["newTokenAddress"]
```

Full function:

```python
def createDataNFT(name: str, symbol: str, from_account):
    erc721_factory = ERC721Factory()
    template_index = 1
    additional_metadata_updater = ZERO_ADDRESS
    additional_erc20_deployer = factoryRouter().address
    transferable = True
    owner = from_account.address
    token_uri = "https://mystorage.com/mytoken.png"

    tx = erc721_factory.deployERC721Contract(
        name,
        symbol,
        template_index,
        additional_metadata_updater,
        additional_erc20_deployer,
        token_uri,
        transferable,
        owner,
        {"from": from_account},
    )
    data_NFT_address = tx.events["NFTCreated"]["newTokenAddress"]
    data_NFT = B.ERC721Template.at(data_NFT_address)
    return data_NFT
```

**Comment by trentmc** [comment]
As another datapoint, I just published an asset into Ocean Market, on Mumbai. Free.

Tx 1: "Create Tokens & Pricing"
https://mumbai.polygonscan.com/tx/0x296da32238ee9cf7de706ef45d0e92bd1c18389ab7e5add051efa1fa1fc9238f

Tx 2: "Publish DDO"
https://mumbai.polygonscan.com//tx/0xcbe9bb08b4d92746f1305d3505858751deaba617eb5e2589824bb300865adbee

Note: I used a different wallet. 0xF5dcd..

**Comment by alexcos20** [comment]
Are you sure that https://mumbai.polygonscan.com/tx/0xa2edd4c742c67274c4fb3be64e6cf714080c17aa84b37ae607a299e65d5d707f is the tx that you are looking for ?

1. Mumbai Factory has another address (https://github.com/oceanprotocol/contracts/blob/main/addresses/address.json#L46)
2. NFTCreated  event has a different signature  (0x8125264ec1d174cb383ea0646ea1e6921ca3b0aba20370c8e18389e7c2d6a571  vs 0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63 in your contract)
3. found 
<html>
<body>


2365 | LogFeeTransfer(address,address,address,uint256,uint256,uint256,uint256,uint256) | 0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63
-- | -- | --



</body>
</html>

I would say that you are not passing the right txid

**Comment by trentmc** [comment]
Thanks. Maybe I shared the wrong txid in my report above. But the issue occurred independent of what I report here. 

Basically, ocean.py fails on its most fundamental tx: create data nft. See traceback above. The fail doesn't happen in ganache, it does happen in Mumbai and rinkeby (the only ones I've tested so far).

Run the unit test as described in how to reproduce, you'll see.

> NFTCreatedEvent has a different signature 

Maybe the issue is here?

**Comment by alexcos20** [comment]
Looks like Ocean.py is not able to get the correct address for ERC721Factory:

By adding
```
print(nft_factory)
```
at https://github.com/oceanprotocol/ocean.py/blob/2a5c9fd9e626b06b3b16e4bbf82de60766a7af4c/ocean_lib/ocean/ocean.py#L172, I got this:


```
----------------------------- Captured stdout call -----------------------------
config filename = /tmp/pytest-of-alx/pytest-6/test_ocean_tx0/config.ini
config.network_url = 'https://rpc-mumbai.maticvigil.com'
config.address_file = '/home/alx/.ocean/ocean-contracts/artifacts/address.json'
config.block_confirmations = 0
config.metadata_cache_uri = 'https://v4.aquarius.oceanprotocol.com'
config.provider_url = 'https://v4.provider.mumbai.oceanprotocol.com'
<ocean_lib.config.Config object at 0x7f86a998fac0>
<ocean_lib.ocean.ocean.Ocean object at 0x7f86a998fa00>
alice_wallet.address = '0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544'
bob_wallet.address = '0xD6764a9F3387B14692CC783BcF5604a23EBb779f'
Do an Ocean tx, and wait for it to complete...
ERC721Factory @ 0x8930D1F61Defb9CBD652136B4C3D93f19AC35678
0x7138aad1670502d2bce0b1894e2bb893123c4be0ee66d9052a54bdd58a301b1c
=========================== short test summary info ============================
FAILED tests/integration/remote/test_mumbai.py::test_ocean_tx - IndexError: l...
============================== 1 failed in 8.04s ===============================
```

so, I started to check what is with that address (0x8930D1F61Defb9CBD652136B4C3D93f19AC35678), because it's not the  [mumbai erc721factory](https://github.com/oceanprotocol/contracts/blob/main/addresses/address.json#L46
And found it in 
```
less /home/alx/.ocean/ocean-contracts/artifacts/address.json | grep ERC721Factory

 "ERC721Factory": "0x465069D3d6Ec45CDB006ec3E22cC9E8d6f9793eF",
    "ERC721Factory": "0x7d46d74023507D30ccc2d3868129fbE4e400e40B",
    "ERC721Factory": "0xB0F8c68eF94ACB8E976b1dED6351Cc62e383d253",
    "ERC721Factory": "0x5b1E1b333B76BC81FA60cD986EA82487e4F72B8B"
    "ERC721Factory": "0x6fd867E5AEE6D62a24f97939db90C4e67A73A651",
    "ERC721Factory": "0xbFBc7A21133B4e0e54a182BE8d4337A5e036A615",
    "ERC721Factory": "0x4dD281EB67DED07E76E413Df16176D66ae69e240",
    "ERC721Factory": "0x86F2BB9F8f18B5a836b342199a3eC89F282E4018",
    "ERC721Factory": "0x1706DF1f2d93558D1d77bEd49ccdB8B88fAfC306",
    "ERC721Factory": "0xe8c6Dc39602031A152440311e364818ba25C2Bc1",
    "ERC721Factory": "0x1706DF1f2d93558D1d77bEd49ccdB8B88fAfC306"
    "ERC721Factory": "0x49E35cd2bAE043Abd9074B6e5a649a5AdEB05C33"
    "ERC721Factory": "0x8930D1F61Defb9CBD652136B4C3D93f19AC35678",
```
so, where is that coming from ?
```
"development": {
    "chainId": 8996,
    "Ocean": "0x2473f4F7bf40ed9310838edFCA6262C17A59DF64",
    "MockDAI": "0xaF6AaaA5B8D12F7d7dD4e2BE1d1B087544f585d0",
    "MockUSDC": "0x053aE1FeCdc2f391753E2Bf2AAe301E75CC0aac9",
    "OPFCommunityFeeCollector": "0x2fC1fd21cb222Dc180Ef817dE4c426fd9230b5A5",
    "startBlock": 5,
    "Router": "0x1e6d9207241DbDca82B0D9546490c97B24B1a9f6",
    "FixedPrice": "0xBb0911124E680D65358Ac46C5404D4dF01F03e80",
    "Staking": "0x98b6901cE7C9fc65dBeeC98598136593EB7b4c6C",
    "ERC20Template": {
      "1": "0x91EB42b164664cB28a09B0cF9651b404Ee105afA",
      "2": "0x9C2a015129969c98E9A5BcBEb61A5F907FF5b629"
    },
    "ERC721Template": {
      "1": "0x611f28Ef25D778aFC5a0034Aea94297e2c215a42"
    },
    "Dispenser": "0xe749E2f8482810b11B838Ae8c5eb69e54d610411",
    "ERC721Factory": "0x8930D1F61Defb9CBD652136B4C3D93f19AC35678",
```

so, it looks like ocean.py is unable to fetch ERC721Factory from mumbai, it always fetches the "development" addresses

**Comment by alexcos20** [comment]
So, added some debugs at https://github.com/oceanprotocol/ocean.py/blob/2a5c9fd9e626b06b3b16e4bbf82de60766a7af4c/ocean_lib/ocean/util.py#L83

```
 print(f"Config.address_file: {config.address_file}")
 print(f"Config.network_name: {config.network_name}")
```

and got:

```
---------------------------- Captured stdout call -----------------------------
config filename = /tmp/pytest-of-alx/pytest-7/test_ocean_tx0/config.ini
config.network_url = 'https://rpc-mumbai.maticvigil.com'
config.address_file = '/home/alx/.ocean/ocean-contracts/artifacts/address.json'
config.block_confirmations = 0
config.metadata_cache_uri = 'https://v4.aquarius.oceanprotocol.com'
config.provider_url = 'https://v4.provider.mumbai.oceanprotocol.com'
<ocean_lib.config.Config object at 0x7f34d8b92ac0>
<ocean_lib.ocean.ocean.Ocean object at 0x7f34d8b92a00>
alice_wallet.address = '0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544'
bob_wallet.address = '0xD6764a9F3387B14692CC783BcF5604a23EBb779f'
Do an Ocean tx, and wait for it to complete...
Config.address_file: /home/alx/.ocean/ocean-contracts/artifacts/address.json
Config.network_name: ganache
=========================== short test summary info ============================
FAILED tests/integration/remote/test_mumbai.py::test_ocean_tx - UnboundLocalE...
============================== 1 failed in 1.25s ===============================
```


so, you need one fix:   Add network_name to config like
```
# Create conf file
    conf_file = tmp_path / "config.ini"
    conf_file.write_text(
        """
[eth-network]
network = https://rpc-mumbai.maticvigil.com
network_name = mumbai
address.file = ~/.ocean/ocean-contracts/artifacts/address.json
block_confirmations = 0

[resources]
metadata_cache_uri = https://v4.aquarius.oceanprotocol.com
provider.url = https://v4.provider.mumbai.oceanprotocol.com
"""
    )
```

and it works:
```
(ocean.py) alx@ubuntu:/ocean/ocean.py$ pytest tests/integration/remote/test_mumbai.py::test_ocean_tx
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.1, pluggy-1.0.0
rootdir: /ocean/ocean.py, configfile: pytest.ini
plugins: env-0.6.2, web3-5.28.0
collected 1 item                                                               

tests/integration/remote/test_mumbai.py .                                [100%]

============================== 1 passed in 11.03s ==============================
(ocean.py) alx@ubuntu:/ocean/ocean.py$ 
```

This needs to be changed, there is no need to specify network_name when you already have the RPC connection.
The flow should be:
- put network_url in config
- fetch chainID from that connection ( https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html#getchainid)
- fetch corresponding addresses  (each deployment has a field called chainId)

**Comment by trentmc** [comment]
@alexcos20 , thank you very much!  🙏🙏🙏

I will follow up with this issue, and the new one that you created.

**Comment by trentmc** [comment]
> so, you need one fix:
> Add network_name to config at https://github.com/oceanprotocol/ocean.py/blob/main/tests/integration/remote/test_mumbai.py#L99 , like
> ..
> `network_name = mumbai`

This worked perfectly on my local machine. :100: 

Alas, it still has the same failure on CI tests. 
- [Here's the PR](https://github.com/oceanprotocol/ocean.py/pull/932). [Here's the failing test](https://github.com/oceanprotocol/ocean.py/actions/runs/3078921614/jobs/4974777959). 
- My guess is that it's still got some barge-related envvars set. E.g. envvar OCEAN_NETWORK_U
- My guess is that it's still got some barge-related envvars set. E.g. envvar OCEAN_NETWORK_URRL, maybe ADDRESS_FILE?
- A solution: set up a different Github Action just for this test, and any future remote tests. In that action, ensure barge isn't going, and if needed, unset envvars 
- If that doesn't work, I can do #927 and #931 - each fixes a specific Config issue, then revisit this.
