### ISSUE TITLE
Why does ocean.py source code hold a config.ini? It's error-prone

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#930]
Pre-requisite to this issue: [#938](https://github.com/oceanprotocol/ocean.py/issues/938) "Streamline Config: no config.ini file, no dict, just envvars." Then, doing this issue will be dead simple: delete it, since no config file exists:)

----

There's a `config.ini` file in the root directory of ocean.py.

Having this config around may hint that it's used somewhere, but it probably shouldn't be. People should be creating their own config.ini's. From #921 (and follow-up issues like #927) we've found that config is error-prone. 

TODO for this issue:
- identify where (if anywhere) that config.ini is actually used
- if possible (and if it makes sense), remove it

**Comment by alexcos20** [comment]
I would recommend to remove it and use env vars, which are more secure

**Comment by calina-c** [comment]
I completely agree, I would remove the entire config shennanigans and keep just env vars.

**Comment by trentmc** [comment]
Thanks, both. Sounds great. I just created a github issue in this vein.

Once we do that, we get to close _this_ issue immediately, and also at least two more.

https://github.com/oceanprotocol/ocean.py/issues/938

**Comment by trentmc** [comment]
#938 is done. So, we can close this issue:)
