### ISSUE TITLE
Config needs address_file specified for remote networks; it shouldn't (except for custom network)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#931]
Pre-requisite to this issue: [#971](https://github.com/oceanprotocol/ocean.py/issues/971) "Cleanup: import ocean-contracts library for Ocean addresses". That will either directly solve this issue, or make solving this issue trivial.

----

**Describe the bug**
In working on #923 "ocean.py has no remote tests", and other remote-related issues (#921, #909, more), it would fail unless I had the following line in `config.ini` to specify an `address.file`, e.g. like [here](https://github.com/oceanprotocol/ocean.py/blob/2a5c9fd9e626b06b3b16e4bbf82de60766a7af4c/tests/integration/remote/test_mumbai.py#L103) in `test_mumbai.py`.
```text
address.file = ~/.ocean/ocean-contracts/artifacts/address.json
```

If I didn't have that line, then it would fail.

Equivalently, if not set in the `config.ini` but rather as an envvar `ADDRESS_FILE`, same thing.

But I shouldn't have needed to, since ocean.py can simply import `ocean-contracts` pypi library (created by `oceanprotocol/contracts` repo). That library is small: it contains the addresses of Ocean contracts deployments.

**How it's supposed to work**

Here is how it's used in other components (ref Alex):
- if envvar ADDRESS_FILE exists, use that as path for addresses.json (very useful with barge)
- if not, then use the file that came from import ocean-contracts

So, when dealing with remote networks, you don't need to specify a path to `addresses.json`, it will just work
but when dealing with barge (or custom network), then by having `ADDRESS_FILE` you can control the list of addresses

The flow should be (ref Alex):
- put network_url in config
- fetch chainID from that connection ( https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html#getchainid)
- fetch corresponding addresses (each deployment has a field called chainId)

Related issue: #927 "Config needs both network and network_name; it shouldn't #927"

**Comment by calina-c** [comment]
A huge chunk of this is done from the config streamline and #937 (currently in review). I'll try closing this issue as well, using the same PR. I think there is very little work left to be done.
