### ISSUE TITLE
Deprecate 'artifacts' dir, point to contracts repo instead

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#95]
**Problem**

Right now the ocean.py repo has an `artifacts` directory, containing: 
* `address.json` - lists the address of each Ocean smart contract deployed to Eth mainnet, and other networks
* `BFactory.json` - ABI for BFactory smart contract
* `BPool.json` - ABI for BPool ..
* (and several more ABI jsons)

Issues: The redundant storage of this information means that whenever the contract deployments change (from contracts repo) this needs to get updated. That update may be forgotten (an error), or performed but with a mistake (an error). It also takes explicit effort (takes time) and violates DRY principle (Don't Repeat Yourself).

**Solution**

Deprecate ocean.py's `artifacts` directory. Instead look at the directory in ocean `contracts` repo. For both addresses and ABIs.

**Steps**

- [x] Get ocean.py unittests all running first, it's been a while :) (Exception: some break, see #156)
- [x] addresses: Write unit tests to capture current functionality
- [x] addresses: Write tests for new behavior
- [x] addresses: Implement new behavior, refine tests
- [x] ABIs: Write unit tests to capture current functionality
- [x] ABIs: Write tests for new behavior
- [x] ABIs: Implement new behavior, refine tests
- [x] Update READMEs that refer to the (to-be) deprecated directory
- [x] Update packaging logic to ignore new test directories
- [x] Merge etc
- [x] Deploy to pip

**Comment by trentmc** [comment]
Note: this is WIP in the branch: https://github.com/oceanprotocol/ocean.py/tree/issue95

**Comment by trentmc** [comment]
Here's where ocean.js grabs the info:
https://github.com/oceanprotocol/ocean.js/blob/main/src/utils/ConfigHelper.ts#L5

```javascript
import * as DefaultContractsAddresses from '@oceanprotocol/contracts/artifacts/address.json
```

And later in the file how it uses it:
```javascript
export class ConfigHelper {
  /* Load contract addresses from env ADDRESS_FILE (generated by ocean-contracts) */
  public getAddressesFromEnv(network: string): Partial<ConfigHelperConfig> {
    // use the defaults first
    let configAddresses: Partial<ConfigHelperConfig>
    if (DefaultContractsAddresses[network]) {
      const {
        DTFactory,
        BFactory,
        FixedRateExchange,
        Metadata,
        Ocean
      } = DefaultContractsAddresses[network]
      configAddresses = {
        factoryAddress: DTFactory,
        poolFactoryAddress: BFactory,
        fixedRateExchangeAddress: FixedRateExchange,
        metadataContractAddress: Metadata,
        oceanTokenAddress: Ocean,
        ...(process.env.AQUARIUS_URI && { metadataCacheUri: process.env.AQUARIUS_URI })
      }
    }
```

**Comment by trentmc** [comment]
Here's the file in the `contracts` repo:
https://github.com/oceanprotocol/contracts/blob/master/artifacts/address.json

The contents look like
```
{
  "rinkeby": {
    "DTFactory": "0x3fd7A00106038Fb5c802c6d63fa7147Fe429E83a",
    "BFactory": "0x53eDF9289B0898e1652Ce009AACf8D25fA9A42F8",
    "FixedRateExchange": "0xeD1DfC5F3a589CfC4E8B91C1fbfC18FC6699Fbde",
    "Metadata": "0xFD8a7b6297153397B7eb4356C47dbd381d58bFF4",
    "Ocean": "0x8967BCF84170c91B0d24D4302C2376283b0B3a07"
  },
  ...
  ```

**Comment by trentmc** [comment]
The ocean.py file of interest is https://github.com/oceanprotocol/ocean.py/blob/master/ocean_lib/config.py

It has parameter `DEFAULT_ADDRESS_FILE` which populates `ADDRESS_FILE`, which in turn populates:
```python
config_defaults = {
    "eth-network": {
        NAME_NETWORK_URL: DEFAULT_NETWORK_URL,
        NAME_ARTIFACTS_PATH: DEFAULT_ARTIFACTS_PATH,
        NAME_ADDRESS_FILE: DEFAULT_ADDRESS_FILE,
        NAME_GAS_LIMIT: GAS_LIMIT_DEFAULT,
    },
...
```

Which in turn is used as:
```python
class Config(configparser.ConfigParser):
...
    @property
    def address_file(self):
        file_path = self.get(self._section_name, NAME_ADDRESS_FILE)
        if file_path:
            file_path = Path(file_path).expanduser().resolve()

        if not file_path or not os.path.exists(file_path):
            file_path = os.path.join(self.artifacts_path, "address.json")

        return file_path
```

And that property is used in the following places. (From here on I will debug to myself lol)
```console
(venv) trentmc@trentmcLnv:~/code/ocean.py$ grep -r "\.address_file"
tests/models/conftest.py:        _NETWORK, ConfigProvider.get_config().address_file
tests/models/conftest.py:        _NETWORK, ConfigProvider.get_config().address_file
tests/models/conftest.py:        _NETWORK, ConfigProvider.get_config().address_file
deploy.py:        addresses_file = config.address_file
ocean_lib/ocean/util.py:            network, config.address_file
ocean_lib/ocean/util.py:            f"artifacts path is {ContractHandler.artifacts_path}, address file is {config.address_file}"
ocean_lib/ocean/util.py:            f"artifacts path is {ContractHandler.artifacts_path}, address file is {config.address_file}"
ocean_lib/ocean/util.py:        print(f"address file exists? {os.path.exists(config.address_file)}")
ocean_lib/ocean/util.py:        ConfigProvider.get_config().address_file,
ocean_lib/ocean/util.py:        ConfigProvider.get_config().address_file,
ocean_lib/ocean/ocean_assets.py:            Web3Helper.get_network_name(), self._config.address_file
ocean_lib/ocean/ocean.py:                ConfigProvider.get_config().address_file,
ocean_lib/ocean/ocean.py:            Web3Helper.get_network_name(), self._config.address_file
```

**Comment by ssallam** [comment]
if the address file path is specified in the config file or in the envvar then that is what will be used. When none of the above is declared, then it relies on the artifacts path. The artifacts path, if not specified in the config or env, will be extracted from the venv or the python installation.

**Comment by trentmc** [comment]
>  it relies on the artifacts path ...

Yep! Overall the path needs to be generalized to support files at a url. That's my approach in the [PR](https://github.com/oceanprotocol/ocean.py/pull/160). Many nuances to test for, but coming along:)

**Comment by trentmc** [comment]
I was going down a path of pointing to urls. Then I had a super useful call with @ssallam yesterday about how ocean-contracts are created and used as a python library. Some  surprising behavior. Towards fixing that behavior, I created [MultiRepo#83](https://github.com/oceanprotocol/multi-repo-issue/issues/83). It's a _multi-repo_ issue because there will be changes in both `ocean-contracts` repo and `ocean.py` repo.

For *this* issue, I'm going to try to do it with minimal changes using existing ocean-contracts setup. (Plus preserve all the unit tests I already created).

**Comment by trentmc** [comment]
S: To update the packaging logic to omit the tests.

T: Where to ignore?

S:
```
python setup.py install
python setup.py bdist_wheel
```
then take a look inside the build folder

**Comment by trentmc** [comment]
Note to self on setup.py's `packages` variable:

What it currently has: `['ocean_lib', 'ocean_lib.web3_internal', 'ocean_lib.web3_internal.web3_overrides', 'ocean_lib.web3_internal.test', 'ocean_lib.data_provider', 'ocean_lib.data_store', 'ocean_lib.assets', 'ocean_lib.models', 'ocean_lib.ocean', 'ocean_lib.test']`

What it _should_ have: `['ocean_lib', 'ocean_lib.web3_internal', 'ocean_lib.web3_internal.web3_overrides',  'ocean_lib.data_provider', 'ocean_lib.data_store', 'ocean_lib.assets', 'ocean_lib.models', 'ocean_lib.ocean']`

**Comment by trentmc** [comment]
Finished main work in commit https://github.com/oceanprotocol/ocean.py/commit/39f8a92b9b30defb2bacc2788c63a08d4afd455e

Now only pip remains, if we choose to do it here.

**Comment by trentmc** [comment]
Don't need to do it here. Closing.

**Comment by trentmc** [comment]
> Don't need to do it here. Closing.

I spoke too soon. We _did_ make changes to the code: removing the `artifacts/` directory. That definitely needs a new deploy to pip, with a quick readiness to revert in case it fails.

**Comment by trentmc** [comment]
Deployed to pip now.
