### ISSUE TITLE
Use or drop config GAS_LIMIT

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#955]
Pending discussion:
I have noticed that the GAS_LIMIT option inside the config was not actually used in gas calculations. I suggest we either work it into the calculation some way, or drop it from the config dict.

_Originally posted by @calina-c in https://github.com/oceanprotocol/ocean.py/issues/953#issuecomment-1254710160_

**Comment by trentmc** [comment]
Let's drop it.

(There are good args for this from a pure sw eng perspective, and from an EVM perspective)
