### ISSUE TITLE
Update prerequisites for python in READMEs 

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#965]
Update prerequisites for python in READMEs. Recently tried with python 3.10 and some dependencies from ocean-lib and it didn't work.

**Comment by trentmc** [comment]
FWIW, I'm on Python 3.10.4 and don't have any issues.

What are the specific issues?

**Comment by mariacarmina** [comment]
Hmm I think it was a venv issue when installing python dependencies that I have encountered together with @MBadea17. If it works from your end I think we can close this issue.
