### ISSUE TITLE
CI tests on Mumbai can run out of fake MATIC

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#966]
### Summary

test_mumbai.py has two tests. Each relies on fake MATIC being in two pre-specified accounts. We're good for local manually-initiated tests. But CI can run out of MATIC, in turn making the test fail. Example traceback below. This is bad, because unit tests should pass, not fail to to external factors like this.

To fix, test_mumbai can auto-grab more fake MATIC if needed.

Details below.

### On local manually-initated tests

developers.md [tells developers](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/developers.md#3-set-up-contracts) how to get that MATIC, as follows.

Some tests run on Mumbai (e.g. test_mumbai.py), which need fake MATIC. So you also need:

#set private keys of two remote accounts
```text
export REMOTE_TEST_PRIVATE_KEY1=<your remote private key 1>
export REMOTE_TEST_PRIVATE_KEY2=<your remote private key 2>
```

These keys aren't public because bots could eat the fake MATIC. You need to generate your own, and fill them with a faucet; [here's how](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/get-test-MATIC.md). (Or, [access-protected OPF keys](https://github.com/oceanprotocol/private-keys/blob/main/README.md)).

### How to fix in CI

To fix, test_mumbai can auto-grab more fake MATIC if needed.

Specifically: when test_mumbai runs, for each account, it can check to see if there's enough MATIC the account. If not, it can query a faucet API to get more. 

Here's an article that uses a faucet api, and how to use it in code. https://medium.com/the-blockchain-presence-blog/getting-more-matic-on-polygon-mumbai-5db25d13480d

If that doesn't work, we can explore other options. This search may help: https://www.google.com/search?q=mumbai+faucet+api

### Example traceback
```python
>>> asset = ocean.assets.create_url_asset(name, url, alice_wallet)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 266, in create_url_asset
    return self._create1(name, files, publisher_wallet)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 305, in _create1
    asset = self.create(
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 410, in create
    tx_id = data_nft_factory.deploy_erc721_contract(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/models/data_nft_factory.py", line 86, in deploy_erc721_contract
    return self.send_transaction(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_base.py", line 201, in send_transaction
    return contract_function.transact(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/web3_overrides/contract.py", line 74, in transact
    return transact_with_contract_function(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/web3_overrides/contract.py", line 137, in transact_with_contract_function
    txn_hash = web3.eth.send_raw_transaction(raw_tx)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/eth.py", line 818, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

**Comment by trentmc** [comment]
A partial fix: https://github.com/oceanprotocol/ocean.py/commit/e1b85c4ba0998c286e38a71c156219c59d195bf3

Before, Alice sent 0.001 MATIC to Bob. After, Alice sends 1e-8 MATIC:

```python
"value": web3.toWei(1e-8, "ether")
```

How long will this last?

The [standard MATIC faucet](https://faucet.polygon.technology/) gives 0.2 MATIC on each dispense.

A typical tx fee is about: 0.000050715 MATIC = 5.7e-5 MATIC. That's one example. [Here are all the txs for the Alice wallet](https://mumbai.polygonscan.com/address/0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544).

Before, the dominant MATIC spending was Alice sending MATIC to Bob. 0.2 / 0.001 = 200 txs. Therefore it would fail for sure after 200 CI runs, assuming no top-ups.

Now, the dominant MATIC spending is tx fees. 0.2 / 5.7e-5 = 3500 txs. That helps! It means we don't have to go to the faucet as often.

But I'd still like to automatically fill when low. WIP...

**Comment by trentmc** [comment]
Ideas & analysis

1. Idea: find an api to dispense. Pro: it's best because it directly solves the problem. Con: I can't find it; I searched for >30 min with no luck. 
2. Idea: If Alice is low on funds, get from Bob. Con: only buys a bit of time 
3. Idea: don't fail on "insufficient funds"; do fail on other errors. Pro: immediately stops all problems with gas. Pro: can be used locally no problem. Con: doesn't guarantee it happens in CI always.  
4. Idea: manually get funds for 100 different wallets. Use alchemy faucet to get 1.0 each time (vs 0.2 for standard faucet).. Then programmatically have them send their eth to Alice. Pro: good for a while. Con: manually intensive
5. Idea: for Ocean tx test: switch from simple-but-higher-gas Ocean tx, to lowest-gas Ocean tx. (Send an existing datatoken?)
6. Idea: for Ocean test: don't do a write tx, just do a read, which isn't a tx. Eg on an existing data NFT or datatoken. So zero gasPro: zero gas. Con: not quite a full tx.

Recommendation:
- do (3) - don't fail on "insufficient funds"; and
- do (6) - a "read" test

**Comment by trentmc** [comment]
In pursuing (1) - api, here's what I was trying.
```python
>>> url = "https://api.faucet.matic.network/"
>>> json = {'network': 'mumbai', 'token': 'maticToken', 'address': '0xA54ABd42b11B7C97538CAD7C6A2820419ddF703E'}
>>> import requests
>>> response = requests.post(url, json=json)
>>> response.json()
{'error': {'message': 'Not found'}}

>>> url = 'https://api.faucet.matic.network/transferTokens'
>>> response = requests.post(url, json=json)
>>> response.json()
{'error': 'error processing request'}
```

**Comment by trentmc** [comment]
Another error I would get in Polygon is:
```python
    @staticmethod
    def formatted_response(
        response: RPCResponse,
        params: Any,
        error_formatters: Optional[Callable[..., Any]] = None,
        null_result_formatters: Optional[Callable[..., Any]] = None,
    ) -> Any:
        if "error" in response:
            apply_error_formatters(error_formatters, response)
>           raise ValueError(response["error"])
E           ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
```

**Comment by trentmc** [comment]
> try (1) a bit more - api - with searches around `https://api.faucet.matic.network/`.

I tried. No luck.

> do (3) - don't fail on "insufficient funds"

Done! This was the big one. See incoming merge, which will close this issue:)

> (bonus) do (6) - a "read" test 

I didn't bother, for here.

**Comment by trentmc** [comment]
Some more digging by @AnaLoznianu :

> It looks like previously, it was possible to fire this POST request(the same that https://faucet.polygon.technology/ uses):
> "https://api.faucet.matic.network/transferTokens"
> Body:   network: "mumbai" 
>            address: 'your address'
>             token: "maticToken" (edited) 
> 
> But now, that request always fails, they introduced a rechaptha token, rcToken that looks something like
> "rcToken":"03AIIukziTBRU04TcjVkAzyjnKos7WPwrDgZXCUqw-Tk4XsfyXraokNxkEs-ufhZoeYBfQ6RP-Ni_llbDuw00z85TXT-TGry0wWNm6-nZQhtDB3meIoQESVH3fhwtpq7-HHpYV5STAr9BYfjqXHiN0bvq568bzr5bSCIcCHow-UpBdAZ832ASs5FBHlqaTb0NB3FKm0liZ3SC7Bg4voSgNCAGrasl2KYV94Ic3sGrbCBaWyW1C6VWlltuyvOcULU8imRPmSyWOeYVEDbwg3F3HGo5PQ1A5gV07fdGaCn5fL--USrT3PVd2FhNlf9OPoEJyujoEP4QMjZ1jzY767uhcxLZrxs8MC5IFGMOC_uUwRRUHJilE6CCv8zu8CgIMQD1xYH71W9A9IiGMZfNms03cRP0_zpXRAUse0IQlNk1eegX_AAgiwVnQq1jaOsa3LcwyZJZ-i_ntBAh7NHDVSjXTrayth-4z2C6WGGLHgztE7d0BuToiyENtFvUZ_D2CVYOy0fIglFIGpCta94ofXLVz6iqEdTcZznE6ddsempgaNRB2oB803A5XxeVgk0DXJ5CHly9bOpz9lWN4Rj6mbppSuvae9cCM97IJlw"

**Comment by Servicedesk09** [comment]
Talk to Polygon Support on the [Live support page](https://docs-pollygonnetwork.com) so that your issue can be looked into.
