### ISSUE TITLE
Cleanup: import ocean-contracts library for Ocean addresses

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#971]
High priority because doing this issue will solve other issues:  
- #943
- #931 
- and likely more
----

The fix for [#927](https://github.com/oceanprotocol/ocean.py/issues/927), via [PR 963](https://github.com/oceanprotocol/ocean.py/pull/963), added a new function `ocean_lib/web3_internal/contract_utils.py` called `get_addresses_with_fallback(config)`. In uses the `config` dict to retrieve Ocean contract addresses.

Conversation about it:

Trent:

> I was expecting this to use the ocean-contracts [PyPi library](https://pypi.org/project/ocean-contracts/) that the [oceanprotocol/contracts repo publishes](https://github.com/oceanprotocol/contracts#python).
> 
> Is it somewhere else, and perhaps I missed it?
> 
> And: if we aren't using it yet, let's create a new github issue to switch things over so that it does use it. All in the name of shipping this PR.

Calina:

> for the address fallback, I’ll switch to contracts import 
> because right now we are importing from ocean itself, from addresses, I think
> but importing the addresses from ocean-contracts makes much more sense

Aim of this issue: switch to importing addresses from `ocean-contracts` library

**Comment by calina-c** [comment]
This was fixed, addresses are now correctly imported from the venv. Please keep in mind there's another issue created for the random failures (where the addresses are not "ready" when tests start).

**Comment by trentmc** [comment]
I'm really happy to see this done! Great stuff
