### ISSUE TITLE
"read operation timed out" error when downloading asset in predict-eth.md

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#981]
From @trentmc: 

The challenge is that is can't download the new CEXA asset.

Here's how to reproduce:
1. go to the [predict-eth.md that has the issue](https://github.com/oceanprotocol/ocean.py/blob/164a60cc1c94ef839b55f71ec05d9e84f743ff39/READMEs/predict-eth.md). (Note: we put a non-Ocean workaround into main [predict-eth.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md) so that competitors aren't blocked. Once we fix the issue, we will revive)
2. Start working through it
3. It will fail in step 2, at `ocean.assets.download_asset()` call. [full-log.txt](https://github.com/oceanprotocol/ocean.py/files/9706410/full-log.txt)

Another way: publish the url for yourself on any network (ganache, or Mumbai,..) and then try to consume. https://cexa.oceanprotocol.io/ohlc?exchange=binance&pair=ETH/USDT

Note: the following does work for Trent, and Alex: go to the asset on Ocean Market and try to consume https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19

**Comment by trentmc** [comment]
FYI I put in a placeholder fix: use ccxt instead of an Ocean asset

https://github.com/oceanprotocol/ocean.py/pull/982

**Comment by trentmc** [comment]
Alex is digging more, realtime with me.

He tried to download the asset directly, without ocean.py, and it worked.

So the failure is in ocean.py. It fails due to a timeout issue. It appears that ocean.py wants the result immediately.

We're digging more...

**Comment by trentmc** [comment]
It auto-closed from the new PR. Re-opening until we confirm that the README works too.

**Comment by trentmc** [comment]
Updated the assignees based on what's still left. Thanks @mariacarmina for investigating. @alexcos20 was a huge help to solve this. I can take it from here.
