### ISSUE TITLE
"Invalid signature provided" error when downloading asset in predict-eth.md

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#984]
In step 2 of the [predict-eth.md](https://github.com/oceanprotocol/ocean.py/blob/164a60cc1c94ef839b55f71ec05d9e84f743ff39/READMEs/predict-eth.md)
- I'm doing a call to `ocean.assets.download_asset()`
- The first error was "read operation timed out". But we fixed that in [#981](https://github.com/oceanprotocol/ocean.py/issues/981).
- Alex doesn't get more errors. But I (Trent) do: "Invalid signature provided". My guess at the difference: maybe Alex didn't have previous failures to download from that wallet?

```
python
>>> file_path = ocean.assets.download_asset(
...     asset=asset,
...     consumer_wallet=alice_wallet,
...     destination='./',
...     order_tx_id=order_tx_id
... )
INFO:ocean_lib.data_provider.fileinfo_provider:Retrieved asset files successfully FileInfoEndpoint https://v4.provider.polygon.oceanprotocol.com/api/services/fileinfo from did did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19 with service id 8e2e09fd9b02e0b7e9c0d0e01c6f500e2a07aa305c04144ad96babf50b820c87
signing message with nonce 1664905891.738489: did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19, account=0xB5958aC6D6B062c0c9eD579fb1B488Caa4F4e5ee
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 720, in download_asset
    return download_asset_files(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/assets/asset_downloader.py", line 73, in download_asset_files
    data_provider.download(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/data_provider/data_service_provider.py", line 185, in download
    DataServiceProviderBase.check_response(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/data_provider/base.py", line 303, in check_response
    raise DataProviderException(f"{endpoint_name} failed: {error}")
ocean_lib.exceptions.DataProviderException: downloadEndpoint failed: {'signature': ['Invalid signature provided.']}
```

**Comment by trentmc** [comment]
Update: it fails on this address of Trent's: 611e7adc31bc4dad284ba8385371310e77812681bb7e582f3446d8f127f6da2a

But not on this address of Trent's: 0x7BA3d8551A6f2C70a5d47bb448BcF7EF69661822

Alex will investigate further.

But this isn't holding us back from shipping the README with the previous fix

**Comment by calina-c** [comment]
@trentmc those addresses don't look like they are the same thing: they are different in length, different in format (the first doesn't start with 0x). How did you make the addresses in the first place?

**Comment by trentmc** [comment]
> @trentmc those addresses don't look like they are the same thing: they are different in length, different in format (the first doesn't start with 0x). How did you make the addresses in the first place?

Whups I gave the wrong info for my erroneous address, in that [comment](https://github.com/oceanprotocol/ocean.py/issues/984#issuecomment-1266968388). Corrected, in the comment.

**Comment by AnaLoznianu** [comment]
Is this issue still valid?

**Comment by trentmc** [comment]
I haven't seen it recently. 

I just tested going through the README, with the default provided private keys. It worked.

Let's close this issue. If it reappears, we can reopen it, or create a new issue.
