### ISSUE TITLE
"AssetNotConsumable" error in CI tests: 4 x test_compute_flow.py, 1 x test_readmes.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#988]
Note: So that the 4 x test_compute_flow.py don't break other tests, they're now skipped until this issue is fixed, via these commits: https://github.com/oceanprotocol/ocean.py/commit/71c7d305d9b79a50a3eef87a94a7d3661c147717,  https://github.com/oceanprotocol/ocean.py/commit/e5961806961d0e4b4f216dacd4e1f0b115dfd5d3

----

### Issues Seen

From [this CI test](https://github.com/oceanprotocol/ocean.py/actions/runs/3183868467/jobs/5191599078#step:7:1462), we got two failures: 
```
FAILED tests/integration/ganache/test_compute_flow.py::test_compute_multi_inputs
ERROR tests/integration/ganache/test_compute_flow.py::test_compute_trusted_algorithm
```

Then, from [this CI test](https://github.com/oceanprotocol/ocean.py/actions/runs/3185961560/jobs/5196094248) - after the first two tests were turned off - we got two more failures:
```
FAILED tests/integration/ganache/test_compute_flow.py::test_compute_registered_algo
FAILED tests/integration/ganache/test_compute_flow.py::test_compute_reuse_order
```

At first I thought these tests were random. But now I'm not so sure, given that it's a common error across thet tests: `AssetNotConsumable`.

### Notes

Note: the test file `test_compute_flow.py` has 8 tests total, as shown below. We've already seen four fail randomly. Maybe more do too?
```text
def test_compute_raw_algo()
def test_compute_registered_algo()
def test_compute_reuse_order()
def test_compute_multi_inputs() 
def test_compute_trusted_algorithm()
def test_compute_update_trusted_algorithm()
def test_compute_trusted_publisher()
def test_compute_just_provider_fees()
```

**Comment by calina-c** [comment]
I might wait for the latest provider fixes to tackle this one.
